ofcmdln.o: ofcmdln.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/ofcmdln.h ../include/oftypes.h \
  ../include/oflist.h ../include/ofcast.h ../include/ofstdinc.h \
  ../include/ofstring.h ../include/ofstream.h ../include/ofconsol.h \
  ../include/ofthread.h ../include/ofstd.h
ofconapp.o: ofconapp.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/ofconapp.h \
  ../include/oftypes.h ../include/ofcmdln.h ../include/oflist.h \
  ../include/ofcast.h ../include/ofstdinc.h ../include/ofstring.h \
  ../include/ofstream.h ../include/ofconsol.h ../include/ofthread.h
ofcond.o: ofcond.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/ofcond.h ../include/oftypes.h \
  ../include/ofstring.h ../include/ofcast.h ../include/ofstdinc.h \
  ../include/ofstream.h
ofconfig.o: ofconfig.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/ofconfig.h \
  ../include/ofstring.h ../include/oftypes.h ../include/ofcast.h \
  ../include/ofstdinc.h ../include/ofstream.h ../include/ofstack.h
ofconsol.o: ofconsol.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/ofconsol.h \
  ../include/ofstream.h ../include/ofthread.h ../include/oftypes.h \
  ../include/ofstring.h ../include/ofcast.h ../include/ofstdinc.h
ofcrc32.o: ofcrc32.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/ofcrc32.h ../include/ofcast.h
ofdate.o: ofdate.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/ofdate.h ../include/ofstring.h \
  ../include/oftypes.h ../include/ofcast.h ../include/ofstdinc.h \
  ../include/ofstream.h
ofdatime.o: ofdatime.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/ofstdinc.h \
  ../include/ofdatime.h ../include/ofstring.h ../include/oftypes.h \
  ../include/ofcast.h ../include/ofstream.h ../include/ofdate.h \
  ../include/oftime.h
offname.o: offname.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/offname.h ../include/oftypes.h \
  ../include/ofstring.h ../include/ofcast.h ../include/ofstdinc.h \
  ../include/ofstream.h
oflist.o: oflist.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/oflist.h ../include/oftypes.h \
  ../include/ofcast.h ../include/ofstdinc.h
oflogfil.o: oflogfil.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/oflogfil.h \
  ../include/ofthread.h ../include/oftypes.h ../include/ofstring.h \
  ../include/ofcast.h ../include/ofstdinc.h ../include/ofstream.h \
  ../include/ofdatime.h ../include/ofdate.h ../include/oftime.h
ofstd.o: ofstd.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/ofstd.h ../include/oflist.h \
  ../include/oftypes.h ../include/ofcast.h ../include/ofstdinc.h \
  ../include/ofstring.h ../include/ofstream.h
ofstring.o: ofstring.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/ofstring.h \
  ../include/oftypes.h ../include/ofcast.h ../include/ofstdinc.h \
  ../include/ofstream.h
ofthread.o: ofthread.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/ofstdinc.h \
  ../include/ofthread.h ../include/oftypes.h ../include/ofstring.h \
  ../include/ofcast.h ../include/ofstream.h ../include/ofconsol.h
oftime.o: oftime.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/ofstdinc.h ../include/oftime.h \
  ../include/ofstring.h ../include/oftypes.h ../include/ofcast.h \
  ../include/ofstream.h ../include/ofstd.h ../include/oflist.h
