tlslayer.o: tlslayer.cc ../../config/include/dcmtk/config/osconfig.h \
 ../include/dcmtk/dcmtls/tlsdefin.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h
tlsscu.o: tlsscu.cc ../../config/include/dcmtk/config/osconfig.h
tlstrans.o: tlstrans.cc ../../config/include/dcmtk/config/osconfig.h
