mkreport.o: mkreport.cc ../../config/include/dcmtk/config/osconfig.h \
 ../include/dcmtk/dcmsr/dsrdoc.h ../include/dcmtk/dcmsr/dsrdoctr.h \
 ../include/dcmtk/dcmsr/dsrdocst.h ../include/dcmtk/dcmsr/dsrtree.h \
 ../include/dcmtk/dcmsr/dsrtypes.h ../include/dcmtk/dcmsr/dsdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcelem.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcobject.h \
 ../../ofstd/include/dcmtk/ofstd/ofglobal.h \
 ../../ofstd/include/dcmtk/ofstd/ofthread.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcerror.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdefine.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcxfer.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctypes.h \
 ../../oflog/include/dcmtk/oflog/oflog.h \
 ../../oflog/include/dcmtk/oflog/logger.h \
 ../../oflog/include/dcmtk/oflog/config.h \
 ../../oflog/include/dcmtk/oflog/config/defines.h \
 ../../oflog/include/dcmtk/oflog/helpers/threadcf.h \
 ../../oflog/include/dcmtk/oflog/loglevel.h \
 ../../ofstd/include/dcmtk/ofstd/ofvector.h \
 ../../oflog/include/dcmtk/oflog/tstring.h \
 ../../oflog/include/dcmtk/oflog/tchar.h \
 ../../oflog/include/dcmtk/oflog/spi/apndatch.h \
 ../../oflog/include/dcmtk/oflog/appender.h \
 ../../ofstd/include/dcmtk/ofstd/ofmem.h \
 ../../ofstd/include/dcmtk/ofstd/ofutil.h \
 ../../ofstd/include/dcmtk/ofstd/oftraits.h \
 ../../ofstd/include/dcmtk/ofstd/variadic/tuplefwd.h \
 ../../oflog/include/dcmtk/oflog/layout.h \
 ../../oflog/include/dcmtk/oflog/streams.h \
 ../../oflog/include/dcmtk/oflog/helpers/pointer.h \
 ../../oflog/include/dcmtk/oflog/thread/syncprim.h \
 ../../oflog/include/dcmtk/oflog/spi/filter.h \
 ../../oflog/include/dcmtk/oflog/helpers/lockfile.h \
 ../../oflog/include/dcmtk/oflog/spi/logfact.h \
 ../../oflog/include/dcmtk/oflog/logmacro.h \
 ../../oflog/include/dcmtk/oflog/helpers/snprintf.h \
 ../../oflog/include/dcmtk/oflog/tracelog.h \
 ../../ofstd/include/dcmtk/ofstd/ofconapp.h \
 ../../ofstd/include/dcmtk/ofstd/ofcmdln.h \
 ../../ofstd/include/dcmtk/ofstd/ofexbl.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../../ofstd/include/dcmtk/ofstd/ofconsol.h \
 ../../ofstd/include/dcmtk/ofstd/offile.h \
 ../../ofstd/include/dcmtk/ofstd/ofstd.h \
 ../../ofstd/include/dcmtk/ofstd/oflimits.h \
 ../../config/include/dcmtk/config/arith.h \
 ../../ofstd/include/dcmtk/ofstd/oferror.h \
 ../../ofstd/include/dcmtk/ofstd/ofexit.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvr.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctag.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctagkey.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcstack.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcitem.h \
 ../../dcmdata/include/dcmtk/dcmdata/dclist.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcpcache.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcsequen.h \
 ../include/dcmtk/dcmsr/dsrtncsr.h ../include/dcmtk/dcmsr/dsrposcn.h \
 ../include/dcmtk/dcmsr/dsrtnant.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../include/dcmtk/dcmsr/dsrdoctn.h ../include/dcmtk/dcmsr/dsrcodvl.h \
 ../include/dcmtk/dcmsr/dsrdncsr.h ../include/dcmtk/dcmsr/dsrdnflt.h \
 ../../ofstd/include/dcmtk/ofstd/ofdatime.h \
 ../../ofstd/include/dcmtk/ofstd/ofdate.h \
 ../../ofstd/include/dcmtk/ofstd/oftime.h \
 ../include/dcmtk/dcmsr/dsritcsr.h ../include/dcmtk/dcmsr/dsrcitem.h \
 ../include/dcmtk/dcmsr/dsrnumvl.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrfd.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrsl.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrul.h \
 ../include/dcmtk/dcmsr/dsrscovl.h ../include/dcmtk/dcmsr/dsrscogr.h \
 ../include/dcmtk/dcmsr/dsrtlist.h ../include/dcmtk/dcmsr/dsrsc3vl.h \
 ../include/dcmtk/dcmsr/dsrsc3gr.h ../include/dcmtk/dcmsr/dsrtcovl.h \
 ../include/dcmtk/dcmsr/dsrtcodt.h ../include/dcmtk/dcmsr/dsrtcosp.h \
 ../include/dcmtk/dcmsr/dsrtcoto.h ../include/dcmtk/dcmsr/dsrcomvl.h \
 ../include/dcmtk/dcmsr/dsrimgvl.h ../include/dcmtk/dcmsr/dsrimgfr.h \
 ../include/dcmtk/dcmsr/dsrimgse.h ../include/dcmtk/dcmsr/dsrwavvl.h \
 ../include/dcmtk/dcmsr/dsrwavch.h ../include/dcmtk/dcmsr/dsrrtpl.h \
 ../include/dcmtk/dcmsr/dsrctpl.h ../include/dcmtk/dcmsr/dsrsoprf.h \
 ../include/dcmtk/dcmsr/dsrrefin.h ../include/dcmtk/dcmsr/dsrcsidl.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrcs.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcbytstr.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrda.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvris.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrlo.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcchrstr.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrpn.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrsh.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrtm.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrui.h \
 ../include/dcmtk/dcmsr/codes/ucum.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctk.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcswap.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcistrma.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcostrma.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcuid.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdicent.h \
 ../../dcmdata/include/dcmtk/dcmdata/dchashdi.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdict.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdeftag.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcmetinf.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdatset.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcfilefo.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdicdir.h \
 ../../ofstd/include/dcmtk/ofstd/ofmap.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdirrec.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrulup.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcpixseq.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcofsetl.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrae.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvras.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrds.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrdt.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrur.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrlt.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrst.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvruc.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrut.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrobow.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcpixel.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrpobw.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcovlay.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrat.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrss.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrus.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrsv.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvruv.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrfl.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrof.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrod.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrol.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrov.h \
 ../../dcmdata/include/dcmtk/dcmdata/cmdlnarg.h
read1500.o: read1500.cc ../../config/include/dcmtk/config/osconfig.h \
 ../include/dcmtk/dcmsr/dsrdoc.h ../include/dcmtk/dcmsr/dsrdoctr.h \
 ../include/dcmtk/dcmsr/dsrdocst.h ../include/dcmtk/dcmsr/dsrtree.h \
 ../include/dcmtk/dcmsr/dsrtypes.h ../include/dcmtk/dcmsr/dsdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcelem.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcobject.h \
 ../../ofstd/include/dcmtk/ofstd/ofglobal.h \
 ../../ofstd/include/dcmtk/ofstd/ofthread.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcerror.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdefine.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcxfer.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctypes.h \
 ../../oflog/include/dcmtk/oflog/oflog.h \
 ../../oflog/include/dcmtk/oflog/logger.h \
 ../../oflog/include/dcmtk/oflog/config.h \
 ../../oflog/include/dcmtk/oflog/config/defines.h \
 ../../oflog/include/dcmtk/oflog/helpers/threadcf.h \
 ../../oflog/include/dcmtk/oflog/loglevel.h \
 ../../ofstd/include/dcmtk/ofstd/ofvector.h \
 ../../oflog/include/dcmtk/oflog/tstring.h \
 ../../oflog/include/dcmtk/oflog/tchar.h \
 ../../oflog/include/dcmtk/oflog/spi/apndatch.h \
 ../../oflog/include/dcmtk/oflog/appender.h \
 ../../ofstd/include/dcmtk/ofstd/ofmem.h \
 ../../ofstd/include/dcmtk/ofstd/ofutil.h \
 ../../ofstd/include/dcmtk/ofstd/oftraits.h \
 ../../ofstd/include/dcmtk/ofstd/variadic/tuplefwd.h \
 ../../oflog/include/dcmtk/oflog/layout.h \
 ../../oflog/include/dcmtk/oflog/streams.h \
 ../../oflog/include/dcmtk/oflog/helpers/pointer.h \
 ../../oflog/include/dcmtk/oflog/thread/syncprim.h \
 ../../oflog/include/dcmtk/oflog/spi/filter.h \
 ../../oflog/include/dcmtk/oflog/helpers/lockfile.h \
 ../../oflog/include/dcmtk/oflog/spi/logfact.h \
 ../../oflog/include/dcmtk/oflog/logmacro.h \
 ../../oflog/include/dcmtk/oflog/helpers/snprintf.h \
 ../../oflog/include/dcmtk/oflog/tracelog.h \
 ../../ofstd/include/dcmtk/ofstd/ofconapp.h \
 ../../ofstd/include/dcmtk/ofstd/ofcmdln.h \
 ../../ofstd/include/dcmtk/ofstd/ofexbl.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../../ofstd/include/dcmtk/ofstd/ofconsol.h \
 ../../ofstd/include/dcmtk/ofstd/offile.h \
 ../../ofstd/include/dcmtk/ofstd/ofstd.h \
 ../../ofstd/include/dcmtk/ofstd/oflimits.h \
 ../../config/include/dcmtk/config/arith.h \
 ../../ofstd/include/dcmtk/ofstd/oferror.h \
 ../../ofstd/include/dcmtk/ofstd/ofexit.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvr.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctag.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctagkey.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcstack.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcitem.h \
 ../../dcmdata/include/dcmtk/dcmdata/dclist.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcpcache.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcsequen.h \
 ../include/dcmtk/dcmsr/dsrtncsr.h ../include/dcmtk/dcmsr/dsrposcn.h \
 ../include/dcmtk/dcmsr/dsrtnant.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../include/dcmtk/dcmsr/dsrdoctn.h ../include/dcmtk/dcmsr/dsrcodvl.h \
 ../include/dcmtk/dcmsr/dsrdncsr.h ../include/dcmtk/dcmsr/dsrdnflt.h \
 ../../ofstd/include/dcmtk/ofstd/ofdatime.h \
 ../../ofstd/include/dcmtk/ofstd/ofdate.h \
 ../../ofstd/include/dcmtk/ofstd/oftime.h \
 ../include/dcmtk/dcmsr/dsritcsr.h ../include/dcmtk/dcmsr/dsrcitem.h \
 ../include/dcmtk/dcmsr/dsrnumvl.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrfd.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrsl.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrul.h \
 ../include/dcmtk/dcmsr/dsrscovl.h ../include/dcmtk/dcmsr/dsrscogr.h \
 ../include/dcmtk/dcmsr/dsrtlist.h ../include/dcmtk/dcmsr/dsrsc3vl.h \
 ../include/dcmtk/dcmsr/dsrsc3gr.h ../include/dcmtk/dcmsr/dsrtcovl.h \
 ../include/dcmtk/dcmsr/dsrtcodt.h ../include/dcmtk/dcmsr/dsrtcosp.h \
 ../include/dcmtk/dcmsr/dsrtcoto.h ../include/dcmtk/dcmsr/dsrcomvl.h \
 ../include/dcmtk/dcmsr/dsrimgvl.h ../include/dcmtk/dcmsr/dsrimgfr.h \
 ../include/dcmtk/dcmsr/dsrimgse.h ../include/dcmtk/dcmsr/dsrwavvl.h \
 ../include/dcmtk/dcmsr/dsrwavch.h ../include/dcmtk/dcmsr/dsrrtpl.h \
 ../include/dcmtk/dcmsr/dsrctpl.h ../include/dcmtk/dcmsr/dsrsoprf.h \
 ../include/dcmtk/dcmsr/dsrrefin.h ../include/dcmtk/dcmsr/dsrcsidl.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrcs.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcbytstr.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrda.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvris.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrlo.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcchrstr.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrpn.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrsh.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrtm.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrui.h \
 ../include/dcmtk/dcmsr/dsrcodtn.h ../include/dcmtk/dcmsr/dsrimgtn.h \
 ../include/dcmtk/dcmsr/dsrnumtn.h ../include/dcmtk/dcmsr/dsrtextn.h \
 ../include/dcmtk/dcmsr/dsrstrvl.h ../include/dcmtk/dcmsr/dsruidtn.h \
 ../include/dcmtk/dcmsr/codes/dcm.h ../include/dcmtk/dcmsr/codes/ncit.h \
 ../include/dcmtk/dcmsr/codes/srt.h ../include/dcmtk/dcmsr/codes/umls.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcfilefo.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdatset.h
tests.o: tests.cc ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/oftest.h \
 ../../ofstd/include/dcmtk/ofstd/ofconapp.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../../ofstd/include/dcmtk/ofstd/ofcmdln.h \
 ../../ofstd/include/dcmtk/ofstd/ofexbl.h \
 ../../ofstd/include/dcmtk/ofstd/oftraits.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofconsol.h \
 ../../ofstd/include/dcmtk/ofstd/ofthread.h \
 ../../ofstd/include/dcmtk/ofstd/offile.h \
 ../../ofstd/include/dcmtk/ofstd/ofstd.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/oflimits.h \
 ../../config/include/dcmtk/config/arith.h \
 ../../ofstd/include/dcmtk/ofstd/oferror.h \
 ../../ofstd/include/dcmtk/ofstd/ofexit.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcuid.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdefine.h \
 ../../oflog/include/dcmtk/oflog/oflog.h \
 ../../oflog/include/dcmtk/oflog/logger.h \
 ../../oflog/include/dcmtk/oflog/config.h \
 ../../oflog/include/dcmtk/oflog/config/defines.h \
 ../../oflog/include/dcmtk/oflog/helpers/threadcf.h \
 ../../oflog/include/dcmtk/oflog/loglevel.h \
 ../../ofstd/include/dcmtk/ofstd/ofvector.h \
 ../../oflog/include/dcmtk/oflog/tstring.h \
 ../../oflog/include/dcmtk/oflog/tchar.h \
 ../../oflog/include/dcmtk/oflog/spi/apndatch.h \
 ../../oflog/include/dcmtk/oflog/appender.h \
 ../../ofstd/include/dcmtk/ofstd/ofmem.h \
 ../../ofstd/include/dcmtk/ofstd/ofutil.h \
 ../../ofstd/include/dcmtk/ofstd/variadic/tuplefwd.h \
 ../../oflog/include/dcmtk/oflog/layout.h \
 ../../oflog/include/dcmtk/oflog/streams.h \
 ../../oflog/include/dcmtk/oflog/helpers/pointer.h \
 ../../oflog/include/dcmtk/oflog/thread/syncprim.h \
 ../../oflog/include/dcmtk/oflog/spi/filter.h \
 ../../oflog/include/dcmtk/oflog/helpers/lockfile.h \
 ../../oflog/include/dcmtk/oflog/spi/logfact.h \
 ../../oflog/include/dcmtk/oflog/logmacro.h \
 ../../oflog/include/dcmtk/oflog/helpers/snprintf.h \
 ../../oflog/include/dcmtk/oflog/tracelog.h
tsrcmr.o: tsrcmr.cc ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/oftest.h \
 ../../ofstd/include/dcmtk/ofstd/ofconapp.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../../ofstd/include/dcmtk/ofstd/ofcmdln.h \
 ../../ofstd/include/dcmtk/ofstd/ofexbl.h \
 ../../ofstd/include/dcmtk/ofstd/oftraits.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofconsol.h \
 ../../ofstd/include/dcmtk/ofstd/ofthread.h \
 ../../ofstd/include/dcmtk/ofstd/offile.h \
 ../../ofstd/include/dcmtk/ofstd/ofstd.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/oflimits.h \
 ../../config/include/dcmtk/config/arith.h \
 ../../ofstd/include/dcmtk/ofstd/oferror.h \
 ../../ofstd/include/dcmtk/ofstd/ofexit.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcuid.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdefine.h \
 ../../oflog/include/dcmtk/oflog/oflog.h \
 ../../oflog/include/dcmtk/oflog/logger.h \
 ../../oflog/include/dcmtk/oflog/config.h \
 ../../oflog/include/dcmtk/oflog/config/defines.h \
 ../../oflog/include/dcmtk/oflog/helpers/threadcf.h \
 ../../oflog/include/dcmtk/oflog/loglevel.h \
 ../../ofstd/include/dcmtk/ofstd/ofvector.h \
 ../../oflog/include/dcmtk/oflog/tstring.h \
 ../../oflog/include/dcmtk/oflog/tchar.h \
 ../../oflog/include/dcmtk/oflog/spi/apndatch.h \
 ../../oflog/include/dcmtk/oflog/appender.h \
 ../../ofstd/include/dcmtk/ofstd/ofmem.h \
 ../../ofstd/include/dcmtk/ofstd/ofutil.h \
 ../../ofstd/include/dcmtk/ofstd/variadic/tuplefwd.h \
 ../../oflog/include/dcmtk/oflog/layout.h \
 ../../oflog/include/dcmtk/oflog/streams.h \
 ../../oflog/include/dcmtk/oflog/helpers/pointer.h \
 ../../oflog/include/dcmtk/oflog/thread/syncprim.h \
 ../../oflog/include/dcmtk/oflog/spi/filter.h \
 ../../oflog/include/dcmtk/oflog/helpers/lockfile.h \
 ../../oflog/include/dcmtk/oflog/spi/logfact.h \
 ../../oflog/include/dcmtk/oflog/logmacro.h \
 ../../oflog/include/dcmtk/oflog/helpers/snprintf.h \
 ../../oflog/include/dcmtk/oflog/tracelog.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdeftag.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctagkey.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdatset.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcitem.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctypes.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcobject.h \
 ../../ofstd/include/dcmtk/ofstd/ofglobal.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcerror.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcxfer.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvr.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctag.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcstack.h \
 ../../dcmdata/include/dcmtk/dcmdata/dclist.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcpcache.h \
 ../include/dcmtk/dcmsr/dsrdoc.h ../include/dcmtk/dcmsr/dsrdoctr.h \
 ../include/dcmtk/dcmsr/dsrdocst.h ../include/dcmtk/dcmsr/dsrtree.h \
 ../include/dcmtk/dcmsr/dsrtypes.h ../include/dcmtk/dcmsr/dsdefine.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcelem.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcsequen.h \
 ../include/dcmtk/dcmsr/dsrtncsr.h ../include/dcmtk/dcmsr/dsrposcn.h \
 ../include/dcmtk/dcmsr/dsrtnant.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../include/dcmtk/dcmsr/dsrdoctn.h ../include/dcmtk/dcmsr/dsrcodvl.h \
 ../include/dcmtk/dcmsr/dsrdncsr.h ../include/dcmtk/dcmsr/dsrdnflt.h \
 ../../ofstd/include/dcmtk/ofstd/ofdatime.h \
 ../../ofstd/include/dcmtk/ofstd/ofdate.h \
 ../../ofstd/include/dcmtk/ofstd/oftime.h \
 ../include/dcmtk/dcmsr/dsritcsr.h ../include/dcmtk/dcmsr/dsrcitem.h \
 ../include/dcmtk/dcmsr/dsrnumvl.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrfd.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrsl.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrul.h \
 ../include/dcmtk/dcmsr/dsrscovl.h ../include/dcmtk/dcmsr/dsrscogr.h \
 ../include/dcmtk/dcmsr/dsrtlist.h ../include/dcmtk/dcmsr/dsrsc3vl.h \
 ../include/dcmtk/dcmsr/dsrsc3gr.h ../include/dcmtk/dcmsr/dsrtcovl.h \
 ../include/dcmtk/dcmsr/dsrtcodt.h ../include/dcmtk/dcmsr/dsrtcosp.h \
 ../include/dcmtk/dcmsr/dsrtcoto.h ../include/dcmtk/dcmsr/dsrcomvl.h \
 ../include/dcmtk/dcmsr/dsrimgvl.h ../include/dcmtk/dcmsr/dsrimgfr.h \
 ../include/dcmtk/dcmsr/dsrimgse.h ../include/dcmtk/dcmsr/dsrwavvl.h \
 ../include/dcmtk/dcmsr/dsrwavch.h ../include/dcmtk/dcmsr/dsrrtpl.h \
 ../include/dcmtk/dcmsr/dsrctpl.h ../include/dcmtk/dcmsr/dsrsoprf.h \
 ../include/dcmtk/dcmsr/dsrrefin.h ../include/dcmtk/dcmsr/dsrcsidl.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrcs.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcbytstr.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrda.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvris.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrlo.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcchrstr.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrpn.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrsh.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrtm.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrui.h \
 ../include/dcmtk/dcmsr/dsrnumtn.h ../include/dcmtk/dcmsr/codes/dcm.h \
 ../include/dcmtk/dcmsr/codes/sct.h ../include/dcmtk/dcmsr/codes/ucum.h \
 ../include/dcmtk/dcmsr/cmr/init.h ../include/dcmtk/dcmsr/cmr/define.h \
 ../include/dcmtk/dcmsr/cmr/logger.h ../include/dcmtk/dcmsr/cmr/cid29e.h \
 ../include/dcmtk/dcmsr/cmr/cid29.h ../include/dcmtk/dcmsr/dsrctxgr.h \
 ../../ofstd/include/dcmtk/ofstd/ofmap.h \
 ../include/dcmtk/dcmsr/cmr/cid42.h ../include/dcmtk/dcmsr/cmr/cid244e.h \
 ../include/dcmtk/dcmsr/cmr/cid244.h ../include/dcmtk/dcmsr/cmr/cid4020.h \
 ../include/dcmtk/dcmsr/cmr/cid4031e.h \
 ../include/dcmtk/dcmsr/cmr/cid4031.h \
 ../include/dcmtk/dcmsr/cmr/cid7181.h \
 ../include/dcmtk/dcmsr/cmr/cid7445.h \
 ../include/dcmtk/dcmsr/cmr/cid10013e.h \
 ../include/dcmtk/dcmsr/cmr/cid10013.h \
 ../include/dcmtk/dcmsr/cmr/cid10033e.h \
 ../include/dcmtk/dcmsr/cmr/cid10033.h \
 ../include/dcmtk/dcmsr/cmr/tid1001.h ../include/dcmtk/dcmsr/dsrstpl.h \
 ../include/dcmtk/dcmsr/cmr/cid7452.h \
 ../include/dcmtk/dcmsr/cmr/cid7453.h \
 ../include/dcmtk/dcmsr/cmr/tid1204.h \
 ../include/dcmtk/dcmsr/cmr/cid5000.h \
 ../include/dcmtk/dcmsr/cmr/cid5001.h \
 ../include/dcmtk/dcmsr/cmr/tid1500.h \
 ../include/dcmtk/dcmsr/cmr/tid1411.h \
 ../include/dcmtk/dcmsr/cmr/srnumvlu.h \
 ../include/dcmtk/dcmsr/cmr/srnumvl.h \
 ../include/dcmtk/dcmsr/cmr/tid1419m.h \
 ../include/dcmtk/dcmsr/cmr/tid4019.h \
 ../include/dcmtk/dcmsr/cmr/cid6147.h \
 ../include/dcmtk/dcmsr/cmr/cid7464.h \
 ../include/dcmtk/dcmsr/cmr/cid7469.h \
 ../include/dcmtk/dcmsr/cmr/tid1501.h ../include/dcmtk/dcmsr/cmr/tid300.h \
 ../include/dcmtk/dcmsr/cmr/tid1600.h \
 ../include/dcmtk/dcmsr/cmr/cid4021.h ../include/dcmtk/dcmsr/cmr/cid100.h \
 ../include/dcmtk/dcmsr/cmr/cid7021.h
tsrcodvl.o: tsrcodvl.cc ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/oftest.h \
 ../../ofstd/include/dcmtk/ofstd/ofconapp.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../../ofstd/include/dcmtk/ofstd/ofcmdln.h \
 ../../ofstd/include/dcmtk/ofstd/ofexbl.h \
 ../../ofstd/include/dcmtk/ofstd/oftraits.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofconsol.h \
 ../../ofstd/include/dcmtk/ofstd/ofthread.h \
 ../../ofstd/include/dcmtk/ofstd/offile.h \
 ../../ofstd/include/dcmtk/ofstd/ofstd.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/oflimits.h \
 ../../config/include/dcmtk/config/arith.h \
 ../../ofstd/include/dcmtk/ofstd/oferror.h \
 ../../ofstd/include/dcmtk/ofstd/ofexit.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcuid.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdefine.h \
 ../../oflog/include/dcmtk/oflog/oflog.h \
 ../../oflog/include/dcmtk/oflog/logger.h \
 ../../oflog/include/dcmtk/oflog/config.h \
 ../../oflog/include/dcmtk/oflog/config/defines.h \
 ../../oflog/include/dcmtk/oflog/helpers/threadcf.h \
 ../../oflog/include/dcmtk/oflog/loglevel.h \
 ../../ofstd/include/dcmtk/ofstd/ofvector.h \
 ../../oflog/include/dcmtk/oflog/tstring.h \
 ../../oflog/include/dcmtk/oflog/tchar.h \
 ../../oflog/include/dcmtk/oflog/spi/apndatch.h \
 ../../oflog/include/dcmtk/oflog/appender.h \
 ../../ofstd/include/dcmtk/ofstd/ofmem.h \
 ../../ofstd/include/dcmtk/ofstd/ofutil.h \
 ../../ofstd/include/dcmtk/ofstd/variadic/tuplefwd.h \
 ../../oflog/include/dcmtk/oflog/layout.h \
 ../../oflog/include/dcmtk/oflog/streams.h \
 ../../oflog/include/dcmtk/oflog/helpers/pointer.h \
 ../../oflog/include/dcmtk/oflog/thread/syncprim.h \
 ../../oflog/include/dcmtk/oflog/spi/filter.h \
 ../../oflog/include/dcmtk/oflog/helpers/lockfile.h \
 ../../oflog/include/dcmtk/oflog/spi/logfact.h \
 ../../oflog/include/dcmtk/oflog/logmacro.h \
 ../../oflog/include/dcmtk/oflog/helpers/snprintf.h \
 ../../oflog/include/dcmtk/oflog/tracelog.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdeftag.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctagkey.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdatset.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcitem.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctypes.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcobject.h \
 ../../ofstd/include/dcmtk/ofstd/ofglobal.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcerror.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcxfer.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvr.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctag.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcstack.h \
 ../../dcmdata/include/dcmtk/dcmdata/dclist.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcpcache.h \
 ../include/dcmtk/dcmsr/dsrcodvl.h ../include/dcmtk/dcmsr/dsrtypes.h \
 ../include/dcmtk/dcmsr/dsdefine.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcelem.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcsequen.h
tsrdoc.o: tsrdoc.cc ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/oftest.h \
 ../../ofstd/include/dcmtk/ofstd/ofconapp.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../../ofstd/include/dcmtk/ofstd/ofcmdln.h \
 ../../ofstd/include/dcmtk/ofstd/ofexbl.h \
 ../../ofstd/include/dcmtk/ofstd/oftraits.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofconsol.h \
 ../../ofstd/include/dcmtk/ofstd/ofthread.h \
 ../../ofstd/include/dcmtk/ofstd/offile.h \
 ../../ofstd/include/dcmtk/ofstd/ofstd.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/oflimits.h \
 ../../config/include/dcmtk/config/arith.h \
 ../../ofstd/include/dcmtk/ofstd/oferror.h \
 ../../ofstd/include/dcmtk/ofstd/ofexit.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcuid.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdefine.h \
 ../../oflog/include/dcmtk/oflog/oflog.h \
 ../../oflog/include/dcmtk/oflog/logger.h \
 ../../oflog/include/dcmtk/oflog/config.h \
 ../../oflog/include/dcmtk/oflog/config/defines.h \
 ../../oflog/include/dcmtk/oflog/helpers/threadcf.h \
 ../../oflog/include/dcmtk/oflog/loglevel.h \
 ../../ofstd/include/dcmtk/ofstd/ofvector.h \
 ../../oflog/include/dcmtk/oflog/tstring.h \
 ../../oflog/include/dcmtk/oflog/tchar.h \
 ../../oflog/include/dcmtk/oflog/spi/apndatch.h \
 ../../oflog/include/dcmtk/oflog/appender.h \
 ../../ofstd/include/dcmtk/ofstd/ofmem.h \
 ../../ofstd/include/dcmtk/ofstd/ofutil.h \
 ../../ofstd/include/dcmtk/ofstd/variadic/tuplefwd.h \
 ../../oflog/include/dcmtk/oflog/layout.h \
 ../../oflog/include/dcmtk/oflog/streams.h \
 ../../oflog/include/dcmtk/oflog/helpers/pointer.h \
 ../../oflog/include/dcmtk/oflog/thread/syncprim.h \
 ../../oflog/include/dcmtk/oflog/spi/filter.h \
 ../../oflog/include/dcmtk/oflog/helpers/lockfile.h \
 ../../oflog/include/dcmtk/oflog/spi/logfact.h \
 ../../oflog/include/dcmtk/oflog/logmacro.h \
 ../../oflog/include/dcmtk/oflog/helpers/snprintf.h \
 ../../oflog/include/dcmtk/oflog/tracelog.h \
 ../include/dcmtk/dcmsr/dsrdoc.h ../include/dcmtk/dcmsr/dsrdoctr.h \
 ../include/dcmtk/dcmsr/dsrdocst.h ../include/dcmtk/dcmsr/dsrtree.h \
 ../include/dcmtk/dcmsr/dsrtypes.h ../include/dcmtk/dcmsr/dsdefine.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcelem.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcobject.h \
 ../../ofstd/include/dcmtk/ofstd/ofglobal.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcerror.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcxfer.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctypes.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvr.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctag.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctagkey.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcstack.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcitem.h \
 ../../dcmdata/include/dcmtk/dcmdata/dclist.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcpcache.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcsequen.h \
 ../include/dcmtk/dcmsr/dsrtncsr.h ../include/dcmtk/dcmsr/dsrposcn.h \
 ../include/dcmtk/dcmsr/dsrtnant.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../include/dcmtk/dcmsr/dsrdoctn.h ../include/dcmtk/dcmsr/dsrcodvl.h \
 ../include/dcmtk/dcmsr/dsrdncsr.h ../include/dcmtk/dcmsr/dsrdnflt.h \
 ../../ofstd/include/dcmtk/ofstd/ofdatime.h \
 ../../ofstd/include/dcmtk/ofstd/ofdate.h \
 ../../ofstd/include/dcmtk/ofstd/oftime.h \
 ../include/dcmtk/dcmsr/dsritcsr.h ../include/dcmtk/dcmsr/dsrcitem.h \
 ../include/dcmtk/dcmsr/dsrnumvl.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrfd.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrsl.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrul.h \
 ../include/dcmtk/dcmsr/dsrscovl.h ../include/dcmtk/dcmsr/dsrscogr.h \
 ../include/dcmtk/dcmsr/dsrtlist.h ../include/dcmtk/dcmsr/dsrsc3vl.h \
 ../include/dcmtk/dcmsr/dsrsc3gr.h ../include/dcmtk/dcmsr/dsrtcovl.h \
 ../include/dcmtk/dcmsr/dsrtcodt.h ../include/dcmtk/dcmsr/dsrtcosp.h \
 ../include/dcmtk/dcmsr/dsrtcoto.h ../include/dcmtk/dcmsr/dsrcomvl.h \
 ../include/dcmtk/dcmsr/dsrimgvl.h ../include/dcmtk/dcmsr/dsrimgfr.h \
 ../include/dcmtk/dcmsr/dsrimgse.h ../include/dcmtk/dcmsr/dsrwavvl.h \
 ../include/dcmtk/dcmsr/dsrwavch.h ../include/dcmtk/dcmsr/dsrrtpl.h \
 ../include/dcmtk/dcmsr/dsrctpl.h ../include/dcmtk/dcmsr/dsrsoprf.h \
 ../include/dcmtk/dcmsr/dsrrefin.h ../include/dcmtk/dcmsr/dsrcsidl.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrcs.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcbytstr.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrda.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvris.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrlo.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcchrstr.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrpn.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrsh.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrtm.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrui.h
tsrdoctr.o: tsrdoctr.cc ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/oftest.h \
 ../../ofstd/include/dcmtk/ofstd/ofconapp.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../../ofstd/include/dcmtk/ofstd/ofcmdln.h \
 ../../ofstd/include/dcmtk/ofstd/ofexbl.h \
 ../../ofstd/include/dcmtk/ofstd/oftraits.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofconsol.h \
 ../../ofstd/include/dcmtk/ofstd/ofthread.h \
 ../../ofstd/include/dcmtk/ofstd/offile.h \
 ../../ofstd/include/dcmtk/ofstd/ofstd.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/oflimits.h \
 ../../config/include/dcmtk/config/arith.h \
 ../../ofstd/include/dcmtk/ofstd/oferror.h \
 ../../ofstd/include/dcmtk/ofstd/ofexit.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcuid.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdefine.h \
 ../../oflog/include/dcmtk/oflog/oflog.h \
 ../../oflog/include/dcmtk/oflog/logger.h \
 ../../oflog/include/dcmtk/oflog/config.h \
 ../../oflog/include/dcmtk/oflog/config/defines.h \
 ../../oflog/include/dcmtk/oflog/helpers/threadcf.h \
 ../../oflog/include/dcmtk/oflog/loglevel.h \
 ../../ofstd/include/dcmtk/ofstd/ofvector.h \
 ../../oflog/include/dcmtk/oflog/tstring.h \
 ../../oflog/include/dcmtk/oflog/tchar.h \
 ../../oflog/include/dcmtk/oflog/spi/apndatch.h \
 ../../oflog/include/dcmtk/oflog/appender.h \
 ../../ofstd/include/dcmtk/ofstd/ofmem.h \
 ../../ofstd/include/dcmtk/ofstd/ofutil.h \
 ../../ofstd/include/dcmtk/ofstd/variadic/tuplefwd.h \
 ../../oflog/include/dcmtk/oflog/layout.h \
 ../../oflog/include/dcmtk/oflog/streams.h \
 ../../oflog/include/dcmtk/oflog/helpers/pointer.h \
 ../../oflog/include/dcmtk/oflog/thread/syncprim.h \
 ../../oflog/include/dcmtk/oflog/spi/filter.h \
 ../../oflog/include/dcmtk/oflog/helpers/lockfile.h \
 ../../oflog/include/dcmtk/oflog/spi/logfact.h \
 ../../oflog/include/dcmtk/oflog/logmacro.h \
 ../../oflog/include/dcmtk/oflog/helpers/snprintf.h \
 ../../oflog/include/dcmtk/oflog/tracelog.h \
 ../include/dcmtk/dcmsr/dsrdoc.h ../include/dcmtk/dcmsr/dsrdoctr.h \
 ../include/dcmtk/dcmsr/dsrdocst.h ../include/dcmtk/dcmsr/dsrtree.h \
 ../include/dcmtk/dcmsr/dsrtypes.h ../include/dcmtk/dcmsr/dsdefine.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcelem.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcobject.h \
 ../../ofstd/include/dcmtk/ofstd/ofglobal.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcerror.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcxfer.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctypes.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvr.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctag.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctagkey.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcstack.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcitem.h \
 ../../dcmdata/include/dcmtk/dcmdata/dclist.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcpcache.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcsequen.h \
 ../include/dcmtk/dcmsr/dsrtncsr.h ../include/dcmtk/dcmsr/dsrposcn.h \
 ../include/dcmtk/dcmsr/dsrtnant.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../include/dcmtk/dcmsr/dsrdoctn.h ../include/dcmtk/dcmsr/dsrcodvl.h \
 ../include/dcmtk/dcmsr/dsrdncsr.h ../include/dcmtk/dcmsr/dsrdnflt.h \
 ../../ofstd/include/dcmtk/ofstd/ofdatime.h \
 ../../ofstd/include/dcmtk/ofstd/ofdate.h \
 ../../ofstd/include/dcmtk/ofstd/oftime.h \
 ../include/dcmtk/dcmsr/dsritcsr.h ../include/dcmtk/dcmsr/dsrcitem.h \
 ../include/dcmtk/dcmsr/dsrnumvl.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrfd.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrsl.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrul.h \
 ../include/dcmtk/dcmsr/dsrscovl.h ../include/dcmtk/dcmsr/dsrscogr.h \
 ../include/dcmtk/dcmsr/dsrtlist.h ../include/dcmtk/dcmsr/dsrsc3vl.h \
 ../include/dcmtk/dcmsr/dsrsc3gr.h ../include/dcmtk/dcmsr/dsrtcovl.h \
 ../include/dcmtk/dcmsr/dsrtcodt.h ../include/dcmtk/dcmsr/dsrtcosp.h \
 ../include/dcmtk/dcmsr/dsrtcoto.h ../include/dcmtk/dcmsr/dsrcomvl.h \
 ../include/dcmtk/dcmsr/dsrimgvl.h ../include/dcmtk/dcmsr/dsrimgfr.h \
 ../include/dcmtk/dcmsr/dsrimgse.h ../include/dcmtk/dcmsr/dsrwavvl.h \
 ../include/dcmtk/dcmsr/dsrwavch.h ../include/dcmtk/dcmsr/dsrrtpl.h \
 ../include/dcmtk/dcmsr/dsrctpl.h ../include/dcmtk/dcmsr/dsrsoprf.h \
 ../include/dcmtk/dcmsr/dsrrefin.h ../include/dcmtk/dcmsr/dsrcsidl.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrcs.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcbytstr.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrda.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvris.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrlo.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcchrstr.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrpn.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrsh.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrtm.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrui.h \
 ../include/dcmtk/dcmsr/dsrtpltn.h ../include/dcmtk/dcmsr/dsrstpl.h \
 ../include/dcmtk/dcmsr/dsrreftn.h ../include/dcmtk/dcmsr/dsrimgtn.h \
 ../include/dcmtk/dcmsr/dsrnumtn.h ../include/dcmtk/dcmsr/dsrtextn.h \
 ../include/dcmtk/dcmsr/dsrstrvl.h
tsrlist.o: tsrlist.cc ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/oftest.h \
 ../../ofstd/include/dcmtk/ofstd/ofconapp.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../../ofstd/include/dcmtk/ofstd/ofcmdln.h \
 ../../ofstd/include/dcmtk/ofstd/ofexbl.h \
 ../../ofstd/include/dcmtk/ofstd/oftraits.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofconsol.h \
 ../../ofstd/include/dcmtk/ofstd/ofthread.h \
 ../../ofstd/include/dcmtk/ofstd/offile.h \
 ../../ofstd/include/dcmtk/ofstd/ofstd.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/oflimits.h \
 ../../config/include/dcmtk/config/arith.h \
 ../../ofstd/include/dcmtk/ofstd/oferror.h \
 ../../ofstd/include/dcmtk/ofstd/ofexit.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcuid.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdefine.h \
 ../../oflog/include/dcmtk/oflog/oflog.h \
 ../../oflog/include/dcmtk/oflog/logger.h \
 ../../oflog/include/dcmtk/oflog/config.h \
 ../../oflog/include/dcmtk/oflog/config/defines.h \
 ../../oflog/include/dcmtk/oflog/helpers/threadcf.h \
 ../../oflog/include/dcmtk/oflog/loglevel.h \
 ../../ofstd/include/dcmtk/ofstd/ofvector.h \
 ../../oflog/include/dcmtk/oflog/tstring.h \
 ../../oflog/include/dcmtk/oflog/tchar.h \
 ../../oflog/include/dcmtk/oflog/spi/apndatch.h \
 ../../oflog/include/dcmtk/oflog/appender.h \
 ../../ofstd/include/dcmtk/ofstd/ofmem.h \
 ../../ofstd/include/dcmtk/ofstd/ofutil.h \
 ../../ofstd/include/dcmtk/ofstd/variadic/tuplefwd.h \
 ../../oflog/include/dcmtk/oflog/layout.h \
 ../../oflog/include/dcmtk/oflog/streams.h \
 ../../oflog/include/dcmtk/oflog/helpers/pointer.h \
 ../../oflog/include/dcmtk/oflog/thread/syncprim.h \
 ../../oflog/include/dcmtk/oflog/spi/filter.h \
 ../../oflog/include/dcmtk/oflog/helpers/lockfile.h \
 ../../oflog/include/dcmtk/oflog/spi/logfact.h \
 ../../oflog/include/dcmtk/oflog/logmacro.h \
 ../../oflog/include/dcmtk/oflog/helpers/snprintf.h \
 ../../oflog/include/dcmtk/oflog/tracelog.h \
 ../../ofstd/include/dcmtk/ofstd/ofdiag.h \
 ../include/dcmtk/dcmsr/dsrtlist.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcerror.h \
 ../../ofstd/include/dcmtk/ofstd/diag/push.def \
 ../../ofstd/include/dcmtk/ofstd/diag/shadow.def \
 ../../ofstd/include/dcmtk/ofstd/diag/pop.def
tsrnumvl.o: tsrnumvl.cc ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/oftest.h \
 ../../ofstd/include/dcmtk/ofstd/ofconapp.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../../ofstd/include/dcmtk/ofstd/ofcmdln.h \
 ../../ofstd/include/dcmtk/ofstd/ofexbl.h \
 ../../ofstd/include/dcmtk/ofstd/oftraits.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofconsol.h \
 ../../ofstd/include/dcmtk/ofstd/ofthread.h \
 ../../ofstd/include/dcmtk/ofstd/offile.h \
 ../../ofstd/include/dcmtk/ofstd/ofstd.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/oflimits.h \
 ../../config/include/dcmtk/config/arith.h \
 ../../ofstd/include/dcmtk/ofstd/oferror.h \
 ../../ofstd/include/dcmtk/ofstd/ofexit.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcuid.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdefine.h \
 ../../oflog/include/dcmtk/oflog/oflog.h \
 ../../oflog/include/dcmtk/oflog/logger.h \
 ../../oflog/include/dcmtk/oflog/config.h \
 ../../oflog/include/dcmtk/oflog/config/defines.h \
 ../../oflog/include/dcmtk/oflog/helpers/threadcf.h \
 ../../oflog/include/dcmtk/oflog/loglevel.h \
 ../../ofstd/include/dcmtk/ofstd/ofvector.h \
 ../../oflog/include/dcmtk/oflog/tstring.h \
 ../../oflog/include/dcmtk/oflog/tchar.h \
 ../../oflog/include/dcmtk/oflog/spi/apndatch.h \
 ../../oflog/include/dcmtk/oflog/appender.h \
 ../../ofstd/include/dcmtk/ofstd/ofmem.h \
 ../../ofstd/include/dcmtk/ofstd/ofutil.h \
 ../../ofstd/include/dcmtk/ofstd/variadic/tuplefwd.h \
 ../../oflog/include/dcmtk/oflog/layout.h \
 ../../oflog/include/dcmtk/oflog/streams.h \
 ../../oflog/include/dcmtk/oflog/helpers/pointer.h \
 ../../oflog/include/dcmtk/oflog/thread/syncprim.h \
 ../../oflog/include/dcmtk/oflog/spi/filter.h \
 ../../oflog/include/dcmtk/oflog/helpers/lockfile.h \
 ../../oflog/include/dcmtk/oflog/spi/logfact.h \
 ../../oflog/include/dcmtk/oflog/logmacro.h \
 ../../oflog/include/dcmtk/oflog/helpers/snprintf.h \
 ../../oflog/include/dcmtk/oflog/tracelog.h \
 ../include/dcmtk/dcmsr/dsrnumvl.h ../include/dcmtk/dcmsr/dsrcodvl.h \
 ../include/dcmtk/dcmsr/dsrtypes.h ../include/dcmtk/dcmsr/dsdefine.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcelem.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcobject.h \
 ../../ofstd/include/dcmtk/ofstd/ofglobal.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcerror.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcxfer.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctypes.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvr.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctag.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctagkey.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcstack.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcitem.h \
 ../../dcmdata/include/dcmtk/dcmdata/dclist.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcpcache.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcsequen.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrfd.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrsl.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrul.h \
 ../include/dcmtk/dcmsr/codes/dcm.h
tsrtpl.o: tsrtpl.cc ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/oftest.h \
 ../../ofstd/include/dcmtk/ofstd/ofconapp.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../../ofstd/include/dcmtk/ofstd/ofcmdln.h \
 ../../ofstd/include/dcmtk/ofstd/ofexbl.h \
 ../../ofstd/include/dcmtk/ofstd/oftraits.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofconsol.h \
 ../../ofstd/include/dcmtk/ofstd/ofthread.h \
 ../../ofstd/include/dcmtk/ofstd/offile.h \
 ../../ofstd/include/dcmtk/ofstd/ofstd.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/oflimits.h \
 ../../config/include/dcmtk/config/arith.h \
 ../../ofstd/include/dcmtk/ofstd/oferror.h \
 ../../ofstd/include/dcmtk/ofstd/ofexit.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcuid.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdefine.h \
 ../../oflog/include/dcmtk/oflog/oflog.h \
 ../../oflog/include/dcmtk/oflog/logger.h \
 ../../oflog/include/dcmtk/oflog/config.h \
 ../../oflog/include/dcmtk/oflog/config/defines.h \
 ../../oflog/include/dcmtk/oflog/helpers/threadcf.h \
 ../../oflog/include/dcmtk/oflog/loglevel.h \
 ../../ofstd/include/dcmtk/ofstd/ofvector.h \
 ../../oflog/include/dcmtk/oflog/tstring.h \
 ../../oflog/include/dcmtk/oflog/tchar.h \
 ../../oflog/include/dcmtk/oflog/spi/apndatch.h \
 ../../oflog/include/dcmtk/oflog/appender.h \
 ../../ofstd/include/dcmtk/ofstd/ofmem.h \
 ../../ofstd/include/dcmtk/ofstd/ofutil.h \
 ../../ofstd/include/dcmtk/ofstd/variadic/tuplefwd.h \
 ../../oflog/include/dcmtk/oflog/layout.h \
 ../../oflog/include/dcmtk/oflog/streams.h \
 ../../oflog/include/dcmtk/oflog/helpers/pointer.h \
 ../../oflog/include/dcmtk/oflog/thread/syncprim.h \
 ../../oflog/include/dcmtk/oflog/spi/filter.h \
 ../../oflog/include/dcmtk/oflog/helpers/lockfile.h \
 ../../oflog/include/dcmtk/oflog/spi/logfact.h \
 ../../oflog/include/dcmtk/oflog/logmacro.h \
 ../../oflog/include/dcmtk/oflog/helpers/snprintf.h \
 ../../oflog/include/dcmtk/oflog/tracelog.h \
 ../include/dcmtk/dcmsr/dsrdoc.h ../include/dcmtk/dcmsr/dsrdoctr.h \
 ../include/dcmtk/dcmsr/dsrdocst.h ../include/dcmtk/dcmsr/dsrtree.h \
 ../include/dcmtk/dcmsr/dsrtypes.h ../include/dcmtk/dcmsr/dsdefine.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcelem.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcobject.h \
 ../../ofstd/include/dcmtk/ofstd/ofglobal.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcerror.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcxfer.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctypes.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvr.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctag.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctagkey.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcstack.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcitem.h \
 ../../dcmdata/include/dcmtk/dcmdata/dclist.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcpcache.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcsequen.h \
 ../include/dcmtk/dcmsr/dsrtncsr.h ../include/dcmtk/dcmsr/dsrposcn.h \
 ../include/dcmtk/dcmsr/dsrtnant.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../include/dcmtk/dcmsr/dsrdoctn.h ../include/dcmtk/dcmsr/dsrcodvl.h \
 ../include/dcmtk/dcmsr/dsrdncsr.h ../include/dcmtk/dcmsr/dsrdnflt.h \
 ../../ofstd/include/dcmtk/ofstd/ofdatime.h \
 ../../ofstd/include/dcmtk/ofstd/ofdate.h \
 ../../ofstd/include/dcmtk/ofstd/oftime.h \
 ../include/dcmtk/dcmsr/dsritcsr.h ../include/dcmtk/dcmsr/dsrcitem.h \
 ../include/dcmtk/dcmsr/dsrnumvl.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrfd.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrsl.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrul.h \
 ../include/dcmtk/dcmsr/dsrscovl.h ../include/dcmtk/dcmsr/dsrscogr.h \
 ../include/dcmtk/dcmsr/dsrtlist.h ../include/dcmtk/dcmsr/dsrsc3vl.h \
 ../include/dcmtk/dcmsr/dsrsc3gr.h ../include/dcmtk/dcmsr/dsrtcovl.h \
 ../include/dcmtk/dcmsr/dsrtcodt.h ../include/dcmtk/dcmsr/dsrtcosp.h \
 ../include/dcmtk/dcmsr/dsrtcoto.h ../include/dcmtk/dcmsr/dsrcomvl.h \
 ../include/dcmtk/dcmsr/dsrimgvl.h ../include/dcmtk/dcmsr/dsrimgfr.h \
 ../include/dcmtk/dcmsr/dsrimgse.h ../include/dcmtk/dcmsr/dsrwavvl.h \
 ../include/dcmtk/dcmsr/dsrwavch.h ../include/dcmtk/dcmsr/dsrrtpl.h \
 ../include/dcmtk/dcmsr/dsrctpl.h ../include/dcmtk/dcmsr/dsrsoprf.h \
 ../include/dcmtk/dcmsr/dsrrefin.h ../include/dcmtk/dcmsr/dsrcsidl.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrcs.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcbytstr.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrda.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvris.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrlo.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcchrstr.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrpn.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrsh.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrtm.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrui.h \
 ../include/dcmtk/dcmsr/dsrstpl.h ../include/dcmtk/dcmsr/dsrreftn.h
tsrtree.o: tsrtree.cc ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/oftest.h \
 ../../ofstd/include/dcmtk/ofstd/ofconapp.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../../ofstd/include/dcmtk/ofstd/ofcmdln.h \
 ../../ofstd/include/dcmtk/ofstd/ofexbl.h \
 ../../ofstd/include/dcmtk/ofstd/oftraits.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofconsol.h \
 ../../ofstd/include/dcmtk/ofstd/ofthread.h \
 ../../ofstd/include/dcmtk/ofstd/offile.h \
 ../../ofstd/include/dcmtk/ofstd/ofstd.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/oflimits.h \
 ../../config/include/dcmtk/config/arith.h \
 ../../ofstd/include/dcmtk/ofstd/oferror.h \
 ../../ofstd/include/dcmtk/ofstd/ofexit.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcuid.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdefine.h \
 ../../oflog/include/dcmtk/oflog/oflog.h \
 ../../oflog/include/dcmtk/oflog/logger.h \
 ../../oflog/include/dcmtk/oflog/config.h \
 ../../oflog/include/dcmtk/oflog/config/defines.h \
 ../../oflog/include/dcmtk/oflog/helpers/threadcf.h \
 ../../oflog/include/dcmtk/oflog/loglevel.h \
 ../../ofstd/include/dcmtk/ofstd/ofvector.h \
 ../../oflog/include/dcmtk/oflog/tstring.h \
 ../../oflog/include/dcmtk/oflog/tchar.h \
 ../../oflog/include/dcmtk/oflog/spi/apndatch.h \
 ../../oflog/include/dcmtk/oflog/appender.h \
 ../../ofstd/include/dcmtk/ofstd/ofmem.h \
 ../../ofstd/include/dcmtk/ofstd/ofutil.h \
 ../../ofstd/include/dcmtk/ofstd/variadic/tuplefwd.h \
 ../../oflog/include/dcmtk/oflog/layout.h \
 ../../oflog/include/dcmtk/oflog/streams.h \
 ../../oflog/include/dcmtk/oflog/helpers/pointer.h \
 ../../oflog/include/dcmtk/oflog/thread/syncprim.h \
 ../../oflog/include/dcmtk/oflog/spi/filter.h \
 ../../oflog/include/dcmtk/oflog/helpers/lockfile.h \
 ../../oflog/include/dcmtk/oflog/spi/logfact.h \
 ../../oflog/include/dcmtk/oflog/logmacro.h \
 ../../oflog/include/dcmtk/oflog/helpers/snprintf.h \
 ../../oflog/include/dcmtk/oflog/tracelog.h \
 ../include/dcmtk/dcmsr/dsrtree.h ../include/dcmtk/dcmsr/dsrtypes.h \
 ../include/dcmtk/dcmsr/dsdefine.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcelem.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcobject.h \
 ../../ofstd/include/dcmtk/ofstd/ofglobal.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcerror.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcxfer.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctypes.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvr.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctag.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctagkey.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcstack.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcitem.h \
 ../../dcmdata/include/dcmtk/dcmdata/dclist.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcpcache.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcsequen.h \
 ../include/dcmtk/dcmsr/dsrtncsr.h ../include/dcmtk/dcmsr/dsrposcn.h \
 ../include/dcmtk/dcmsr/dsrtnant.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h
