dcmimage.o: dcmimage.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../dcmdata/include/dctypes.h \
  ../../ofstd/include/oftypes.h ../../ofstd/include/ofstdinc.h \
  ../../dcmdata/include/dcdeftag.h ../../dcmdata/include/dctagkey.h \
  ../../ofstd/include/ofstream.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../../dcmdata/include/dcobject.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/ofglobal.h ../../dcmdata/include/dcerror.h \
  ../../ofstd/include/ofcond.h ../../dcmdata/include/dcxfer.h \
  ../../dcmdata/include/dcvr.h ../../dcmdata/include/dctag.h \
  ../../dcmdata/include/dclist.h ../../dcmdata/include/dcstack.h \
  ../../dcmdata/include/dcuid.h ../../dcmdata/include/dcdict.h \
  ../../dcmdata/include/dchashdi.h ../../ofstd/include/oflist.h \
  ../include/dcmimage.h ../include/dimoimg.h ../include/diimage.h \
  ../../dcmdata/include/dcitem.h ../../dcmdata/include/dcvrui.h \
  ../../dcmdata/include/dcbytstr.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcpcache.h ../include/diovlay.h \
  ../include/diobjcou.h ../include/diovdat.h ../include/diovpln.h \
  ../include/diutils.h ../include/dimopx.h ../include/dipixel.h \
  ../include/dimomod.h ../include/diluptab.h ../include/dibaslut.h \
  ../include/dimoopx.h ../include/didispfn.h ../include/didislut.h \
  ../include/diovlimg.h ../include/dimo2img.h ../include/dimo1img.h \
  ../include/didocu.h ../../dcmdata/include/dcfilefo.h \
  ../../dcmdata/include/dcsequen.h ../../dcmdata/include/dcdatset.h \
  ../include/diregbas.h ../include/diplugin.h \
  ../../dcmdata/include/dcdicent.h
dibaslut.o: dibaslut.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/dibaslut.h \
  ../../ofstd/include/ofstring.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/ofcast.h ../../ofstd/include/ofstdinc.h \
  ../../ofstd/include/ofstream.h ../include/diutils.h \
  ../../dcmdata/include/dctypes.h ../../ofstd/include/ofglobal.h \
  ../../ofstd/include/ofthread.h
diciefn.o: diciefn.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofconsol.h \
  ../../ofstd/include/ofstream.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/oftypes.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../../ofstd/include/ofstdinc.h \
  ../include/diciefn.h ../include/didispfn.h ../include/didislut.h \
  ../include/dibaslut.h ../include/diutils.h \
  ../../dcmdata/include/dctypes.h ../../ofstd/include/ofglobal.h \
  ../include/dicielut.h
dicielut.o: dicielut.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofconsol.h \
  ../../ofstd/include/ofstream.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/oftypes.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../../ofstd/include/ofstdinc.h \
  ../include/dicielut.h ../include/didislut.h ../include/dibaslut.h \
  ../include/diutils.h ../../dcmdata/include/dctypes.h \
  ../../ofstd/include/ofglobal.h
didislut.o: didislut.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/didislut.h \
  ../include/dibaslut.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/oftypes.h ../../ofstd/include/ofcast.h \
  ../../ofstd/include/ofstdinc.h ../../ofstd/include/ofstream.h \
  ../include/diutils.h ../../dcmdata/include/dctypes.h \
  ../../ofstd/include/ofglobal.h ../../ofstd/include/ofthread.h
didispfn.o: didispfn.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofconsol.h \
  ../../ofstd/include/ofstream.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/oftypes.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../../ofstd/include/ofstdinc.h \
  ../../ofstd/include/ofbmanip.h ../include/didispfn.h \
  ../include/didislut.h ../include/dibaslut.h ../include/diutils.h \
  ../../dcmdata/include/dctypes.h ../../ofstd/include/ofglobal.h \
  ../include/displint.h ../include/dicrvfit.h
didocu.o: didocu.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../dcmdata/include/dctk.h \
  ../../dcmdata/include/dctypes.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/ofstdinc.h ../../dcmdata/include/dcswap.h \
  ../../dcmdata/include/dcerror.h ../../ofstd/include/ofcond.h \
  ../../ofstd/include/ofstring.h ../../ofstd/include/ofcast.h \
  ../../ofstd/include/ofstream.h ../../dcmdata/include/dcxfer.h \
  ../../dcmdata/include/dcvr.h ../../ofstd/include/ofglobal.h \
  ../../ofstd/include/ofthread.h ../../dcmdata/include/dcistrma.h \
  ../../dcmdata/include/dcostrma.h ../../dcmdata/include/dcuid.h \
  ../../dcmdata/include/dcvm.h ../../dcmdata/include/dcdefine.h \
  ../../dcmdata/include/dcdebug.h ../../dcmdata/include/dctagkey.h \
  ../../dcmdata/include/dctag.h ../../dcmdata/include/dcdicent.h \
  ../../dcmdata/include/dchashdi.h ../../ofstd/include/oflist.h \
  ../../dcmdata/include/dcdict.h ../../dcmdata/include/dcdeftag.h \
  ../../dcmdata/include/dcobject.h ../../ofstd/include/ofconsol.h \
  ../../dcmdata/include/dclist.h ../../dcmdata/include/dcstack.h \
  ../../dcmdata/include/dcelem.h ../../dcmdata/include/dcitem.h \
  ../../dcmdata/include/dcvrui.h ../../dcmdata/include/dcbytstr.h \
  ../../dcmdata/include/dcpcache.h ../../dcmdata/include/dcmetinf.h \
  ../../dcmdata/include/dcdatset.h ../../dcmdata/include/dcsequen.h \
  ../../dcmdata/include/dcfilefo.h ../../dcmdata/include/dcdicdir.h \
  ../../dcmdata/include/dcdirrec.h ../../dcmdata/include/dcvrulup.h \
  ../../dcmdata/include/dcvrul.h ../../dcmdata/include/dcpixseq.h \
  ../../dcmdata/include/dcofsetl.h ../../dcmdata/include/dcvrae.h \
  ../../dcmdata/include/dcvras.h ../../dcmdata/include/dcvrcs.h \
  ../../dcmdata/include/dcvrda.h ../../ofstd/include/ofdate.h \
  ../../dcmdata/include/dcvrds.h ../../dcmdata/include/dcvrdt.h \
  ../../ofstd/include/ofdatime.h ../../ofstd/include/oftime.h \
  ../../dcmdata/include/dcvris.h ../../dcmdata/include/dcvrtm.h \
  ../../dcmdata/include/dcchrstr.h ../../dcmdata/include/dcvrlo.h \
  ../../dcmdata/include/dcvrlt.h ../../dcmdata/include/dcvrpn.h \
  ../../dcmdata/include/dcvrsh.h ../../dcmdata/include/dcvrst.h \
  ../../dcmdata/include/dcvrut.h ../../dcmdata/include/dcvrobow.h \
  ../../dcmdata/include/dcpixel.h ../../dcmdata/include/dcvrpobw.h \
  ../../dcmdata/include/dcovlay.h ../../dcmdata/include/dcvrat.h \
  ../../dcmdata/include/dcvrss.h ../../dcmdata/include/dcvrus.h \
  ../../dcmdata/include/dcvrsl.h ../../dcmdata/include/dcvrfl.h \
  ../../dcmdata/include/dcvrfd.h ../../dcmdata/include/dcvrof.h \
  ../../dcmdata/include/cmdlnarg.h ../include/didocu.h \
  ../include/diobjcou.h ../include/diutils.h
digsdfn.o: digsdfn.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofconsol.h \
  ../../ofstd/include/ofstream.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/oftypes.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../../ofstd/include/ofstdinc.h \
  ../include/digsdfn.h ../include/didispfn.h ../include/didislut.h \
  ../include/dibaslut.h ../include/diutils.h \
  ../../dcmdata/include/dctypes.h ../../ofstd/include/ofglobal.h \
  ../include/digsdlut.h ../include/displint.h
digsdlut.o: digsdlut.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofconsol.h \
  ../../ofstd/include/ofstream.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/oftypes.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../../ofstd/include/ofstdinc.h \
  ../include/digsdlut.h ../include/didislut.h ../include/dibaslut.h \
  ../include/diutils.h ../../dcmdata/include/dctypes.h \
  ../../ofstd/include/ofglobal.h ../include/displint.h
diimage.o: diimage.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../dcmdata/include/dctypes.h \
  ../../ofstd/include/oftypes.h ../../ofstd/include/ofstdinc.h \
  ../../dcmdata/include/dcdeftag.h ../../dcmdata/include/dctagkey.h \
  ../../ofstd/include/ofstream.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../../dcmdata/include/dcswap.h \
  ../../dcmdata/include/dcerror.h ../../ofstd/include/ofcond.h \
  ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
  ../../ofstd/include/ofglobal.h ../../ofstd/include/ofthread.h \
  ../include/diimage.h ../../dcmdata/include/dcitem.h \
  ../../ofstd/include/ofconsol.h ../../dcmdata/include/dcobject.h \
  ../../dcmdata/include/dctag.h ../../dcmdata/include/dclist.h \
  ../../dcmdata/include/dcstack.h ../../dcmdata/include/dcvrui.h \
  ../../dcmdata/include/dcbytstr.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcpcache.h ../../ofstd/include/oflist.h \
  ../include/diovlay.h ../include/diobjcou.h ../include/diovdat.h \
  ../include/diovpln.h ../include/diutils.h ../include/diinpxt.h \
  ../../dcmdata/include/dcpixel.h ../../dcmdata/include/dcvrpobw.h \
  ../../dcmdata/include/dcvrobow.h ../../ofstd/include/ofbmanip.h \
  ../include/diinpx.h ../include/dipxrept.h ../include/didocu.h \
  ../../dcmdata/include/dcfilefo.h ../../dcmdata/include/dcsequen.h \
  ../../dcmdata/include/dcdatset.h ../../ofstd/include/ofstd.h
diinpx.o: diinpx.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/diinpx.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofstream.h \
  ../../ofstd/include/ofthread.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/ofstring.h ../../ofstd/include/ofcast.h \
  ../../ofstd/include/ofstdinc.h ../../dcmdata/include/dctypes.h \
  ../include/diutils.h ../../ofstd/include/ofglobal.h
diluptab.o: diluptab.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../dcmdata/include/dcdeftag.h \
  ../../dcmdata/include/dctagkey.h ../../ofstd/include/ofstream.h \
  ../../dcmdata/include/dctypes.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/ofstdinc.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../../dcmdata/include/dcsequen.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofthread.h \
  ../../dcmdata/include/dcerror.h ../../ofstd/include/ofcond.h \
  ../../dcmdata/include/dcobject.h ../../ofstd/include/ofglobal.h \
  ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
  ../../dcmdata/include/dctag.h ../../dcmdata/include/dclist.h \
  ../../dcmdata/include/dcstack.h ../../dcmdata/include/dcitem.h \
  ../../dcmdata/include/dcvrui.h ../../dcmdata/include/dcbytstr.h \
  ../../dcmdata/include/dcelem.h ../../dcmdata/include/dcpcache.h \
  ../../ofstd/include/oflist.h ../../ofstd/include/ofbmanip.h \
  ../include/diluptab.h ../include/dibaslut.h ../include/diutils.h \
  ../include/diobjcou.h ../include/didocu.h \
  ../../dcmdata/include/dcfilefo.h ../../dcmdata/include/dcdatset.h
dimo1img.o: dimo1img.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../dcmdata/include/dctypes.h \
  ../../ofstd/include/oftypes.h ../../ofstd/include/ofstdinc.h \
  ../include/dimo1img.h ../include/dimoimg.h ../../ofstd/include/ofcast.h \
  ../include/diimage.h ../../dcmdata/include/dcitem.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofstream.h \
  ../../ofstd/include/ofthread.h ../../ofstd/include/ofstring.h \
  ../../dcmdata/include/dcobject.h ../../ofstd/include/ofglobal.h \
  ../../dcmdata/include/dcerror.h ../../ofstd/include/ofcond.h \
  ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
  ../../dcmdata/include/dctag.h ../../dcmdata/include/dctagkey.h \
  ../../dcmdata/include/dclist.h ../../dcmdata/include/dcstack.h \
  ../../dcmdata/include/dcvrui.h ../../dcmdata/include/dcbytstr.h \
  ../../dcmdata/include/dcelem.h ../../dcmdata/include/dcpcache.h \
  ../../ofstd/include/oflist.h ../include/diovlay.h ../include/diobjcou.h \
  ../include/diovdat.h ../include/diovpln.h ../include/diutils.h \
  ../include/dimopx.h ../include/dipixel.h ../include/dimomod.h \
  ../include/diluptab.h ../include/dibaslut.h ../include/dimoopx.h \
  ../include/didispfn.h ../include/didislut.h
dimo2img.o: dimo2img.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../dcmdata/include/dctypes.h \
  ../../ofstd/include/oftypes.h ../../ofstd/include/ofstdinc.h \
  ../include/dimo2img.h ../include/dimoimg.h ../../ofstd/include/ofcast.h \
  ../include/diimage.h ../../dcmdata/include/dcitem.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofstream.h \
  ../../ofstd/include/ofthread.h ../../ofstd/include/ofstring.h \
  ../../dcmdata/include/dcobject.h ../../ofstd/include/ofglobal.h \
  ../../dcmdata/include/dcerror.h ../../ofstd/include/ofcond.h \
  ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
  ../../dcmdata/include/dctag.h ../../dcmdata/include/dctagkey.h \
  ../../dcmdata/include/dclist.h ../../dcmdata/include/dcstack.h \
  ../../dcmdata/include/dcvrui.h ../../dcmdata/include/dcbytstr.h \
  ../../dcmdata/include/dcelem.h ../../dcmdata/include/dcpcache.h \
  ../../ofstd/include/oflist.h ../include/diovlay.h ../include/diobjcou.h \
  ../include/diovdat.h ../include/diovpln.h ../include/diutils.h \
  ../include/dimopx.h ../include/dipixel.h ../include/dimomod.h \
  ../include/diluptab.h ../include/dibaslut.h ../include/dimoopx.h \
  ../include/didispfn.h ../include/didislut.h
dimoimg.o: dimoimg.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../dcmdata/include/dctypes.h \
  ../../ofstd/include/oftypes.h ../../ofstd/include/ofstdinc.h \
  ../../dcmdata/include/dcdeftag.h ../../dcmdata/include/dctagkey.h \
  ../../ofstd/include/ofstream.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../include/dimoimg.h ../include/diimage.h \
  ../../dcmdata/include/dcitem.h ../../ofstd/include/ofconsol.h \
  ../../ofstd/include/ofthread.h ../../dcmdata/include/dcobject.h \
  ../../ofstd/include/ofglobal.h ../../dcmdata/include/dcerror.h \
  ../../ofstd/include/ofcond.h ../../dcmdata/include/dcxfer.h \
  ../../dcmdata/include/dcvr.h ../../dcmdata/include/dctag.h \
  ../../dcmdata/include/dclist.h ../../dcmdata/include/dcstack.h \
  ../../dcmdata/include/dcvrui.h ../../dcmdata/include/dcbytstr.h \
  ../../dcmdata/include/dcelem.h ../../dcmdata/include/dcpcache.h \
  ../../ofstd/include/oflist.h ../include/diovlay.h ../include/diobjcou.h \
  ../include/diovdat.h ../include/diovpln.h ../include/diutils.h \
  ../include/dimopx.h ../include/dipixel.h ../include/dimomod.h \
  ../include/diluptab.h ../include/dibaslut.h ../include/dimoopx.h \
  ../include/didispfn.h ../include/didislut.h ../include/dimo2img.h \
  ../include/dimoipxt.h ../../ofstd/include/ofbmanip.h \
  ../include/dimopxt.h ../../dcmdata/include/dcdefine.h \
  ../include/dipxrept.h ../include/diinpx.h ../include/dimocpt.h \
  ../include/dimosct.h ../include/discalet.h ../include/ditranst.h \
  ../include/dimoflt.h ../include/diflipt.h ../include/dimorot.h \
  ../include/dirotat.h ../include/dimoopxt.h ../include/digsdfn.h \
  ../include/digsdlut.h ../include/didocu.h \
  ../../dcmdata/include/dcfilefo.h ../../dcmdata/include/dcsequen.h \
  ../../dcmdata/include/dcdatset.h ../include/diregbas.h
dimoimg3.o: dimoimg3.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/dimoimg.h \
  ../../dcmdata/include/dctypes.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/ofstdinc.h ../../ofstd/include/ofcast.h \
  ../include/diimage.h ../../dcmdata/include/dcitem.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofstream.h \
  ../../ofstd/include/ofthread.h ../../ofstd/include/ofstring.h \
  ../../dcmdata/include/dcobject.h ../../ofstd/include/ofglobal.h \
  ../../dcmdata/include/dcerror.h ../../ofstd/include/ofcond.h \
  ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
  ../../dcmdata/include/dctag.h ../../dcmdata/include/dctagkey.h \
  ../../dcmdata/include/dclist.h ../../dcmdata/include/dcstack.h \
  ../../dcmdata/include/dcvrui.h ../../dcmdata/include/dcbytstr.h \
  ../../dcmdata/include/dcelem.h ../../dcmdata/include/dcpcache.h \
  ../../ofstd/include/oflist.h ../include/diovlay.h ../include/diobjcou.h \
  ../include/diovdat.h ../include/diovpln.h ../include/diutils.h \
  ../include/dimopx.h ../include/dipixel.h ../include/dimomod.h \
  ../include/diluptab.h ../include/dibaslut.h ../include/dimoopx.h \
  ../include/didispfn.h ../include/didislut.h ../include/dimoipxt.h \
  ../../ofstd/include/ofbmanip.h ../include/dimopxt.h \
  ../../dcmdata/include/dcdefine.h ../include/dipxrept.h \
  ../include/diinpx.h ../include/dimoopxt.h
dimoimg4.o: dimoimg4.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/dimoimg.h \
  ../../dcmdata/include/dctypes.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/ofstdinc.h ../../ofstd/include/ofcast.h \
  ../include/diimage.h ../../dcmdata/include/dcitem.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofstream.h \
  ../../ofstd/include/ofthread.h ../../ofstd/include/ofstring.h \
  ../../dcmdata/include/dcobject.h ../../ofstd/include/ofglobal.h \
  ../../dcmdata/include/dcerror.h ../../ofstd/include/ofcond.h \
  ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
  ../../dcmdata/include/dctag.h ../../dcmdata/include/dctagkey.h \
  ../../dcmdata/include/dclist.h ../../dcmdata/include/dcstack.h \
  ../../dcmdata/include/dcvrui.h ../../dcmdata/include/dcbytstr.h \
  ../../dcmdata/include/dcelem.h ../../dcmdata/include/dcpcache.h \
  ../../ofstd/include/oflist.h ../include/diovlay.h ../include/diobjcou.h \
  ../include/diovdat.h ../include/diovpln.h ../include/diutils.h \
  ../include/dimopx.h ../include/dipixel.h ../include/dimomod.h \
  ../include/diluptab.h ../include/dibaslut.h ../include/dimoopx.h \
  ../include/didispfn.h ../include/didislut.h ../include/dimoipxt.h \
  ../../ofstd/include/ofbmanip.h ../include/dimopxt.h \
  ../../dcmdata/include/dcdefine.h ../include/dipxrept.h \
  ../include/diinpx.h ../include/dimoopxt.h
dimoimg5.o: dimoimg5.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/dimoimg.h \
  ../../dcmdata/include/dctypes.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/ofstdinc.h ../../ofstd/include/ofcast.h \
  ../include/diimage.h ../../dcmdata/include/dcitem.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofstream.h \
  ../../ofstd/include/ofthread.h ../../ofstd/include/ofstring.h \
  ../../dcmdata/include/dcobject.h ../../ofstd/include/ofglobal.h \
  ../../dcmdata/include/dcerror.h ../../ofstd/include/ofcond.h \
  ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
  ../../dcmdata/include/dctag.h ../../dcmdata/include/dctagkey.h \
  ../../dcmdata/include/dclist.h ../../dcmdata/include/dcstack.h \
  ../../dcmdata/include/dcvrui.h ../../dcmdata/include/dcbytstr.h \
  ../../dcmdata/include/dcelem.h ../../dcmdata/include/dcpcache.h \
  ../../ofstd/include/oflist.h ../include/diovlay.h ../include/diobjcou.h \
  ../include/diovdat.h ../include/diovpln.h ../include/diutils.h \
  ../include/dimopx.h ../include/dipixel.h ../include/dimomod.h \
  ../include/diluptab.h ../include/dibaslut.h ../include/dimoopx.h \
  ../include/didispfn.h ../include/didislut.h ../include/dimoipxt.h \
  ../../ofstd/include/ofbmanip.h ../include/dimopxt.h \
  ../../dcmdata/include/dcdefine.h ../include/dipxrept.h \
  ../include/diinpx.h ../include/dimoopxt.h
dimomod.o: dimomod.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../dcmdata/include/dcdeftag.h \
  ../../dcmdata/include/dctagkey.h ../../ofstd/include/ofstream.h \
  ../../dcmdata/include/dctypes.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/ofstdinc.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../../dcmdata/include/dcuid.h \
  ../include/dimomod.h ../include/diluptab.h ../include/dibaslut.h \
  ../include/diutils.h ../../ofstd/include/ofglobal.h \
  ../../ofstd/include/ofthread.h ../include/diobjcou.h \
  ../include/didocu.h ../../dcmdata/include/dcfilefo.h \
  ../../ofstd/include/ofconsol.h ../../dcmdata/include/dcerror.h \
  ../../ofstd/include/ofcond.h ../../dcmdata/include/dcsequen.h \
  ../../dcmdata/include/dcobject.h ../../dcmdata/include/dcxfer.h \
  ../../dcmdata/include/dcvr.h ../../dcmdata/include/dctag.h \
  ../../dcmdata/include/dclist.h ../../dcmdata/include/dcstack.h \
  ../../dcmdata/include/dcitem.h ../../dcmdata/include/dcvrui.h \
  ../../dcmdata/include/dcbytstr.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcpcache.h ../../ofstd/include/oflist.h \
  ../../dcmdata/include/dcdatset.h ../include/diinpx.h
dimoopx.o: dimoopx.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/dimoopx.h ../include/diutils.h \
  ../../dcmdata/include/dctypes.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/ofstdinc.h ../../ofstd/include/ofglobal.h \
  ../../ofstd/include/ofthread.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../../ofstd/include/ofstream.h \
  ../include/dimopx.h ../include/dipixel.h ../include/dimomod.h \
  ../include/diluptab.h ../../dcmdata/include/dctagkey.h \
  ../include/dibaslut.h ../include/diobjcou.h
dimopx.o: dimopx.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/dimopx.h \
  ../../dcmdata/include/dctypes.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/ofstdinc.h ../../ofstd/include/ofcast.h \
  ../include/dipixel.h ../include/diutils.h \
  ../../ofstd/include/ofglobal.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/ofstring.h ../../ofstd/include/ofstream.h \
  ../include/dimomod.h ../include/diluptab.h \
  ../../dcmdata/include/dctagkey.h ../include/dibaslut.h \
  ../include/diobjcou.h ../include/diinpx.h \
  ../../ofstd/include/ofconsol.h ../include/dimoopx.h
diovdat.o: diovdat.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../dcmdata/include/dctypes.h \
  ../../ofstd/include/oftypes.h ../../ofstd/include/ofstdinc.h \
  ../include/diovlay.h ../../ofstd/include/ofcast.h ../include/diobjcou.h \
  ../../ofstd/include/ofthread.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofstream.h ../include/diovdat.h \
  ../include/diovpln.h ../include/diutils.h \
  ../../ofstd/include/ofglobal.h ../../ofstd/include/ofbmanip.h
diovlay.o: diovlay.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../dcmdata/include/dctypes.h \
  ../../ofstd/include/oftypes.h ../../ofstd/include/ofstdinc.h \
  ../include/diovlay.h ../../ofstd/include/ofcast.h ../include/diobjcou.h \
  ../../ofstd/include/ofthread.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofstream.h ../include/diovdat.h \
  ../include/diovpln.h ../include/diutils.h \
  ../../ofstd/include/ofglobal.h ../include/discalet.h \
  ../../ofstd/include/ofconsol.h ../include/ditranst.h \
  ../../ofstd/include/ofbmanip.h ../include/dipxrept.h \
  ../include/diflipt.h ../include/dipixel.h ../include/dirotat.h \
  ../include/didocu.h ../../dcmdata/include/dcfilefo.h \
  ../../dcmdata/include/dcerror.h ../../ofstd/include/ofcond.h \
  ../../dcmdata/include/dcsequen.h ../../dcmdata/include/dcobject.h \
  ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
  ../../dcmdata/include/dctag.h ../../dcmdata/include/dctagkey.h \
  ../../dcmdata/include/dclist.h ../../dcmdata/include/dcstack.h \
  ../../dcmdata/include/dcitem.h ../../dcmdata/include/dcvrui.h \
  ../../dcmdata/include/dcbytstr.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcpcache.h ../../ofstd/include/oflist.h \
  ../../dcmdata/include/dcdatset.h
diovlimg.o: diovlimg.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../dcmdata/include/dctypes.h \
  ../../ofstd/include/oftypes.h ../../ofstd/include/ofstdinc.h \
  ../include/diovlimg.h ../include/dimo2img.h ../include/dimoimg.h \
  ../../ofstd/include/ofcast.h ../include/diimage.h \
  ../../dcmdata/include/dcitem.h ../../ofstd/include/ofconsol.h \
  ../../ofstd/include/ofstream.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/ofstring.h ../../dcmdata/include/dcobject.h \
  ../../ofstd/include/ofglobal.h ../../dcmdata/include/dcerror.h \
  ../../ofstd/include/ofcond.h ../../dcmdata/include/dcxfer.h \
  ../../dcmdata/include/dcvr.h ../../dcmdata/include/dctag.h \
  ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dclist.h \
  ../../dcmdata/include/dcstack.h ../../dcmdata/include/dcvrui.h \
  ../../dcmdata/include/dcbytstr.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcpcache.h ../../ofstd/include/oflist.h \
  ../include/diovlay.h ../include/diobjcou.h ../include/diovdat.h \
  ../include/diovpln.h ../include/diutils.h ../include/dimopx.h \
  ../include/dipixel.h ../include/dimomod.h ../include/diluptab.h \
  ../include/dibaslut.h ../include/dimoopx.h ../include/didispfn.h \
  ../include/didislut.h ../include/dimopxt.h \
  ../../ofstd/include/ofbmanip.h ../../dcmdata/include/dcdefine.h \
  ../include/dipxrept.h ../include/diinpx.h ../include/didocu.h \
  ../../dcmdata/include/dcfilefo.h ../../dcmdata/include/dcsequen.h \
  ../../dcmdata/include/dcdatset.h
diovpln.o: diovpln.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofconsol.h \
  ../../ofstd/include/ofstream.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/oftypes.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../../ofstd/include/ofstdinc.h \
  ../../dcmdata/include/dctypes.h ../../dcmdata/include/dcdeftag.h \
  ../../dcmdata/include/dctagkey.h ../../ofstd/include/ofbmanip.h \
  ../include/diovpln.h ../include/diutils.h \
  ../../ofstd/include/ofglobal.h ../include/didocu.h \
  ../../dcmdata/include/dcfilefo.h ../../dcmdata/include/dcerror.h \
  ../../ofstd/include/ofcond.h ../../dcmdata/include/dcsequen.h \
  ../../dcmdata/include/dcobject.h ../../dcmdata/include/dcxfer.h \
  ../../dcmdata/include/dcvr.h ../../dcmdata/include/dctag.h \
  ../../dcmdata/include/dclist.h ../../dcmdata/include/dcstack.h \
  ../../dcmdata/include/dcitem.h ../../dcmdata/include/dcvrui.h \
  ../../dcmdata/include/dcbytstr.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcpcache.h ../../ofstd/include/oflist.h \
  ../../dcmdata/include/dcdatset.h ../include/diobjcou.h
diutils.o: diutils.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../dcmdata/include/dctypes.h \
  ../../ofstd/include/oftypes.h ../../ofstd/include/ofstdinc.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofstream.h \
  ../../ofstd/include/ofthread.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../include/diutils.h \
  ../../ofstd/include/ofglobal.h
