dcmmkcrv.o: dcmmkcrv.cc ../../config/include/osconfig.h \
 ../../dcmdata/include/dctk.h ../../dcmdata/include/dctypes.h \
 ../../ofstd/include/oftypes.h ../../dcmdata/include/dcswap.h \
 ../../dcmdata/include/dcerror.h ../../dcmdata/include/dcxfer.h \
 ../../dcmdata/include/dcvr.h ../../dcmdata/include/dcstream.h \
 ../../dcmdata/include/dcuid.h ../../dcmdata/include/dcvm.h \
 ../../dcmdata/include/dcdefine.h ../../dcmdata/include/dcdebug.h \
 ../../dcmdata/include/dctagkey.h ../../ofstd/include/ofstring.h \
 ../../dcmdata/include/dctag.h ../../dcmdata/include/dcdicent.h \
 ../../dcmdata/include/dchashdi.h ../../ofstd/include/oflist.h \
 ../../dcmdata/include/dcdict.h ../../dcmdata/include/dcdeftag.h \
 ../../dcmdata/include/dcobject.h ../../dcmdata/include/dclist.h \
 ../../dcmdata/include/dcstack.h ../../dcmdata/include/dcelem.h \
 ../../dcmdata/include/dcitem.h ../../dcmdata/include/dcvrui.h \
 ../../dcmdata/include/dcbytstr.h ../../dcmdata/include/dcmetinf.h \
 ../../dcmdata/include/dcdatset.h ../../dcmdata/include/dcsequen.h \
 ../../dcmdata/include/dcfilefo.h ../../dcmdata/include/dcdicdir.h \
 ../../dcmdata/include/dcdirrec.h ../../dcmdata/include/dcvrulup.h \
 ../../dcmdata/include/dcvrul.h ../../dcmdata/include/dcpixseq.h \
 ../../dcmdata/include/dcvrae.h ../../dcmdata/include/dcvras.h \
 ../../dcmdata/include/dcvrcs.h ../../dcmdata/include/dcvrda.h \
 ../../dcmdata/include/dcvrds.h ../../dcmdata/include/dcvrdt.h \
 ../../dcmdata/include/dcvris.h ../../dcmdata/include/dcvrtm.h \
 ../../dcmdata/include/dcchrstr.h ../../dcmdata/include/dcvrlo.h \
 ../../dcmdata/include/dcvrlt.h ../../dcmdata/include/dcvrpn.h \
 ../../dcmdata/include/dcvrsh.h ../../dcmdata/include/dcvrst.h \
 ../../dcmdata/include/dcvrut.h ../../dcmdata/include/dcvrvs.h \
 ../../dcmdata/include/dcvrobow.h ../../dcmdata/include/dcpixel.h \
 ../../dcmdata/include/dcvrpobw.h ../../dcmdata/include/dcovlay.h \
 ../../dcmdata/include/dcvrat.h ../../dcmdata/include/dcvrss.h \
 ../../dcmdata/include/dcvrus.h ../../dcmdata/include/dcvrsl.h \
 ../../dcmdata/include/dcvrfl.h ../../dcmdata/include/dcvrfd.h \
 ../../dcmdata/include/cmdlnarg.h ../../ofstd/include/ofconapp.h \
 ../../ofstd/include/ofcmdln.h
dcmmklut.o: dcmmklut.cc ../../config/include/osconfig.h \
 ../../dcmdata/include/dctk.h ../../dcmdata/include/dctypes.h \
 ../../ofstd/include/oftypes.h ../../dcmdata/include/dcswap.h \
 ../../dcmdata/include/dcerror.h ../../dcmdata/include/dcxfer.h \
 ../../dcmdata/include/dcvr.h ../../dcmdata/include/dcstream.h \
 ../../dcmdata/include/dcuid.h ../../dcmdata/include/dcvm.h \
 ../../dcmdata/include/dcdefine.h ../../dcmdata/include/dcdebug.h \
 ../../dcmdata/include/dctagkey.h ../../ofstd/include/ofstring.h \
 ../../dcmdata/include/dctag.h ../../dcmdata/include/dcdicent.h \
 ../../dcmdata/include/dchashdi.h ../../ofstd/include/oflist.h \
 ../../dcmdata/include/dcdict.h ../../dcmdata/include/dcdeftag.h \
 ../../dcmdata/include/dcobject.h ../../dcmdata/include/dclist.h \
 ../../dcmdata/include/dcstack.h ../../dcmdata/include/dcelem.h \
 ../../dcmdata/include/dcitem.h ../../dcmdata/include/dcvrui.h \
 ../../dcmdata/include/dcbytstr.h ../../dcmdata/include/dcmetinf.h \
 ../../dcmdata/include/dcdatset.h ../../dcmdata/include/dcsequen.h \
 ../../dcmdata/include/dcfilefo.h ../../dcmdata/include/dcdicdir.h \
 ../../dcmdata/include/dcdirrec.h ../../dcmdata/include/dcvrulup.h \
 ../../dcmdata/include/dcvrul.h ../../dcmdata/include/dcpixseq.h \
 ../../dcmdata/include/dcvrae.h ../../dcmdata/include/dcvras.h \
 ../../dcmdata/include/dcvrcs.h ../../dcmdata/include/dcvrda.h \
 ../../dcmdata/include/dcvrds.h ../../dcmdata/include/dcvrdt.h \
 ../../dcmdata/include/dcvris.h ../../dcmdata/include/dcvrtm.h \
 ../../dcmdata/include/dcchrstr.h ../../dcmdata/include/dcvrlo.h \
 ../../dcmdata/include/dcvrlt.h ../../dcmdata/include/dcvrpn.h \
 ../../dcmdata/include/dcvrsh.h ../../dcmdata/include/dcvrst.h \
 ../../dcmdata/include/dcvrut.h ../../dcmdata/include/dcvrvs.h \
 ../../dcmdata/include/dcvrobow.h ../../dcmdata/include/dcpixel.h \
 ../../dcmdata/include/dcvrpobw.h ../../dcmdata/include/dcovlay.h \
 ../../dcmdata/include/dcvrat.h ../../dcmdata/include/dcvrss.h \
 ../../dcmdata/include/dcvrus.h ../../dcmdata/include/dcvrsl.h \
 ../../dcmdata/include/dcvrfl.h ../../dcmdata/include/dcvrfd.h \
 ../../dcmdata/include/cmdlnarg.h ../../ofstd/include/ofconapp.h \
 ../../ofstd/include/ofcmdln.h
dcmp2pgm.o: dcmp2pgm.cc ../../config/include/osconfig.h \
 ../include/dviface.h ../../dcmdata/include/dctk.h \
 ../../dcmdata/include/dctypes.h ../../ofstd/include/oftypes.h \
 ../../dcmdata/include/dcswap.h ../../dcmdata/include/dcerror.h \
 ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
 ../../dcmdata/include/dcstream.h ../../dcmdata/include/dcuid.h \
 ../../dcmdata/include/dcvm.h ../../dcmdata/include/dcdefine.h \
 ../../dcmdata/include/dcdebug.h ../../dcmdata/include/dctagkey.h \
 ../../ofstd/include/ofstring.h ../../dcmdata/include/dctag.h \
 ../../dcmdata/include/dcdicent.h ../../dcmdata/include/dchashdi.h \
 ../../ofstd/include/oflist.h ../../dcmdata/include/dcdict.h \
 ../../dcmdata/include/dcdeftag.h ../../dcmdata/include/dcobject.h \
 ../../dcmdata/include/dclist.h ../../dcmdata/include/dcstack.h \
 ../../dcmdata/include/dcelem.h ../../dcmdata/include/dcitem.h \
 ../../dcmdata/include/dcvrui.h ../../dcmdata/include/dcbytstr.h \
 ../../dcmdata/include/dcmetinf.h ../../dcmdata/include/dcdatset.h \
 ../../dcmdata/include/dcsequen.h ../../dcmdata/include/dcfilefo.h \
 ../../dcmdata/include/dcdicdir.h ../../dcmdata/include/dcdirrec.h \
 ../../dcmdata/include/dcvrulup.h ../../dcmdata/include/dcvrul.h \
 ../../dcmdata/include/dcpixseq.h ../../dcmdata/include/dcvrae.h \
 ../../dcmdata/include/dcvras.h ../../dcmdata/include/dcvrcs.h \
 ../../dcmdata/include/dcvrda.h ../../dcmdata/include/dcvrds.h \
 ../../dcmdata/include/dcvrdt.h ../../dcmdata/include/dcvris.h \
 ../../dcmdata/include/dcvrtm.h ../../dcmdata/include/dcchrstr.h \
 ../../dcmdata/include/dcvrlo.h ../../dcmdata/include/dcvrlt.h \
 ../../dcmdata/include/dcvrpn.h ../../dcmdata/include/dcvrsh.h \
 ../../dcmdata/include/dcvrst.h ../../dcmdata/include/dcvrut.h \
 ../../dcmdata/include/dcvrvs.h ../../dcmdata/include/dcvrobow.h \
 ../../dcmdata/include/dcpixel.h ../../dcmdata/include/dcvrpobw.h \
 ../../dcmdata/include/dcovlay.h ../../dcmdata/include/dcvrat.h \
 ../../dcmdata/include/dcvrss.h ../../dcmdata/include/dcvrus.h \
 ../../dcmdata/include/dcvrsl.h ../../dcmdata/include/dcvrfl.h \
 ../../dcmdata/include/dcvrfd.h ../../dcmdata/include/cmdlnarg.h \
 ../include/dvpscf.h ../include/dvpstyp.h ../include/dvpstat.h \
 ../include/dvpsovl.h ../include/dvpsgll.h ../include/dvpsrsl.h \
 ../include/dvpsall.h ../include/dvpsgal.h ../include/dvpscul.h \
 ../include/dvpsvll.h ../include/dvpsvwl.h ../include/dvpsdal.h \
 ../include/dvpssvl.h ../include/dvpspl.h \
 ../../imagectn/include/dbpriv.h ../../imagectn/include/imagedb.h \
 ../../dcmnet/include/dicom.h ../../dcmnet/include/dcompat.h \
 ../../ofstd/include/ofbmanip.h ../../dcmnet/include/cond.h \
 ../../dcmnet/include/dimse.h ../../dcmnet/include/lst.h \
 ../../dcmnet/include/dul.h ../../dcmnet/include/extneg.h \
 ../../dcmnet/include/assoc.h ../../imagectn/include/dbstore.h \
 ../include/dvcache.h ../include/dvpstx.h ../include/dvpsgr.h \
 ../include/dvpscu.h ../../dcmimgle/include/dcmimage.h \
 ../../dcmimgle/include/dimoimg.h ../../dcmimgle/include/diimage.h \
 ../../dcmimgle/include/diovlay.h ../../dcmimgle/include/diobjcou.h \
 ../../dcmimgle/include/diovdat.h ../../dcmimgle/include/diovpln.h \
 ../../dcmimgle/include/diutils.h ../../dcmimgle/include/dimopx.h \
 ../../dcmimgle/include/dipixel.h ../../dcmimgle/include/dimomod.h \
 ../../dcmimgle/include/diluptab.h ../../dcmimgle/include/dibaslut.h \
 ../../dcmimgle/include/dimoopx.h ../../dcmimgle/include/didispfn.h \
 ../../dcmimgle/include/didislut.h ../../ofstd/include/ofcmdln.h \
 ../../ofstd/include/ofconapp.h
dcmprtsv.o: dcmprtsv.cc ../../config/include/osconfig.h \
 ../include/dviface.h ../../dcmdata/include/dctk.h \
 ../../dcmdata/include/dctypes.h ../../ofstd/include/oftypes.h \
 ../../dcmdata/include/dcswap.h ../../dcmdata/include/dcerror.h \
 ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
 ../../dcmdata/include/dcstream.h ../../dcmdata/include/dcuid.h \
 ../../dcmdata/include/dcvm.h ../../dcmdata/include/dcdefine.h \
 ../../dcmdata/include/dcdebug.h ../../dcmdata/include/dctagkey.h \
 ../../ofstd/include/ofstring.h ../../dcmdata/include/dctag.h \
 ../../dcmdata/include/dcdicent.h ../../dcmdata/include/dchashdi.h \
 ../../ofstd/include/oflist.h ../../dcmdata/include/dcdict.h \
 ../../dcmdata/include/dcdeftag.h ../../dcmdata/include/dcobject.h \
 ../../dcmdata/include/dclist.h ../../dcmdata/include/dcstack.h \
 ../../dcmdata/include/dcelem.h ../../dcmdata/include/dcitem.h \
 ../../dcmdata/include/dcvrui.h ../../dcmdata/include/dcbytstr.h \
 ../../dcmdata/include/dcmetinf.h ../../dcmdata/include/dcdatset.h \
 ../../dcmdata/include/dcsequen.h ../../dcmdata/include/dcfilefo.h \
 ../../dcmdata/include/dcdicdir.h ../../dcmdata/include/dcdirrec.h \
 ../../dcmdata/include/dcvrulup.h ../../dcmdata/include/dcvrul.h \
 ../../dcmdata/include/dcpixseq.h ../../dcmdata/include/dcvrae.h \
 ../../dcmdata/include/dcvras.h ../../dcmdata/include/dcvrcs.h \
 ../../dcmdata/include/dcvrda.h ../../dcmdata/include/dcvrds.h \
 ../../dcmdata/include/dcvrdt.h ../../dcmdata/include/dcvris.h \
 ../../dcmdata/include/dcvrtm.h ../../dcmdata/include/dcchrstr.h \
 ../../dcmdata/include/dcvrlo.h ../../dcmdata/include/dcvrlt.h \
 ../../dcmdata/include/dcvrpn.h ../../dcmdata/include/dcvrsh.h \
 ../../dcmdata/include/dcvrst.h ../../dcmdata/include/dcvrut.h \
 ../../dcmdata/include/dcvrvs.h ../../dcmdata/include/dcvrobow.h \
 ../../dcmdata/include/dcpixel.h ../../dcmdata/include/dcvrpobw.h \
 ../../dcmdata/include/dcovlay.h ../../dcmdata/include/dcvrat.h \
 ../../dcmdata/include/dcvrss.h ../../dcmdata/include/dcvrus.h \
 ../../dcmdata/include/dcvrsl.h ../../dcmdata/include/dcvrfl.h \
 ../../dcmdata/include/dcvrfd.h ../../dcmdata/include/cmdlnarg.h \
 ../include/dvpscf.h ../include/dvpstyp.h ../include/dvpstat.h \
 ../include/dvpsovl.h ../include/dvpsgll.h ../include/dvpsrsl.h \
 ../include/dvpsall.h ../include/dvpsgal.h ../include/dvpscul.h \
 ../include/dvpsvll.h ../include/dvpsvwl.h ../include/dvpsdal.h \
 ../include/dvpssvl.h ../include/dvpspl.h \
 ../../imagectn/include/dbpriv.h ../../imagectn/include/imagedb.h \
 ../../dcmnet/include/dicom.h ../../dcmnet/include/dcompat.h \
 ../../ofstd/include/ofbmanip.h ../../dcmnet/include/cond.h \
 ../../dcmnet/include/dimse.h ../../dcmnet/include/lst.h \
 ../../dcmnet/include/dul.h ../../dcmnet/include/extneg.h \
 ../../dcmnet/include/assoc.h ../../imagectn/include/dbstore.h \
 ../include/dvcache.h ../../ofstd/include/ofconapp.h \
 ../../ofstd/include/ofcmdln.h ../../dcmimgle/include/dcmimage.h \
 ../../dcmimgle/include/dimoimg.h ../../dcmimgle/include/diimage.h \
 ../../dcmimgle/include/diovlay.h ../../dcmimgle/include/diobjcou.h \
 ../../dcmimgle/include/diovdat.h ../../dcmimgle/include/diovpln.h \
 ../../dcmimgle/include/diutils.h ../../dcmimgle/include/dimopx.h \
 ../../dcmimgle/include/dipixel.h ../../dcmimgle/include/dimomod.h \
 ../../dcmimgle/include/diluptab.h ../../dcmimgle/include/dibaslut.h \
 ../../dcmimgle/include/dimoopx.h ../../dcmimgle/include/didispfn.h \
 ../../dcmimgle/include/didislut.h ../include/dvpspr.h \
 ../include/dvpssp.h ../include/dvpsibl.h ../include/dvpshlp.h
dcmpsmk.o: dcmpsmk.cc ../../config/include/osconfig.h \
 ../../dcmdata/include/dctk.h ../../dcmdata/include/dctypes.h \
 ../../ofstd/include/oftypes.h ../../dcmdata/include/dcswap.h \
 ../../dcmdata/include/dcerror.h ../../dcmdata/include/dcxfer.h \
 ../../dcmdata/include/dcvr.h ../../dcmdata/include/dcstream.h \
 ../../dcmdata/include/dcuid.h ../../dcmdata/include/dcvm.h \
 ../../dcmdata/include/dcdefine.h ../../dcmdata/include/dcdebug.h \
 ../../dcmdata/include/dctagkey.h ../../ofstd/include/ofstring.h \
 ../../dcmdata/include/dctag.h ../../dcmdata/include/dcdicent.h \
 ../../dcmdata/include/dchashdi.h ../../ofstd/include/oflist.h \
 ../../dcmdata/include/dcdict.h ../../dcmdata/include/dcdeftag.h \
 ../../dcmdata/include/dcobject.h ../../dcmdata/include/dclist.h \
 ../../dcmdata/include/dcstack.h ../../dcmdata/include/dcelem.h \
 ../../dcmdata/include/dcitem.h ../../dcmdata/include/dcvrui.h \
 ../../dcmdata/include/dcbytstr.h ../../dcmdata/include/dcmetinf.h \
 ../../dcmdata/include/dcdatset.h ../../dcmdata/include/dcsequen.h \
 ../../dcmdata/include/dcfilefo.h ../../dcmdata/include/dcdicdir.h \
 ../../dcmdata/include/dcdirrec.h ../../dcmdata/include/dcvrulup.h \
 ../../dcmdata/include/dcvrul.h ../../dcmdata/include/dcpixseq.h \
 ../../dcmdata/include/dcvrae.h ../../dcmdata/include/dcvras.h \
 ../../dcmdata/include/dcvrcs.h ../../dcmdata/include/dcvrda.h \
 ../../dcmdata/include/dcvrds.h ../../dcmdata/include/dcvrdt.h \
 ../../dcmdata/include/dcvris.h ../../dcmdata/include/dcvrtm.h \
 ../../dcmdata/include/dcchrstr.h ../../dcmdata/include/dcvrlo.h \
 ../../dcmdata/include/dcvrlt.h ../../dcmdata/include/dcvrpn.h \
 ../../dcmdata/include/dcvrsh.h ../../dcmdata/include/dcvrst.h \
 ../../dcmdata/include/dcvrut.h ../../dcmdata/include/dcvrvs.h \
 ../../dcmdata/include/dcvrobow.h ../../dcmdata/include/dcpixel.h \
 ../../dcmdata/include/dcvrpobw.h ../../dcmdata/include/dcovlay.h \
 ../../dcmdata/include/dcvrat.h ../../dcmdata/include/dcvrss.h \
 ../../dcmdata/include/dcvrus.h ../../dcmdata/include/dcvrsl.h \
 ../../dcmdata/include/dcvrfl.h ../../dcmdata/include/dcvrfd.h \
 ../../dcmdata/include/cmdlnarg.h ../include/dvpstat.h \
 ../include/dvpstyp.h ../include/dvpsovl.h ../include/dvpsgll.h \
 ../include/dvpsrsl.h ../include/dvpsall.h ../include/dvpsgal.h \
 ../include/dvpscul.h ../include/dvpsvll.h ../include/dvpsvwl.h \
 ../include/dvpsdal.h ../include/dvpssvl.h ../include/dvpspl.h \
 ../../ofstd/include/ofconapp.h ../../ofstd/include/ofcmdln.h
dcmpsprt.o: dcmpsprt.cc ../../config/include/osconfig.h \
 ../include/dviface.h ../../dcmdata/include/dctk.h \
 ../../dcmdata/include/dctypes.h ../../ofstd/include/oftypes.h \
 ../../dcmdata/include/dcswap.h ../../dcmdata/include/dcerror.h \
 ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
 ../../dcmdata/include/dcstream.h ../../dcmdata/include/dcuid.h \
 ../../dcmdata/include/dcvm.h ../../dcmdata/include/dcdefine.h \
 ../../dcmdata/include/dcdebug.h ../../dcmdata/include/dctagkey.h \
 ../../ofstd/include/ofstring.h ../../dcmdata/include/dctag.h \
 ../../dcmdata/include/dcdicent.h ../../dcmdata/include/dchashdi.h \
 ../../ofstd/include/oflist.h ../../dcmdata/include/dcdict.h \
 ../../dcmdata/include/dcdeftag.h ../../dcmdata/include/dcobject.h \
 ../../dcmdata/include/dclist.h ../../dcmdata/include/dcstack.h \
 ../../dcmdata/include/dcelem.h ../../dcmdata/include/dcitem.h \
 ../../dcmdata/include/dcvrui.h ../../dcmdata/include/dcbytstr.h \
 ../../dcmdata/include/dcmetinf.h ../../dcmdata/include/dcdatset.h \
 ../../dcmdata/include/dcsequen.h ../../dcmdata/include/dcfilefo.h \
 ../../dcmdata/include/dcdicdir.h ../../dcmdata/include/dcdirrec.h \
 ../../dcmdata/include/dcvrulup.h ../../dcmdata/include/dcvrul.h \
 ../../dcmdata/include/dcpixseq.h ../../dcmdata/include/dcvrae.h \
 ../../dcmdata/include/dcvras.h ../../dcmdata/include/dcvrcs.h \
 ../../dcmdata/include/dcvrda.h ../../dcmdata/include/dcvrds.h \
 ../../dcmdata/include/dcvrdt.h ../../dcmdata/include/dcvris.h \
 ../../dcmdata/include/dcvrtm.h ../../dcmdata/include/dcchrstr.h \
 ../../dcmdata/include/dcvrlo.h ../../dcmdata/include/dcvrlt.h \
 ../../dcmdata/include/dcvrpn.h ../../dcmdata/include/dcvrsh.h \
 ../../dcmdata/include/dcvrst.h ../../dcmdata/include/dcvrut.h \
 ../../dcmdata/include/dcvrvs.h ../../dcmdata/include/dcvrobow.h \
 ../../dcmdata/include/dcpixel.h ../../dcmdata/include/dcvrpobw.h \
 ../../dcmdata/include/dcovlay.h ../../dcmdata/include/dcvrat.h \
 ../../dcmdata/include/dcvrss.h ../../dcmdata/include/dcvrus.h \
 ../../dcmdata/include/dcvrsl.h ../../dcmdata/include/dcvrfl.h \
 ../../dcmdata/include/dcvrfd.h ../../dcmdata/include/cmdlnarg.h \
 ../include/dvpscf.h ../include/dvpstyp.h ../include/dvpstat.h \
 ../include/dvpsovl.h ../include/dvpsgll.h ../include/dvpsrsl.h \
 ../include/dvpsall.h ../include/dvpsgal.h ../include/dvpscul.h \
 ../include/dvpsvll.h ../include/dvpsvwl.h ../include/dvpsdal.h \
 ../include/dvpssvl.h ../include/dvpspl.h \
 ../../imagectn/include/dbpriv.h ../../imagectn/include/imagedb.h \
 ../../dcmnet/include/dicom.h ../../dcmnet/include/dcompat.h \
 ../../ofstd/include/ofbmanip.h ../../dcmnet/include/cond.h \
 ../../dcmnet/include/dimse.h ../../dcmnet/include/lst.h \
 ../../dcmnet/include/dul.h ../../dcmnet/include/extneg.h \
 ../../dcmnet/include/assoc.h ../../imagectn/include/dbstore.h \
 ../include/dvcache.h ../include/dvpssp.h ../include/dvpsibl.h \
 ../include/dvpspr.h ../../dcmimgle/include/dcmimage.h \
 ../../dcmimgle/include/dimoimg.h ../../dcmimgle/include/diimage.h \
 ../../dcmimgle/include/diovlay.h ../../dcmimgle/include/diobjcou.h \
 ../../dcmimgle/include/diovdat.h ../../dcmimgle/include/diovpln.h \
 ../../dcmimgle/include/diutils.h ../../dcmimgle/include/dimopx.h \
 ../../dcmimgle/include/dipixel.h ../../dcmimgle/include/dimomod.h \
 ../../dcmimgle/include/diluptab.h ../../dcmimgle/include/dibaslut.h \
 ../../dcmimgle/include/dimoopx.h ../../dcmimgle/include/didispfn.h \
 ../../dcmimgle/include/didislut.h ../../ofstd/include/ofcmdln.h \
 ../../ofstd/include/ofconapp.h
dcmpsrcv.o: dcmpsrcv.cc ../../config/include/osconfig.h \
 ../include/dviface.h ../../dcmdata/include/dctk.h \
 ../../dcmdata/include/dctypes.h ../../ofstd/include/oftypes.h \
 ../../dcmdata/include/dcswap.h ../../dcmdata/include/dcerror.h \
 ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
 ../../dcmdata/include/dcstream.h ../../dcmdata/include/dcuid.h \
 ../../dcmdata/include/dcvm.h ../../dcmdata/include/dcdefine.h \
 ../../dcmdata/include/dcdebug.h ../../dcmdata/include/dctagkey.h \
 ../../ofstd/include/ofstring.h ../../dcmdata/include/dctag.h \
 ../../dcmdata/include/dcdicent.h ../../dcmdata/include/dchashdi.h \
 ../../ofstd/include/oflist.h ../../dcmdata/include/dcdict.h \
 ../../dcmdata/include/dcdeftag.h ../../dcmdata/include/dcobject.h \
 ../../dcmdata/include/dclist.h ../../dcmdata/include/dcstack.h \
 ../../dcmdata/include/dcelem.h ../../dcmdata/include/dcitem.h \
 ../../dcmdata/include/dcvrui.h ../../dcmdata/include/dcbytstr.h \
 ../../dcmdata/include/dcmetinf.h ../../dcmdata/include/dcdatset.h \
 ../../dcmdata/include/dcsequen.h ../../dcmdata/include/dcfilefo.h \
 ../../dcmdata/include/dcdicdir.h ../../dcmdata/include/dcdirrec.h \
 ../../dcmdata/include/dcvrulup.h ../../dcmdata/include/dcvrul.h \
 ../../dcmdata/include/dcpixseq.h ../../dcmdata/include/dcvrae.h \
 ../../dcmdata/include/dcvras.h ../../dcmdata/include/dcvrcs.h \
 ../../dcmdata/include/dcvrda.h ../../dcmdata/include/dcvrds.h \
 ../../dcmdata/include/dcvrdt.h ../../dcmdata/include/dcvris.h \
 ../../dcmdata/include/dcvrtm.h ../../dcmdata/include/dcchrstr.h \
 ../../dcmdata/include/dcvrlo.h ../../dcmdata/include/dcvrlt.h \
 ../../dcmdata/include/dcvrpn.h ../../dcmdata/include/dcvrsh.h \
 ../../dcmdata/include/dcvrst.h ../../dcmdata/include/dcvrut.h \
 ../../dcmdata/include/dcvrvs.h ../../dcmdata/include/dcvrobow.h \
 ../../dcmdata/include/dcpixel.h ../../dcmdata/include/dcvrpobw.h \
 ../../dcmdata/include/dcovlay.h ../../dcmdata/include/dcvrat.h \
 ../../dcmdata/include/dcvrss.h ../../dcmdata/include/dcvrus.h \
 ../../dcmdata/include/dcvrsl.h ../../dcmdata/include/dcvrfl.h \
 ../../dcmdata/include/dcvrfd.h ../../dcmdata/include/cmdlnarg.h \
 ../include/dvpscf.h ../include/dvpstyp.h ../include/dvpstat.h \
 ../include/dvpsovl.h ../include/dvpsgll.h ../include/dvpsrsl.h \
 ../include/dvpsall.h ../include/dvpsgal.h ../include/dvpscul.h \
 ../include/dvpsvll.h ../include/dvpsvwl.h ../include/dvpsdal.h \
 ../include/dvpssvl.h ../include/dvpspl.h \
 ../../imagectn/include/dbpriv.h ../../imagectn/include/imagedb.h \
 ../../dcmnet/include/dicom.h ../../dcmnet/include/dcompat.h \
 ../../ofstd/include/ofbmanip.h ../../dcmnet/include/cond.h \
 ../../dcmnet/include/dimse.h ../../dcmnet/include/lst.h \
 ../../dcmnet/include/dul.h ../../dcmnet/include/extneg.h \
 ../../dcmnet/include/assoc.h ../../imagectn/include/dbstore.h \
 ../include/dvcache.h ../../dcmnet/include/diutil.h \
 ../../ofstd/include/ofconapp.h ../../ofstd/include/ofcmdln.h
dcmpssnd.o: dcmpssnd.cc ../../config/include/osconfig.h \
 ../include/dviface.h ../../dcmdata/include/dctk.h \
 ../../dcmdata/include/dctypes.h ../../ofstd/include/oftypes.h \
 ../../dcmdata/include/dcswap.h ../../dcmdata/include/dcerror.h \
 ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
 ../../dcmdata/include/dcstream.h ../../dcmdata/include/dcuid.h \
 ../../dcmdata/include/dcvm.h ../../dcmdata/include/dcdefine.h \
 ../../dcmdata/include/dcdebug.h ../../dcmdata/include/dctagkey.h \
 ../../ofstd/include/ofstring.h ../../dcmdata/include/dctag.h \
 ../../dcmdata/include/dcdicent.h ../../dcmdata/include/dchashdi.h \
 ../../ofstd/include/oflist.h ../../dcmdata/include/dcdict.h \
 ../../dcmdata/include/dcdeftag.h ../../dcmdata/include/dcobject.h \
 ../../dcmdata/include/dclist.h ../../dcmdata/include/dcstack.h \
 ../../dcmdata/include/dcelem.h ../../dcmdata/include/dcitem.h \
 ../../dcmdata/include/dcvrui.h ../../dcmdata/include/dcbytstr.h \
 ../../dcmdata/include/dcmetinf.h ../../dcmdata/include/dcdatset.h \
 ../../dcmdata/include/dcsequen.h ../../dcmdata/include/dcfilefo.h \
 ../../dcmdata/include/dcdicdir.h ../../dcmdata/include/dcdirrec.h \
 ../../dcmdata/include/dcvrulup.h ../../dcmdata/include/dcvrul.h \
 ../../dcmdata/include/dcpixseq.h ../../dcmdata/include/dcvrae.h \
 ../../dcmdata/include/dcvras.h ../../dcmdata/include/dcvrcs.h \
 ../../dcmdata/include/dcvrda.h ../../dcmdata/include/dcvrds.h \
 ../../dcmdata/include/dcvrdt.h ../../dcmdata/include/dcvris.h \
 ../../dcmdata/include/dcvrtm.h ../../dcmdata/include/dcchrstr.h \
 ../../dcmdata/include/dcvrlo.h ../../dcmdata/include/dcvrlt.h \
 ../../dcmdata/include/dcvrpn.h ../../dcmdata/include/dcvrsh.h \
 ../../dcmdata/include/dcvrst.h ../../dcmdata/include/dcvrut.h \
 ../../dcmdata/include/dcvrvs.h ../../dcmdata/include/dcvrobow.h \
 ../../dcmdata/include/dcpixel.h ../../dcmdata/include/dcvrpobw.h \
 ../../dcmdata/include/dcovlay.h ../../dcmdata/include/dcvrat.h \
 ../../dcmdata/include/dcvrss.h ../../dcmdata/include/dcvrus.h \
 ../../dcmdata/include/dcvrsl.h ../../dcmdata/include/dcvrfl.h \
 ../../dcmdata/include/dcvrfd.h ../../dcmdata/include/cmdlnarg.h \
 ../include/dvpscf.h ../include/dvpstyp.h ../include/dvpstat.h \
 ../include/dvpsovl.h ../include/dvpsgll.h ../include/dvpsrsl.h \
 ../include/dvpsall.h ../include/dvpsgal.h ../include/dvpscul.h \
 ../include/dvpsvll.h ../include/dvpsvwl.h ../include/dvpsdal.h \
 ../include/dvpssvl.h ../include/dvpspl.h \
 ../../imagectn/include/dbpriv.h ../../imagectn/include/imagedb.h \
 ../../dcmnet/include/dicom.h ../../dcmnet/include/dcompat.h \
 ../../ofstd/include/ofbmanip.h ../../dcmnet/include/cond.h \
 ../../dcmnet/include/dimse.h ../../dcmnet/include/lst.h \
 ../../dcmnet/include/dul.h ../../dcmnet/include/extneg.h \
 ../../dcmnet/include/assoc.h ../../imagectn/include/dbstore.h \
 ../include/dvcache.h ../../dcmnet/include/diutil.h \
 ../../ofstd/include/ofconapp.h ../../ofstd/include/ofcmdln.h \
 ../include/dvpshlp.h
dconvmap.o: dconvmap.cc ../../config/include/osconfig.h \
 ../../dcmdata/include/dctk.h ../../dcmdata/include/dctypes.h \
 ../../ofstd/include/oftypes.h ../../dcmdata/include/dcswap.h \
 ../../dcmdata/include/dcerror.h ../../dcmdata/include/dcxfer.h \
 ../../dcmdata/include/dcvr.h ../../dcmdata/include/dcstream.h \
 ../../dcmdata/include/dcuid.h ../../dcmdata/include/dcvm.h \
 ../../dcmdata/include/dcdefine.h ../../dcmdata/include/dcdebug.h \
 ../../dcmdata/include/dctagkey.h ../../ofstd/include/ofstring.h \
 ../../dcmdata/include/dctag.h ../../dcmdata/include/dcdicent.h \
 ../../dcmdata/include/dchashdi.h ../../ofstd/include/oflist.h \
 ../../dcmdata/include/dcdict.h ../../dcmdata/include/dcdeftag.h \
 ../../dcmdata/include/dcobject.h ../../dcmdata/include/dclist.h \
 ../../dcmdata/include/dcstack.h ../../dcmdata/include/dcelem.h \
 ../../dcmdata/include/dcitem.h ../../dcmdata/include/dcvrui.h \
 ../../dcmdata/include/dcbytstr.h ../../dcmdata/include/dcmetinf.h \
 ../../dcmdata/include/dcdatset.h ../../dcmdata/include/dcsequen.h \
 ../../dcmdata/include/dcfilefo.h ../../dcmdata/include/dcdicdir.h \
 ../../dcmdata/include/dcdirrec.h ../../dcmdata/include/dcvrulup.h \
 ../../dcmdata/include/dcvrul.h ../../dcmdata/include/dcpixseq.h \
 ../../dcmdata/include/dcvrae.h ../../dcmdata/include/dcvras.h \
 ../../dcmdata/include/dcvrcs.h ../../dcmdata/include/dcvrda.h \
 ../../dcmdata/include/dcvrds.h ../../dcmdata/include/dcvrdt.h \
 ../../dcmdata/include/dcvris.h ../../dcmdata/include/dcvrtm.h \
 ../../dcmdata/include/dcchrstr.h ../../dcmdata/include/dcvrlo.h \
 ../../dcmdata/include/dcvrlt.h ../../dcmdata/include/dcvrpn.h \
 ../../dcmdata/include/dcvrsh.h ../../dcmdata/include/dcvrst.h \
 ../../dcmdata/include/dcvrut.h ../../dcmdata/include/dcvrvs.h \
 ../../dcmdata/include/dcvrobow.h ../../dcmdata/include/dcpixel.h \
 ../../dcmdata/include/dcvrpobw.h ../../dcmdata/include/dcovlay.h \
 ../../dcmdata/include/dcvrat.h ../../dcmdata/include/dcvrss.h \
 ../../dcmdata/include/dcvrus.h ../../dcmdata/include/dcvrsl.h \
 ../../dcmdata/include/dcvrfl.h ../../dcmdata/include/dcvrfd.h \
 ../../dcmdata/include/cmdlnarg.h ../../ofstd/include/ofconapp.h \
 ../../ofstd/include/ofcmdln.h ../../dcmimgle/include/displint.h
