#ifndef FLEX_HEADER_vrscan_h
#define FLEX_HEADER_vrscan_h
#define YY_vrscan_CHAR unsigned char
#line 1 "flexskel.xh"
/* A lexical scanner header generated by flex */
/* MODIFIED FOR C++ CLASS BY Alain Coetmeur: coetmeur(at)icdc.fr */
/* Note that (at) mean the 'at' symbol that I cannot write */
/* because it is expanded to the class name */
/* made at Informatique-CDC, Research&development department */
/* company from the Caisse Des Depots et Consignations */


/*********************************************/
/* SYSTEM dependent declaration, includes... */
/*********************************************/
/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif
#ifdef __cplusplus
#ifndef YY_USE_PROTOS
#define YY_USE_PROTOS
#endif
#ifndef YY_USE_CLASS
#define YY_USE_CLASS
#endif
#else	/* ! __cplusplus */
#ifdef __STDC__
#ifdef __GNUC__
#else
#endif	/* __GNUC__ */
#ifndef YY_USE_PROTOS
#define YY_USE_PROTOS
#endif
#endif	/* __STDC__ */
#endif	/* ! __cplusplus */
/*********************************************/
/* COMPILER DEPENDENT   MACROS               */
/*********************************************/
/* use prototypes in function declarations */
#ifndef YY_PROTO
#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif
#endif

#ifdef __cplusplus
#define INCLUDE_CSTDIO
#include "dcmtk/ofstd/ofstdinc.h"
#else
#include <stdio.h>
#endif


/* % here is the declaration from section1 %header{  */ 
#line 76 "vrscan.l"
#define YY_vrscan_IOSTREAM 
#line 78 "vrscan.l"
#define YY_vrscan_MEMBERS  \
  private: \
    /* undefined */ vrscan& operator=(const vrscan&); \
    /* undefined */ vrscan(const vrscan&);
#line 84 "vrscan.l"
#include "dcmtk/config/osconfig.h"    /* make sure OS specific configuration is included first */
#line 134 "vrscan.l"
#line 56 "flexskel.xh"

#ifdef YY_USE_CLASS
#ifdef YY_vrscan_IOSTREAM
#include "dcmtk/ofstd/ofstream.h"
#define YY_vrscan_IFILE  istream
#define YY_vrscan_OFILE ostream 
#define YY_vrscan_ERRFILE cerr

#ifndef YY_vrscan_IFILE_DEFAULT
#define YY_vrscan_IFILE_DEFAULT &cin
#endif

#ifndef YY_vrscan_OFILE_DEFAULT
#define YY_vrscan_OFILE_DEFAULT &cout
#endif

#endif
#endif

#ifndef YY_vrscan_IFILE
#define YY_vrscan_IFILE FILE 
#endif

#ifndef YY_vrscan_OFILE
#define YY_vrscan_OFILE FILE 
#endif

#ifndef YY_vrscan_ERRFILE
#define YY_vrscan_ERRFILE stderr
#endif

#ifndef YY_vrscan_IFILE_DEFAULT
#define YY_vrscan_IFILE_DEFAULT stdin
#endif

#ifndef YY_vrscan_OFILE_DEFAULT
#define YY_vrscan_OFILE_DEFAULT stdout
#endif




#ifndef YY_vrscan_TEXT
#define YY_vrscan_TEXT yytext
#endif
#ifndef YY_vrscan_LENG
#define YY_vrscan_LENG yyleng
#endif
#ifndef YY_vrscan_IN
#define YY_vrscan_IN yyin
#endif
#ifndef YY_vrscan_OUT
#define YY_vrscan_OUT yyout
#endif

#ifndef YY_vrscan_LEX_RETURN
#define YY_vrscan_LEX_RETURN int
#else
#ifndef YY_vrscan_LEX_DEFINED
#define YY_vrscan_LEX_DEFINED 
#endif
#endif

#ifndef YY_vrscan_LEX
#define YY_vrscan_LEX yylex
#else
#ifndef YY_vrscan_LEX_DEFINED
#define YY_vrscan_LEX_DEFINED 
#endif
#endif

#ifndef YY_vrscan_LEX_PARAM
#ifndef YY_USE_PROTOS
#define YY_vrscan_LEX_PARAM 
#else
#define YY_vrscan_LEX_PARAM void
#endif
#else
#ifndef YY_vrscan_LEX_DEFINED
#define YY_vrscan_LEX_DEFINED 
#endif
#endif

#ifndef YY_vrscan_LEX_PARAM_DEF
#define YY_vrscan_LEX_PARAM_DEF
#else
#ifndef YY_vrscan_LEX_DEFINED
#define YY_vrscan_LEX_DEFINED 
#endif
#endif

#ifndef YY_vrscan_RESTART
#define YY_vrscan_RESTART yyrestart
#endif
#ifndef YY_vrscan_SWITCH_TO_BUFFER
#define YY_vrscan_SWITCH_TO_BUFFER yy_switch_to_buffer
#endif
#ifndef YY_vrscan_LOAD_BUFFER_STATE
#define YY_vrscan_LOAD_BUFFER_STATE yy_load_buffer_state
#endif

#ifndef YY_vrscan_CREATE_BUFFER
#define YY_vrscan_CREATE_BUFFER yy_create_buffer
#ifndef YY_USE_CLASS
#ifndef yy_new_buffer
#define yy_new_buffer yy_create_buffer
#endif
#endif
#endif
#ifndef YY_vrscan_DELETE_BUFFER
#define YY_vrscan_DELETE_BUFFER yy_delete_buffer
#endif
#ifndef YY_vrscan_INIT_BUFFER
#define YY_vrscan_INIT_BUFFER yy_init_buffer
#endif



#ifdef YY_vrscan_FLEX_DEBUG
#ifndef YY_vrscan_DEBUG
#define YY_vrscan_DEBUG 1
#endif
#else
#ifndef YY_vrscan_DEBUG
#define YY_vrscan_DEBUG 0
#endif
#endif

#if YY_vrscan_DEBUG != 0
#ifndef YY_vrscan_DEBUG_FLAG
#define YY_vrscan_DEBUG_FLAG yy_flex_debug
#endif
#ifndef YY_vrscan_DEBUG_INIT
#define YY_vrscan_DEBUG_INIT 1
#endif
#endif




#ifndef YY_USE_CLASS
#ifndef YY_vrscan_CURRENT_BUFFER
#define YY_vrscan_CURRENT_BUFFER yy_current_buffer
#endif
typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern void YY_vrscan_RESTART YY_PROTO(( YY_vrscan_IFILE *input_file ));
extern void YY_vrscan_SWITCH_TO_BUFFER YY_PROTO(( YY_BUFFER_STATE new_buffer ));
extern void YY_vrscan_LOAD_BUFFER_STATE YY_PROTO(( void ));
extern YY_BUFFER_STATE YY_vrscan_CREATE_BUFFER YY_PROTO(( YY_vrscan_IFILE *file, int size ));
extern void YY_vrscan_DELETE_BUFFER YY_PROTO(( YY_BUFFER_STATE b ));
extern void YY_vrscan_INIT_BUFFER YY_PROTO(( YY_BUFFER_STATE b, YY_vrscan_IFILE *file ));

#if YY_vrscan_DEBUG != 0
extern int YY_vrscan_DEBUG_FLAG ;
#endif
extern YY_vrscan_CHAR  *YY_vrscan_TEXT;
extern int YY_vrscan_LENG;
extern YY_vrscan_IFILE *YY_vrscan_IN;
extern YY_vrscan_OFILE *YY_vrscan_OUT;
#ifdef YY_vrscan_LEX_DEFINED
extern YY_vrscan_LEX_RETURN YY_vrscan_LEX ( YY_vrscan_LEX_PARAM )
YY_vrscan_LEX_PARAM_DEF
#else
#ifndef YY_DECL
extern YY_vrscan_LEX_RETURN YY_vrscan_LEX ( YY_vrscan_LEX_PARAM )
YY_vrscan_LEX_PARAM_DEF
#else
/* no declaration if oldstyle flex */
#endif
#endif
#else

#ifndef YY_vrscan_CURRENT_BUFFER
#define YY_vrscan_CURRENT_BUFFER YY_CURRENT_BUFFER
#endif
#ifndef YY_vrscan_CLASS
#define YY_vrscan_CLASS vrscan
#endif
#ifndef YY_vrscan_ECHO
#define YY_vrscan_ECHO yy_echo
#endif
#ifdef YY_vrscan_ECHO_PURE
#define YY_vrscan_ECHO_NOCODE
#endif

#ifndef YY_vrscan_ECHO_CODE
#ifndef YY_vrscan_IOSTREAM
#define YY_vrscan_ECHO_CODE fwrite( OFreinterpret_cast(char *, YY_vrscan_TEXT), YY_vrscan_LENG, 1, YY_vrscan_OUT );
#else
#define YY_vrscan_ECHO_CODE (YY_vrscan_OUT->write( OFreinterpret_cast(char *, YY_vrscan_TEXT), YY_vrscan_LENG));
#endif
#endif

#ifndef YY_vrscan_INPUT
#define YY_vrscan_INPUT yy_input
#endif
#ifdef YY_vrscan_INPUT_PURE
#define YY_vrscan_INPUT_NOCODE
#endif

#ifndef YY_vrscan_INPUT_CODE
#ifndef YY_vrscan_IOSTREAM
#define YY_vrscan_INPUT_CODE return result= fread(  buffer, 1,max_size,YY_vrscan_IN );
#else
#define YY_vrscan_INPUT_CODE if(YY_vrscan_IN->eof())  result=0;else {YY_vrscan_IN->read(buffer,max_size);result=YY_vrscan_IN->gcount();YY_vrscan_IN->clear(YY_vrscan_IN->rdstate()&(~ios::failbit));if(YY_vrscan_IN->bad()) result= -1;} return result;
#endif
#endif

#ifdef YY_vrscan_FATAL_ERROR_PURE
#define YY_vrscan_FATAL_ERRO_NOCODE
#endif
#ifndef YY_vrscan_FATAL_ERROR
#define YY_vrscan_FATAL_ERROR yy_fatal_error
#endif

#ifndef YY_vrscan_FATAL_ERROR_CODE
#ifndef YY_vrscan_IOSTREAM
#define YY_vrscan_FATAL_ERROR_CODE fputs( msg, YY_vrscan_ERRFILE );putc( '\n', YY_vrscan_ERRFILE );exit( 1 );
#else
#define YY_vrscan_FATAL_ERROR_CODE YY_vrscan_ERRFILE<< msg <<endl;exit( 1 );
#endif
#endif

#ifndef YY_vrscan_WRAP
#define YY_vrscan_WRAP yy_wrap
#endif
#ifdef YY_vrscan_WRAP_PURE
#define YY_vrscan_WRAP_NOCODE
#endif
#ifndef YY_vrscan_WRAP_CODE
#define YY_vrscan_WRAP_CODE return 1;
#endif


#ifndef YY_vrscan_INHERIT
#define YY_vrscan_INHERIT
#endif
#ifndef YY_vrscan_MEMBERS
#define YY_vrscan_MEMBERS 
#endif
#ifndef YY_vrscan_CONSTRUCTOR_PARAM
#define YY_vrscan_CONSTRUCTOR_PARAM
#endif
#ifndef YY_vrscan_CONSTRUCTOR_CODE
#define YY_vrscan_CONSTRUCTOR_CODE
#endif
#ifndef YY_vrscan_CONSTRUCTOR_INIT
#define YY_vrscan_CONSTRUCTOR_INIT
#endif
#ifndef YY_vrscan_DESTRUCTOR_CODE
#define YY_vrscan_DESTRUCTOR_CODE
#endif
typedef struct yy_buffer_state *YY_BUFFER_STATE;

class YY_vrscan_CLASS YY_vrscan_INHERIT
{
 private:/* data */
 YY_vrscan_CHAR  *yy_c_buf_p;
 YY_vrscan_CHAR  yy_hold_char;
 int yy_n_chars;
 int yy_init;
 int yy_start;
 int yy_did_buffer_switch_on_eof;
 private: /* functions */
 void yy_initialize();
 int input();
 int yyinput() {return input();};
 int yy_get_next_buffer();
 void yyunput( YY_vrscan_CHAR  c, YY_vrscan_CHAR  *buf_ptr );
 /* use long instead of yy_state_type because it is undef */
 long yy_get_previous_state_ ( void );
 long yy_try_NUL_trans_  ( long current_state_ );
 protected:/* non virtual */
 YY_BUFFER_STATE YY_vrscan_CURRENT_BUFFER;
 void YY_vrscan_RESTART ( YY_vrscan_IFILE *input_file );
 void YY_vrscan_SWITCH_TO_BUFFER( YY_BUFFER_STATE new_buffer );
 void YY_vrscan_LOAD_BUFFER_STATE( void );
 YY_BUFFER_STATE YY_vrscan_CREATE_BUFFER( YY_vrscan_IFILE *file, int size );
 void YY_vrscan_DELETE_BUFFER( YY_BUFFER_STATE b );
 void YY_vrscan_INIT_BUFFER( YY_BUFFER_STATE b, YY_vrscan_IFILE *file );
 protected: /* virtual */
 virtual void YY_vrscan_ECHO()
#ifdef YY_vrscan_ECHO_PURE
  =0
#endif
  ;
 virtual int  YY_vrscan_INPUT(char  *buf,int &result,int max_size)
#ifdef YY_vrscan_INPUT_PURE
  =0
#endif
  ;
 virtual void  YY_vrscan_FATAL_ERROR(const char *msg)
#ifdef YY_vrscan_FATAL_ERROR_PURE
  =0
#endif
  ;
 virtual int  YY_vrscan_WRAP()
#ifdef YY_vrscan_WRAP_PURE
  =0
#endif
  ;
 public:
 YY_vrscan_CHAR  *YY_vrscan_TEXT;
 int YY_vrscan_LENG;
 YY_vrscan_IFILE *YY_vrscan_IN;
 YY_vrscan_OFILE *YY_vrscan_OUT;
 YY_vrscan_LEX_RETURN YY_vrscan_LEX ( YY_vrscan_LEX_PARAM);
 YY_vrscan_CLASS(YY_vrscan_CONSTRUCTOR_PARAM) ;
 virtual ~YY_vrscan_CLASS() ;
#if YY_vrscan_DEBUG != 0
 int YY_vrscan_DEBUG_FLAG;
#endif
 public: /* added members */
 YY_vrscan_MEMBERS 
};
#endif



/* declaration of externs for public use of yylex scanner */

/* % here is the declaration from section2 %header{ */ 
#line 153 "vrscan.l"
#endif
#line 379 "flexskel.xh"

/* end of generated header */
