echoscu.o: echoscu.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofstdinc.h \
  ../include/dimse.h ../include/dicom.h ../include/cond.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofstream.h \
  ../../ofstd/include/ofthread.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/ofstring.h ../../ofstd/include/ofcast.h \
  ../../dcmdata/include/dcerror.h ../../ofstd/include/ofcond.h \
  ../include/dcompat.h ../../ofstd/include/ofbmanip.h \
  ../../dcmdata/include/dctypes.h ../../dcmdata/include/dcuid.h \
  ../include/lst.h ../../ofstd/include/oflist.h ../include/dul.h \
  ../../ofstd/include/ofglobal.h ../include/extneg.h ../include/assoc.h \
  ../../dcmdata/include/dcdatset.h ../../dcmdata/include/dcitem.h \
  ../../dcmdata/include/dcobject.h ../../dcmdata/include/dcxfer.h \
  ../../dcmdata/include/dcvr.h ../../dcmdata/include/dctag.h \
  ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dclist.h \
  ../../dcmdata/include/dcstack.h ../../dcmdata/include/dcvrui.h \
  ../../dcmdata/include/dcbytstr.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcpcache.h ../include/diutil.h \
  ../../dcmdata/include/dcfilefo.h ../../dcmdata/include/dcsequen.h \
  ../../dcmdata/include/dcdebug.h ../../dcmdata/include/dcdict.h \
  ../../dcmdata/include/dchashdi.h ../../dcmdata/include/cmdlnarg.h \
  ../../ofstd/include/ofconapp.h ../../ofstd/include/ofcmdln.h \
  ../../dcmtls/include/tlstrans.h ../include/dcmtrans.h \
  ../include/dcmlayer.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/ssl.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/e_os2.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/opensslconf.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/comp.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/crypto.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/stack.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/safestack.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/opensslv.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/ossl_typ.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/symhacks.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/bio.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/x509.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/buffer.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/evp.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/objects.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/obj_mac.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/asn1.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/bn.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/ec.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/ecdsa.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/ecdh.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/rsa.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/dsa.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/dh.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/sha.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/x509_vfy.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/lhash.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/pkcs7.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/pem.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/pem2.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/kssl.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/ssl2.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/ssl3.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/pq_compat.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/tls1.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/dtls1.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/pqueue.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/ssl23.h \
  ../../dcmtls/include/tlslayer.h
findscu.o: findscu.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofstdinc.h \
  ../include/dimse.h ../include/dicom.h ../include/cond.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofstream.h \
  ../../ofstd/include/ofthread.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/ofstring.h ../../ofstd/include/ofcast.h \
  ../../dcmdata/include/dcerror.h ../../ofstd/include/ofcond.h \
  ../include/dcompat.h ../../ofstd/include/ofbmanip.h \
  ../../dcmdata/include/dctypes.h ../../dcmdata/include/dcuid.h \
  ../include/lst.h ../../ofstd/include/oflist.h ../include/dul.h \
  ../../ofstd/include/ofglobal.h ../include/extneg.h ../include/assoc.h \
  ../../dcmdata/include/dcdatset.h ../../dcmdata/include/dcitem.h \
  ../../dcmdata/include/dcobject.h ../../dcmdata/include/dcxfer.h \
  ../../dcmdata/include/dcvr.h ../../dcmdata/include/dctag.h \
  ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dclist.h \
  ../../dcmdata/include/dcstack.h ../../dcmdata/include/dcvrui.h \
  ../../dcmdata/include/dcbytstr.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcpcache.h ../include/diutil.h \
  ../../dcmdata/include/dcfilefo.h ../../dcmdata/include/dcsequen.h \
  ../../dcmdata/include/dcdebug.h ../../dcmdata/include/dcdict.h \
  ../../dcmdata/include/dchashdi.h ../../dcmdata/include/cmdlnarg.h \
  ../../ofstd/include/ofconapp.h ../../ofstd/include/ofcmdln.h \
  ../../dcmdata/include/dcdicent.h ../../dcmtls/include/tlstrans.h \
  ../include/dcmtrans.h ../include/dcmlayer.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/ssl.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/e_os2.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/opensslconf.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/comp.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/crypto.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/stack.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/safestack.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/opensslv.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/ossl_typ.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/symhacks.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/bio.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/x509.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/buffer.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/evp.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/objects.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/obj_mac.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/asn1.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/bn.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/ec.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/ecdsa.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/ecdh.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/rsa.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/dsa.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/dh.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/sha.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/x509_vfy.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/lhash.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/pkcs7.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/pem.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/pem2.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/kssl.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/ssl2.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/ssl3.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/pq_compat.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/tls1.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/dtls1.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/pqueue.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/ssl23.h \
  ../../dcmtls/include/tlslayer.h
movescu.o: movescu.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofstdinc.h \
  ../include/dicom.h ../include/cond.h ../../ofstd/include/ofconsol.h \
  ../../ofstd/include/ofstream.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/oftypes.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../../dcmdata/include/dcerror.h \
  ../../ofstd/include/ofcond.h ../include/dcompat.h \
  ../../ofstd/include/ofbmanip.h ../../dcmdata/include/dctypes.h \
  ../../dcmdata/include/dcuid.h ../include/dimse.h ../include/lst.h \
  ../../ofstd/include/oflist.h ../include/dul.h \
  ../../ofstd/include/ofglobal.h ../include/extneg.h ../include/assoc.h \
  ../../dcmdata/include/dcdatset.h ../../dcmdata/include/dcitem.h \
  ../../dcmdata/include/dcobject.h ../../dcmdata/include/dcxfer.h \
  ../../dcmdata/include/dcvr.h ../../dcmdata/include/dctag.h \
  ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dclist.h \
  ../../dcmdata/include/dcstack.h ../../dcmdata/include/dcvrui.h \
  ../../dcmdata/include/dcbytstr.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcpcache.h ../include/diutil.h \
  ../../dcmdata/include/dcfilefo.h ../../dcmdata/include/dcsequen.h \
  ../../dcmdata/include/dcdebug.h ../../dcmdata/include/dcdict.h \
  ../../dcmdata/include/dchashdi.h ../../dcmdata/include/cmdlnarg.h \
  ../../ofstd/include/ofconapp.h ../../ofstd/include/ofcmdln.h \
  ../../ofstd/include/ofstd.h ../../dcmdata/include/dcdicent.h
storescp.o: storescp.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofstdinc.h \
  ../include/dimse.h ../include/dicom.h ../include/cond.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofstream.h \
  ../../ofstd/include/ofthread.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/ofstring.h ../../ofstd/include/ofcast.h \
  ../../dcmdata/include/dcerror.h ../../ofstd/include/ofcond.h \
  ../include/dcompat.h ../../ofstd/include/ofbmanip.h \
  ../../dcmdata/include/dctypes.h ../../dcmdata/include/dcuid.h \
  ../include/lst.h ../../ofstd/include/oflist.h ../include/dul.h \
  ../../ofstd/include/ofglobal.h ../include/extneg.h ../include/assoc.h \
  ../../dcmdata/include/dcdatset.h ../../dcmdata/include/dcitem.h \
  ../../dcmdata/include/dcobject.h ../../dcmdata/include/dcxfer.h \
  ../../dcmdata/include/dcvr.h ../../dcmdata/include/dctag.h \
  ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dclist.h \
  ../../dcmdata/include/dcstack.h ../../dcmdata/include/dcvrui.h \
  ../../dcmdata/include/dcbytstr.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcpcache.h ../include/diutil.h \
  ../../dcmdata/include/dcfilefo.h ../../dcmdata/include/dcsequen.h \
  ../../dcmdata/include/dcdebug.h ../../dcmdata/include/dcdict.h \
  ../../dcmdata/include/dchashdi.h ../../dcmdata/include/cmdlnarg.h \
  ../../ofstd/include/ofconapp.h ../../ofstd/include/ofcmdln.h \
  ../../ofstd/include/ofstd.h ../../ofstd/include/ofdatime.h \
  ../../ofstd/include/ofdate.h ../../ofstd/include/oftime.h \
  ../../dcmdata/include/dcdeftag.h ../../dcmdata/include/dcostrmz.h \
  ../../dcmdata/include/dcostrma.h ../include/dcasccfg.h \
  ../include/dccftsmp.h ../include/dcmsmap.h ../include/dccfuidh.h \
  ../include/dccfpcmp.h ../include/dccfrsmp.h ../include/dccfenmp.h \
  ../include/dccfprmp.h ../include/dcasccff.h \
  ../../dcmtls/include/tlstrans.h ../include/dcmtrans.h \
  ../include/dcmlayer.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/ssl.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/e_os2.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/opensslconf.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/comp.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/crypto.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/stack.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/safestack.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/opensslv.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/ossl_typ.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/symhacks.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/bio.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/x509.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/buffer.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/evp.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/objects.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/obj_mac.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/asn1.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/bn.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/ec.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/ecdsa.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/ecdh.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/rsa.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/dsa.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/dh.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/sha.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/x509_vfy.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/lhash.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/pkcs7.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/pem.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/pem2.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/kssl.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/ssl2.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/ssl3.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/pq_compat.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/tls1.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/dtls1.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/pqueue.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/ssl23.h \
  ../../dcmtls/include/tlslayer.h
storescu.o: storescu.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofstdinc.h \
  ../../ofstd/include/ofstring.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/ofcast.h ../../ofstd/include/ofstream.h \
  ../include/dimse.h ../include/dicom.h ../include/cond.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofthread.h \
  ../../dcmdata/include/dcerror.h ../../ofstd/include/ofcond.h \
  ../include/dcompat.h ../../ofstd/include/ofbmanip.h \
  ../../dcmdata/include/dctypes.h ../../dcmdata/include/dcuid.h \
  ../include/lst.h ../../ofstd/include/oflist.h ../include/dul.h \
  ../../ofstd/include/ofglobal.h ../include/extneg.h ../include/assoc.h \
  ../../dcmdata/include/dcdatset.h ../../dcmdata/include/dcitem.h \
  ../../dcmdata/include/dcobject.h ../../dcmdata/include/dcxfer.h \
  ../../dcmdata/include/dcvr.h ../../dcmdata/include/dctag.h \
  ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dclist.h \
  ../../dcmdata/include/dcstack.h ../../dcmdata/include/dcvrui.h \
  ../../dcmdata/include/dcbytstr.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcpcache.h ../include/diutil.h \
  ../../dcmdata/include/dcmetinf.h ../../dcmdata/include/dcfilefo.h \
  ../../dcmdata/include/dcsequen.h ../../dcmdata/include/dcdebug.h \
  ../../dcmdata/include/dcdict.h ../../dcmdata/include/dchashdi.h \
  ../../dcmdata/include/dcdeftag.h ../../dcmdata/include/cmdlnarg.h \
  ../../ofstd/include/ofconapp.h ../../ofstd/include/ofcmdln.h \
  ../../dcmdata/include/dcostrmz.h ../../dcmdata/include/dcostrma.h \
  ../include/dcasccfg.h ../include/dccftsmp.h ../include/dcmsmap.h \
  ../include/dccfuidh.h ../include/dccfpcmp.h ../include/dccfrsmp.h \
  ../include/dccfenmp.h ../include/dccfprmp.h ../include/dcasccff.h \
  ../../dcmtls/include/tlstrans.h ../include/dcmtrans.h \
  ../include/dcmlayer.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/ssl.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/e_os2.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/opensslconf.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/comp.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/crypto.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/stack.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/safestack.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/opensslv.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/ossl_typ.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/symhacks.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/bio.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/x509.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/buffer.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/evp.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/objects.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/obj_mac.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/asn1.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/bn.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/ec.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/ecdsa.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/ecdh.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/rsa.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/dsa.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/dh.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/sha.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/x509_vfy.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/lhash.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/pkcs7.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/pem.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/pem2.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/kssl.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/ssl2.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/ssl3.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/pq_compat.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/tls1.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/dtls1.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/pqueue.h \
  /usr/local/apps/openssl-0.9.8a/include/openssl/ssl23.h \
  ../../dcmtls/include/tlslayer.h
termscu.o: termscu.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofstdinc.h \
  ../../ofstd/include/ofcmdln.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/oflist.h ../../ofstd/include/ofcast.h \
  ../../ofstd/include/ofstring.h ../../ofstd/include/ofstream.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofthread.h \
  ../include/assoc.h ../include/dicom.h ../include/cond.h \
  ../../dcmdata/include/dcerror.h ../../ofstd/include/ofcond.h \
  ../include/dcompat.h ../../ofstd/include/ofbmanip.h \
  ../../dcmdata/include/dctypes.h ../../dcmdata/include/dcuid.h \
  ../include/lst.h ../include/dul.h ../../ofstd/include/ofglobal.h \
  ../include/extneg.h ../../ofstd/include/ofconapp.h \
  ../../dcmdata/include/cmdlnarg.h ../include/dimse.h \
  ../../dcmdata/include/dcdatset.h ../../dcmdata/include/dcitem.h \
  ../../dcmdata/include/dcobject.h ../../dcmdata/include/dcxfer.h \
  ../../dcmdata/include/dcvr.h ../../dcmdata/include/dctag.h \
  ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dclist.h \
  ../../dcmdata/include/dcstack.h ../../dcmdata/include/dcvrui.h \
  ../../dcmdata/include/dcbytstr.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcpcache.h ../../dcmdata/include/dcdebug.h \
  ../../dcmdata/include/dcdict.h ../../dcmdata/include/dchashdi.h
