cmdlnarg.o: cmdlnarg.cc ../../config/include/osconfig.h
echoscu.o: echoscu.cc ../../config/include/osconfig.h \
 ../include/dimse.h ../include/dicom.h ../include/dcompat.h \
 ../../dcmdata/include/dctypes.h ../../dcmdata/include/dcuid.h \
 ../include/lst.h ../include/cond.h ../include/dul.h \
 ../include/assoc.h ../../dcmdata/include/dcdatset.h \
 ../../dcmdata/include/dcerror.h ../../dcmdata/include/dcitem.h \
 ../../dcmdata/include/dcobject.h ../../dcmdata/include/dcxfer.h \
 ../../dcmdata/include/dcstream.h ../../dcmdata/include/dcbuf.h \
 ../../dcmdata/include/dcdefine.h ../../dcmdata/include/dctag.h \
 ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dcvr.h \
 ../../dcmdata/include/dcdicent.h ../../dcmdata/include/dcstack.h \
 ../../dcmdata/include/dcvrui.h ../../dcmdata/include/dcbytstr.h \
 ../../dcmdata/include/dcelem.h ../../dcmdata/include/dclist.h \
 ../include/diutil.h ../../dcmdata/include/dcfilefo.h \
 ../../dcmdata/include/dcsequen.h ../../dcmdata/include/dcmetinf.h \
 ../../dcmdata/include/dcdebug.h ../../dcmdata/include/dcdict.h \
 ../../dcmdata/include/dcentbst.h ../../dcmdata/include/dcentset.h \
 ../../dcmdata/include/pix.h ../../dcmdata/include/dcentdef.h \
 ../../dcmdata/include/dcentlst.h cmdlnarg.h
storescp.o: storescp.cc ../../config/include/osconfig.h \
 ../include/dimse.h ../include/dicom.h ../include/dcompat.h \
 ../../dcmdata/include/dctypes.h ../../dcmdata/include/dcuid.h \
 ../include/lst.h ../include/cond.h ../include/dul.h \
 ../include/assoc.h ../../dcmdata/include/dcdatset.h \
 ../../dcmdata/include/dcerror.h ../../dcmdata/include/dcitem.h \
 ../../dcmdata/include/dcobject.h ../../dcmdata/include/dcxfer.h \
 ../../dcmdata/include/dcstream.h ../../dcmdata/include/dcbuf.h \
 ../../dcmdata/include/dcdefine.h ../../dcmdata/include/dctag.h \
 ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dcvr.h \
 ../../dcmdata/include/dcdicent.h ../../dcmdata/include/dcstack.h \
 ../../dcmdata/include/dcvrui.h ../../dcmdata/include/dcbytstr.h \
 ../../dcmdata/include/dcelem.h ../../dcmdata/include/dclist.h \
 ../include/diutil.h ../../dcmdata/include/dcfilefo.h \
 ../../dcmdata/include/dcsequen.h ../../dcmdata/include/dcmetinf.h \
 ../../dcmdata/include/dcdebug.h ../../dcmdata/include/dcdict.h \
 ../../dcmdata/include/dcentbst.h ../../dcmdata/include/dcentset.h \
 ../../dcmdata/include/pix.h ../../dcmdata/include/dcentdef.h \
 ../../dcmdata/include/dcentlst.h cmdlnarg.h
storescu.o: storescu.cc ../../config/include/osconfig.h \
 ../include/dimse.h ../include/dicom.h ../include/dcompat.h \
 ../../dcmdata/include/dctypes.h ../../dcmdata/include/dcuid.h \
 ../include/lst.h ../include/cond.h ../include/dul.h \
 ../include/assoc.h ../../dcmdata/include/dcdatset.h \
 ../../dcmdata/include/dcerror.h ../../dcmdata/include/dcitem.h \
 ../../dcmdata/include/dcobject.h ../../dcmdata/include/dcxfer.h \
 ../../dcmdata/include/dcstream.h ../../dcmdata/include/dcbuf.h \
 ../../dcmdata/include/dcdefine.h ../../dcmdata/include/dctag.h \
 ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dcvr.h \
 ../../dcmdata/include/dcdicent.h ../../dcmdata/include/dcstack.h \
 ../../dcmdata/include/dcvrui.h ../../dcmdata/include/dcbytstr.h \
 ../../dcmdata/include/dcelem.h ../../dcmdata/include/dclist.h \
 ../include/diutil.h ../../dcmdata/include/dcfilefo.h \
 ../../dcmdata/include/dcsequen.h ../../dcmdata/include/dcmetinf.h \
 ../../dcmdata/include/dcdebug.h ../../dcmdata/include/dcdict.h \
 ../../dcmdata/include/dcentbst.h ../../dcmdata/include/dcentset.h \
 ../../dcmdata/include/pix.h ../../dcmdata/include/dcentdef.h \
 ../../dcmdata/include/dcentlst.h cmdlnarg.h
