dcbytstr.o: dcbytstr.cc ../include/dcbytstr.h ../include/dctypes.h \
 ../include/dcelem.h ../include/dcobject.h ../include/dcdicenu.h \
 ../include/ddicenuz.i ../include/dcstream.h ../include/dctag.h \
 ../include/dcstack.h ../include/dcvr.h ../include/dcdebug.h
dcchrstr.o: dcchrstr.cc ../include/dcchrstr.h ../include/dctypes.h \
 ../include/dcelem.h ../include/dcobject.h ../include/dcdicenu.h \
 ../include/ddicenuz.i ../include/dcstream.h ../include/dctag.h \
 ../include/dcstack.h ../include/dcvr.h ../include/dcdebug.h
dcdatset.o: dcdatset.cc ../include/dcdatset.h ../include/dctypes.h \
 ../include/dcitem.h ../include/dcobject.h ../include/dcdicenu.h \
 ../include/ddicenuz.i ../include/dcstream.h ../include/dctag.h \
 ../include/dcstack.h ../include/dcvrui.h ../include/dcelem.h \
 ../include/dcbytstr.h ../include/dclist.h ../include/dcxfer.h \
 ../include/dcvrus.h ../include/dcdebug.h
dcdebug.o: dcdebug.cc ../include/dcdebug.h
dcelem.o: dcelem.cc ../include/dcelem.h ../include/dctypes.h \
 ../include/dcobject.h ../include/dcdicenu.h ../include/ddicenuz.i \
 ../include/dcstream.h ../include/dctag.h ../include/dcstack.h \
 ../include/dcdebug.h
dcfilefo.o: dcfilefo.cc ../include/dcfilefo.h ../include/dctypes.h \
 ../include/dcsequen.h ../include/dcelem.h ../include/dcobject.h \
 ../include/dcdicenu.h ../include/ddicenuz.i ../include/dcstream.h \
 ../include/dctag.h ../include/dcstack.h ../include/dcitem.h \
 ../include/dcvrui.h ../include/dcbytstr.h ../include/dclist.h \
 ../include/dcmetinf.h ../include/dcdatset.h ../include/dcxfer.h \
 ../include/dcmodtbl.h ../include/dcvrobow.h ../include/dcvrul.h \
 ../include/dcvrus.h ../include/dcvrae.h ../include/dcvrsh.h \
 ../include/dcchrstr.h ../include/dcdebug.h
dcitem.o: dcitem.cc ../include/dctk.h ../include/dctypes.h \
 ../include/dcswap.h ../include/dcstream.h ../include/dcvr.h \
 ../include/dcdicenu.h ../include/ddicenuz.i ../include/dcxfer.h \
 ../include/dcobject.h ../include/dctag.h ../include/dcstack.h \
 ../include/dcelem.h ../include/dcitem.h ../include/dcvrui.h \
 ../include/dcbytstr.h ../include/dclist.h ../include/dcmetinf.h \
 ../include/dcdatset.h ../include/dcsequen.h ../include/dcfilefo.h \
 ../include/dicomdir/dcdicdir.h ../include/dicomdir/dcdirrec.h \
 ../include/dcvrulup.h ../include/dcvrul.h ../include/dcpixseq.h \
 ../include/dcvrae.h ../include/dcvras.h ../include/dcvrcs.h \
 ../include/dcvrda.h ../include/dcvrds.h ../include/dcvrdt.h \
 ../include/dcvris.h ../include/dcvrtm.h ../include/dcchrstr.h \
 ../include/dcvrlo.h ../include/dcvrlt.h ../include/dcvrpn.h \
 ../include/dcvrsh.h ../include/dcvrst.h ../include/dcvrobow.h \
 ../include/dcpxitem.h ../include/dcvrat.h ../include/dcvrss.h \
 ../include/dcvrus.h ../include/dcvrsl.h ../include/dcvrfl.h \
 ../include/dcvrfd.h ../include/dcdebug.h
dclist.o: dclist.cc ../include/dclist.h ../include/dctypes.h \
 ../include/dcdebug.h
dcmetinf.o: dcmetinf.cc ../include/dcmetinf.h ../include/dctypes.h \
 ../include/dcitem.h ../include/dcobject.h ../include/dcdicenu.h \
 ../include/ddicenuz.i ../include/dcstream.h ../include/dctag.h \
 ../include/dcstack.h ../include/dcvrui.h ../include/dcelem.h \
 ../include/dcbytstr.h ../include/dclist.h ../include/dcxfer.h \
 ../include/dcvrul.h ../include/dcdebug.h
dcmodtbl.o: dcmodtbl.cc ../include/dcmodtbl.h ../include/dctypes.h \
 ../include/dcdicenu.h ../include/ddicenuz.i ../include/dcdebug.h \
 ../include/ddicrefz.ix
dcobject.o: dcobject.cc ../include/dcobject.h ../include/dctypes.h \
 ../include/dcdicenu.h ../include/ddicenuz.i ../include/dcstream.h \
 ../include/dctag.h ../include/dcstack.h ../include/dcvr.h \
 ../include/dcxfer.h ../include/dcdebug.h
dcpixseq.o: dcpixseq.cc ../include/dcpixseq.h ../include/dctypes.h \
 ../include/dcsequen.h ../include/dcelem.h ../include/dcobject.h \
 ../include/dcdicenu.h ../include/ddicenuz.i ../include/dcstream.h \
 ../include/dctag.h ../include/dcstack.h ../include/dcitem.h \
 ../include/dcvrui.h ../include/dcbytstr.h ../include/dclist.h \
 ../include/dcpxitem.h ../include/dcvr.h ../include/dcdebug.h
dcpxitem.o: dcpxitem.cc ../include/dcpxitem.h ../include/dctypes.h \
 ../include/dcitem.h ../include/dcobject.h ../include/dcdicenu.h \
 ../include/ddicenuz.i ../include/dcstream.h ../include/dctag.h \
 ../include/dcstack.h ../include/dcvrui.h ../include/dcelem.h \
 ../include/dcbytstr.h ../include/dclist.h ../include/dcdebug.h
dcsequen.o: dcsequen.cc ../include/dcsequen.h ../include/dctypes.h \
 ../include/dcelem.h ../include/dcobject.h ../include/dcdicenu.h \
 ../include/ddicenuz.i ../include/dcstream.h ../include/dctag.h \
 ../include/dcstack.h ../include/dcitem.h ../include/dcvrui.h \
 ../include/dcbytstr.h ../include/dclist.h \
 ../include/dicomdir/dcdirrec.h ../include/dcfilefo.h \
 ../include/dcmetinf.h ../include/dcdatset.h ../include/dcvr.h \
 ../include/dcdebug.h
dcstack.o: dcstack.cc ../include/dcstack.h ../include/dctypes.h \
 ../include/dcdebug.h
dcstream.o: dcstream.cc ../include/dcstream.h ../include/dctypes.h \
 ../include/dcswap.h ../include/dcxfer.h ../include/dcdebug.h
dcswap.o: dcswap.cc ../include/dcswap.h ../include/dctypes.h \
 ../include/dcdebug.h ../include/dcxfer.h
dctag.o: dctag.cc ../include/dctag.h ../include/dctypes.h \
 ../include/dcdicenu.h ../include/ddicenuz.i ../include/dcdebug.h \
 ../include/ddicnamz.i ../include/ddicvarz.i
dcvr.o: dcvr.cc ../include/dcvr.h ../include/dctypes.h \
 ../include/dcdicenu.h ../include/ddicenuz.i ../include/dcdebug.h
dcvrae.o: dcvrae.cc ../include/dcvrae.h ../include/dctypes.h \
 ../include/dcelem.h ../include/dcobject.h ../include/dcdicenu.h \
 ../include/ddicenuz.i ../include/dcstream.h ../include/dctag.h \
 ../include/dcstack.h ../include/dcbytstr.h ../include/dcdebug.h
dcvras.o: dcvras.cc ../include/dcvras.h ../include/dctypes.h \
 ../include/dcelem.h ../include/dcobject.h ../include/dcdicenu.h \
 ../include/ddicenuz.i ../include/dcstream.h ../include/dctag.h \
 ../include/dcstack.h ../include/dcbytstr.h ../include/dcdebug.h
dcvrat.o: dcvrat.cc ../include/dcvrat.h ../include/dctypes.h \
 ../include/dcelem.h ../include/dcobject.h ../include/dcdicenu.h \
 ../include/ddicenuz.i ../include/dcstream.h ../include/dctag.h \
 ../include/dcstack.h ../include/dcdebug.h
dcvrcs.o: dcvrcs.cc ../include/dcvrcs.h ../include/dctypes.h \
 ../include/dcelem.h ../include/dcobject.h ../include/dcdicenu.h \
 ../include/ddicenuz.i ../include/dcstream.h ../include/dctag.h \
 ../include/dcstack.h ../include/dcbytstr.h ../include/dcdebug.h
dcvrda.o: dcvrda.cc ../include/dcvrda.h ../include/dctypes.h \
 ../include/dcelem.h ../include/dcobject.h ../include/dcdicenu.h \
 ../include/ddicenuz.i ../include/dcstream.h ../include/dctag.h \
 ../include/dcstack.h ../include/dcbytstr.h ../include/dcdebug.h
dcvrds.o: dcvrds.cc ../include/dcvrds.h ../include/dctypes.h \
 ../include/dcelem.h ../include/dcobject.h ../include/dcdicenu.h \
 ../include/ddicenuz.i ../include/dcstream.h ../include/dctag.h \
 ../include/dcstack.h ../include/dcbytstr.h ../include/dcdebug.h
dcvrdt.o: dcvrdt.cc ../include/dcvrdt.h ../include/dctypes.h \
 ../include/dcelem.h ../include/dcobject.h ../include/dcdicenu.h \
 ../include/ddicenuz.i ../include/dcstream.h ../include/dctag.h \
 ../include/dcstack.h ../include/dcbytstr.h ../include/dcdebug.h
dcvrfd.o: dcvrfd.cc ../include/dcvrfd.h ../include/dctypes.h \
 ../include/dcelem.h ../include/dcobject.h ../include/dcdicenu.h \
 ../include/ddicenuz.i ../include/dcstream.h ../include/dctag.h \
 ../include/dcstack.h ../include/dcdebug.h
dcvrfl.o: dcvrfl.cc ../include/dcvrfl.h ../include/dctypes.h \
 ../include/dcelem.h ../include/dcobject.h ../include/dcdicenu.h \
 ../include/ddicenuz.i ../include/dcstream.h ../include/dctag.h \
 ../include/dcstack.h ../include/dcdebug.h
dcvris.o: dcvris.cc ../include/dcvris.h ../include/dctypes.h \
 ../include/dcelem.h ../include/dcobject.h ../include/dcdicenu.h \
 ../include/ddicenuz.i ../include/dcstream.h ../include/dctag.h \
 ../include/dcstack.h ../include/dcbytstr.h ../include/dcdebug.h
dcvrlo.o: dcvrlo.cc ../include/dcvrlo.h ../include/dctypes.h \
 ../include/dcelem.h ../include/dcobject.h ../include/dcdicenu.h \
 ../include/ddicenuz.i ../include/dcstream.h ../include/dctag.h \
 ../include/dcstack.h ../include/dcchrstr.h ../include/dcdebug.h
dcvrlt.o: dcvrlt.cc ../include/dcvrlt.h ../include/dctypes.h \
 ../include/dcelem.h ../include/dcobject.h ../include/dcdicenu.h \
 ../include/ddicenuz.i ../include/dcstream.h ../include/dctag.h \
 ../include/dcstack.h ../include/dcchrstr.h ../include/dcdebug.h
dcvrobow.o: dcvrobow.cc ../include/dcvrobow.h ../include/dctypes.h \
 ../include/dcelem.h ../include/dcobject.h ../include/dcdicenu.h \
 ../include/ddicenuz.i ../include/dcstream.h ../include/dctag.h \
 ../include/dcstack.h ../include/dcswap.h ../include/dcdebug.h
dcvrpn.o: dcvrpn.cc ../include/dcvrpn.h ../include/dctypes.h \
 ../include/dcelem.h ../include/dcobject.h ../include/dcdicenu.h \
 ../include/ddicenuz.i ../include/dcstream.h ../include/dctag.h \
 ../include/dcstack.h ../include/dcchrstr.h ../include/dcdebug.h
dcvrsh.o: dcvrsh.cc ../include/dcvrsh.h ../include/dctypes.h \
 ../include/dcelem.h ../include/dcobject.h ../include/dcdicenu.h \
 ../include/ddicenuz.i ../include/dcstream.h ../include/dctag.h \
 ../include/dcstack.h ../include/dcchrstr.h ../include/dcdebug.h
dcvrsl.o: dcvrsl.cc ../include/dcvrsl.h ../include/dctypes.h \
 ../include/dcelem.h ../include/dcobject.h ../include/dcdicenu.h \
 ../include/ddicenuz.i ../include/dcstream.h ../include/dctag.h \
 ../include/dcstack.h ../include/dcdebug.h
dcvrss.o: dcvrss.cc ../include/dcvrss.h ../include/dctypes.h \
 ../include/dcelem.h ../include/dcobject.h ../include/dcdicenu.h \
 ../include/ddicenuz.i ../include/dcstream.h ../include/dctag.h \
 ../include/dcstack.h ../include/dcdebug.h
dcvrst.o: dcvrst.cc ../include/dcvrst.h ../include/dctypes.h \
 ../include/dcelem.h ../include/dcobject.h ../include/dcdicenu.h \
 ../include/ddicenuz.i ../include/dcstream.h ../include/dctag.h \
 ../include/dcstack.h ../include/dcchrstr.h ../include/dcdebug.h
dcvrtm.o: dcvrtm.cc ../include/dcvrtm.h ../include/dctypes.h \
 ../include/dcelem.h ../include/dcobject.h ../include/dcdicenu.h \
 ../include/ddicenuz.i ../include/dcstream.h ../include/dctag.h \
 ../include/dcstack.h ../include/dcbytstr.h ../include/dcdebug.h
dcvrui.o: dcvrui.cc ../include/dcvrui.h ../include/dctypes.h \
 ../include/dcelem.h ../include/dcobject.h ../include/dcdicenu.h \
 ../include/ddicenuz.i ../include/dcstream.h ../include/dctag.h \
 ../include/dcstack.h ../include/dcbytstr.h ../include/dcmodtbl.h \
 ../include/dcdebug.h
dcvrul.o: dcvrul.cc ../include/dcvrul.h ../include/dctypes.h \
 ../include/dcelem.h ../include/dcobject.h ../include/dcdicenu.h \
 ../include/ddicenuz.i ../include/dcstream.h ../include/dctag.h \
 ../include/dcstack.h ../include/dcdebug.h
dcvrulup.o: dcvrulup.cc ../include/dcvrul.h ../include/dctypes.h \
 ../include/dcelem.h ../include/dcobject.h ../include/dcdicenu.h \
 ../include/ddicenuz.i ../include/dcstream.h ../include/dctag.h \
 ../include/dcstack.h ../include/dcvrulup.h ../include/dcdebug.h
dcvrus.o: dcvrus.cc ../include/dcvrus.h ../include/dctypes.h \
 ../include/dcelem.h ../include/dcobject.h ../include/dcdicenu.h \
 ../include/ddicenuz.i ../include/dcstream.h ../include/dctag.h \
 ../include/dcstack.h ../include/dcdebug.h
dcxfer.o: dcxfer.cc ../include/dcxfer.h ../include/dctypes.h \
 ../include/dcdebug.h
