header.o: header.cc config.h util.h pubtypes.h header.h \
  ../../ofstd/include/dcmtk/ofstd/ofaptr.h \
  ../../config/include/dcmtk/config/osconfig.h \
  ../../config/include/dcmtk/config/cfunix.h \
  ../../ofstd/include/dcmtk/ofstd/ofstdinc.h streams.h \
  ../../ofstd/include/dcmtk/ofstd/ofvector.h \
  ../../ofstd/include/dcmtk/ofstd/oftypes.h \
  ../../ofstd/include/dcmtk/ofstd/ofbmanip.h \
  ../../ofstd/include/dcmtk/ofstd/ofcast.h \
  ../../ofstd/include/dcmtk/ofstd/ofdefine.h decodstr.h procline.h \
  clrtrans.h encodstr.h
intrface.o: intrface.cc config.h util.h pubtypes.h intrface.h \
  ../../ofstd/include/dcmtk/ofstd/ofstd.h \
  ../../config/include/dcmtk/config/osconfig.h \
  ../../config/include/dcmtk/config/cfunix.h \
  ../../ofstd/include/dcmtk/ofstd/oflist.h \
  ../../ofstd/include/dcmtk/ofstd/oftypes.h \
  ../../ofstd/include/dcmtk/ofstd/ofcast.h \
  ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
  ../../ofstd/include/dcmtk/ofstd/ofstring.h \
  ../../ofstd/include/dcmtk/ofstd/ofstream.h \
  ../../ofstd/include/dcmtk/ofstd/ofcond.h header.h \
  ../../ofstd/include/dcmtk/ofstd/ofaptr.h streams.h \
  ../../ofstd/include/dcmtk/ofstd/ofvector.h \
  ../../ofstd/include/dcmtk/ofstd/ofbmanip.h \
  ../../ofstd/include/dcmtk/ofstd/ofdefine.h
jpegls.o: jpegls.cc config.h util.h pubtypes.h streams.h \
  ../../ofstd/include/dcmtk/ofstd/ofvector.h \
  ../../config/include/dcmtk/config/osconfig.h \
  ../../config/include/dcmtk/config/cfunix.h \
  ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
  ../../ofstd/include/dcmtk/ofstd/oftypes.h \
  ../../ofstd/include/dcmtk/ofstd/ofbmanip.h \
  ../../ofstd/include/dcmtk/ofstd/ofcast.h \
  ../../ofstd/include/dcmtk/ofstd/ofdefine.h header.h \
  ../../ofstd/include/dcmtk/ofstd/ofaptr.h decodstr.h procline.h \
  clrtrans.h encodstr.h context.h ctxtrmod.h lokuptbl.h lltraits.h \
  deftrait.h scan.h ../../ofstd/include/dcmtk/ofstd/ofmap.h \
  ../../ofstd/include/dcmtk/ofstd/oflist.h \
  ../../ofstd/include/dcmtk/ofstd/oftypes.h
