header.o: header.cc header.h streams.h util.h config.h interface.h \
  decoderstrategy.h processline.h colortransform.h encoderstrategy.h
interface.o: interface.cc interface.h header.h streams.h util.h config.h
jpegls.o: jpegls.cc streams.h util.h config.h interface.h header.h \
  decoderstrategy.h processline.h colortransform.h encoderstrategy.h \
  context.h contextrunmode.h lookuptable.h losslesstraits.h \
  defaulttraits.h scan.h
