dcsignat.o: dcsignat.cc ../../config/include/dcmtk/config/osconfig.h \
 ../include/dcmtk/dcmsign/sidefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h
siautopr.o: siautopr.cc ../../config/include/dcmtk/config/osconfig.h
sibrsapr.o: sibrsapr.cc ../../config/include/dcmtk/config/osconfig.h
sicert.o: sicert.cc ../../config/include/dcmtk/config/osconfig.h
sicertvf.o: sicertvf.cc ../../config/include/dcmtk/config/osconfig.h
sicreapr.o: sicreapr.cc ../../config/include/dcmtk/config/osconfig.h
sidsa.o: sidsa.cc ../../config/include/dcmtk/config/osconfig.h
simaccon.o: simaccon.cc ../../config/include/dcmtk/config/osconfig.h
simd5.o: simd5.cc ../../config/include/dcmtk/config/osconfig.h
sinullpr.o: sinullpr.cc ../../config/include/dcmtk/config/osconfig.h
siprivat.o: siprivat.cc ../../config/include/dcmtk/config/osconfig.h
siripemd.o: siripemd.cc ../../config/include/dcmtk/config/osconfig.h
sirsa.o: sirsa.cc ../../config/include/dcmtk/config/osconfig.h
sisha1.o: sisha1.cc ../../config/include/dcmtk/config/osconfig.h
sisprof.o: sisprof.cc ../../config/include/dcmtk/config/osconfig.h
sitypes.o: sitypes.cc ../../config/include/dcmtk/config/osconfig.h
