dcsignat.o: dcsignat.cc ../../config/include/osconfig.h \
 ../../config/include/cfunix.h ../include/dcsignat.h \
 ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dctypes.h \
 ../../ofstd/include/oftypes.h ../../ofstd/include/ofstdinc.h \
 ../../dcmdata/include/dcvr.h ../../ofstd/include/ofglobal.h \
 ../../ofstd/include/ofthread.h ../include/sitypes.h \
 ../../ofstd/include/ofcond.h ../../ofstd/include/ofstring.h \
 ../../ofstd/include/ofstream.h ../../dcmdata/include/dcstack.h \
 ../../dcmdata/include/dcitem.h ../../ofstd/include/ofconsol.h \
 ../../dcmdata/include/dcobject.h ../../dcmdata/include/dcerror.h \
 ../../dcmdata/include/dctag.h ../../dcmdata/include/dctagkey.h \
 ../../dcmdata/include/dclist.h ../../dcmdata/include/dcvrui.h \
 ../../dcmdata/include/dcbytstr.h ../../dcmdata/include/dcelem.h \
 ../../dcmdata/include/dcpcache.h ../../ofstd/include/oflist.h \
 ../../dcmdata/include/dcvrat.h ../../dcmdata/include/dcvrcs.h \
 ../../dcmdata/include/dcvrdt.h ../../ofstd/include/ofdatime.h \
 ../../ofstd/include/ofdate.h ../../ofstd/include/oftime.h \
 ../../dcmdata/include/dcvrobow.h ../../dcmdata/include/dcvrus.h \
 ../../dcmdata/include/dcuid.h ../../dcmdata/include/dcsequen.h \
 ../../dcmdata/include/dcdeftag.h ../include/sialgo.h \
 ../include/sicert.h ../include/simac.h ../include/simaccon.h \
 ../../dcmdata/include/dcostrmb.h ../../dcmdata/include/dcostrma.h \
 ../include/simd5.h ../include/siprivat.h ../include/siripemd.h \
 ../include/sisha1.h ../include/sisprof.h ../include/sitstamp.h
siautopr.o: siautopr.cc ../../config/include/osconfig.h \
 ../../config/include/cfunix.h ../include/siautopr.h \
 ../include/sibrsapr.h ../include/sisprof.h \
 ../../ofstd/include/oftypes.h ../../dcmdata/include/dcxfer.h \
 ../../dcmdata/include/dctypes.h ../../ofstd/include/ofstdinc.h \
 ../../dcmdata/include/dcvr.h ../../ofstd/include/ofglobal.h \
 ../../ofstd/include/ofthread.h ../include/sitypes.h \
 ../../ofstd/include/ofcond.h ../../ofstd/include/ofstring.h \
 ../../ofstd/include/ofstream.h ../../dcmdata/include/dcdeftag.h \
 ../../dcmdata/include/dctagkey.h
sibrsapr.o: sibrsapr.cc ../../config/include/osconfig.h \
 ../../config/include/cfunix.h ../include/sibrsapr.h \
 ../include/sisprof.h ../../ofstd/include/oftypes.h \
 ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dctypes.h \
 ../../ofstd/include/ofstdinc.h ../../dcmdata/include/dcvr.h \
 ../../ofstd/include/ofglobal.h ../../ofstd/include/ofthread.h \
 ../include/sitypes.h ../../ofstd/include/ofcond.h \
 ../../ofstd/include/ofstring.h ../../ofstd/include/ofstream.h \
 ../../dcmdata/include/dcdeftag.h ../../dcmdata/include/dctagkey.h
sicert.o: sicert.cc ../../config/include/osconfig.h \
 ../../config/include/cfunix.h ../include/sicert.h \
 ../include/sitypes.h ../../ofstd/include/oftypes.h \
 ../../ofstd/include/ofcond.h ../../ofstd/include/ofstring.h \
 ../../ofstd/include/ofstdinc.h ../../ofstd/include/ofstream.h \
 ../../dcmdata/include/dcerror.h ../include/sirsa.h \
 ../include/sialgo.h ../include/sidsa.h \
 ../../dcmdata/include/dcstack.h ../../dcmdata/include/dctypes.h \
 ../../dcmdata/include/dcitem.h ../../ofstd/include/ofconsol.h \
 ../../ofstd/include/ofthread.h ../../dcmdata/include/dcobject.h \
 ../../ofstd/include/ofglobal.h ../../dcmdata/include/dcxfer.h \
 ../../dcmdata/include/dcvr.h ../../dcmdata/include/dctag.h \
 ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dclist.h \
 ../../dcmdata/include/dcvrui.h ../../dcmdata/include/dcbytstr.h \
 ../../dcmdata/include/dcelem.h ../../dcmdata/include/dcpcache.h \
 ../../ofstd/include/oflist.h ../../dcmdata/include/dcvrcs.h \
 ../../dcmdata/include/dcvrobow.h ../../dcmdata/include/dcdeftag.h
sicertvf.o: sicertvf.cc ../../config/include/osconfig.h \
 ../../config/include/cfunix.h ../include/sicert.h \
 ../include/sitypes.h ../../ofstd/include/oftypes.h \
 ../../ofstd/include/ofcond.h ../../ofstd/include/ofstring.h \
 ../../ofstd/include/ofstdinc.h ../../ofstd/include/ofstream.h \
 ../../dcmdata/include/dcerror.h ../include/sicertvf.h
sicreapr.o: sicreapr.cc ../../config/include/osconfig.h \
 ../../config/include/cfunix.h ../include/sicreapr.h \
 ../include/sibrsapr.h ../include/sisprof.h \
 ../../ofstd/include/oftypes.h ../../dcmdata/include/dcxfer.h \
 ../../dcmdata/include/dctypes.h ../../ofstd/include/ofstdinc.h \
 ../../dcmdata/include/dcvr.h ../../ofstd/include/ofglobal.h \
 ../../ofstd/include/ofthread.h ../include/sitypes.h \
 ../../ofstd/include/ofcond.h ../../ofstd/include/ofstring.h \
 ../../ofstd/include/ofstream.h ../../dcmdata/include/dcdeftag.h \
 ../../dcmdata/include/dctagkey.h
sidsa.o: sidsa.cc ../../config/include/osconfig.h \
 ../../config/include/cfunix.h ../include/sidsa.h \
 ../../ofstd/include/oftypes.h ../include/sialgo.h \
 ../include/sitypes.h ../../ofstd/include/ofcond.h \
 ../../ofstd/include/ofstring.h ../../ofstd/include/ofstdinc.h \
 ../../ofstd/include/ofstream.h ../include/sicert.h \
 ../../dcmdata/include/dcerror.h ../include/siprivat.h
simaccon.o: simaccon.cc ../../config/include/osconfig.h \
 ../../config/include/cfunix.h ../include/simaccon.h \
 ../../dcmdata/include/dcostrmb.h ../../dcmdata/include/dcostrma.h \
 ../../ofstd/include/oftypes.h ../../ofstd/include/ofcond.h \
 ../../ofstd/include/ofstring.h ../../ofstd/include/ofstdinc.h \
 ../../ofstd/include/ofstream.h ../../dcmdata/include/dcxfer.h \
 ../../dcmdata/include/dctypes.h ../../dcmdata/include/dcvr.h \
 ../../ofstd/include/ofglobal.h ../../ofstd/include/ofthread.h \
 ../include/sitypes.h ../../dcmdata/include/dcdeftag.h \
 ../../dcmdata/include/dctagkey.h ../include/simac.h \
 ../../dcmdata/include/dcitem.h ../../ofstd/include/ofconsol.h \
 ../../dcmdata/include/dcobject.h ../../dcmdata/include/dcerror.h \
 ../../dcmdata/include/dctag.h ../../dcmdata/include/dclist.h \
 ../../dcmdata/include/dcstack.h ../../dcmdata/include/dcvrui.h \
 ../../dcmdata/include/dcbytstr.h ../../dcmdata/include/dcelem.h \
 ../../dcmdata/include/dcpcache.h ../../ofstd/include/oflist.h \
 ../../dcmdata/include/dcvrat.h
simd5.o: simd5.cc ../../config/include/osconfig.h \
 ../../config/include/cfunix.h ../include/simd5.h ../include/simac.h \
 ../include/sitypes.h ../../ofstd/include/oftypes.h \
 ../../ofstd/include/ofcond.h ../../ofstd/include/ofstring.h \
 ../../ofstd/include/ofstdinc.h ../../ofstd/include/ofstream.h \
 ../../dcmdata/include/dcerror.h
sinullpr.o: sinullpr.cc ../../config/include/osconfig.h \
 ../../config/include/cfunix.h ../include/sinullpr.h \
 ../include/sisprof.h ../../ofstd/include/oftypes.h \
 ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dctypes.h \
 ../../ofstd/include/ofstdinc.h ../../dcmdata/include/dcvr.h \
 ../../ofstd/include/ofglobal.h ../../ofstd/include/ofthread.h \
 ../include/sitypes.h ../../ofstd/include/ofcond.h \
 ../../ofstd/include/ofstring.h ../../ofstd/include/ofstream.h
siprivat.o: siprivat.cc ../../config/include/osconfig.h \
 ../../config/include/cfunix.h ../include/siprivat.h \
 ../../ofstd/include/ofstring.h ../../ofstd/include/ofstdinc.h \
 ../../ofstd/include/ofstream.h ../../ofstd/include/oftypes.h \
 ../include/sitypes.h ../../ofstd/include/ofcond.h ../include/sirsa.h \
 ../include/sialgo.h ../include/sidsa.h ../include/sicert.h \
 ../../dcmdata/include/dcerror.h
siripemd.o: siripemd.cc ../../config/include/osconfig.h \
 ../../config/include/cfunix.h ../include/siripemd.h \
 ../include/simac.h ../include/sitypes.h ../../ofstd/include/oftypes.h \
 ../../ofstd/include/ofcond.h ../../ofstd/include/ofstring.h \
 ../../ofstd/include/ofstdinc.h ../../ofstd/include/ofstream.h \
 ../../dcmdata/include/dcerror.h
sirsa.o: sirsa.cc ../../config/include/osconfig.h \
 ../../config/include/cfunix.h ../include/sirsa.h \
 ../../ofstd/include/oftypes.h ../include/sialgo.h \
 ../include/sitypes.h ../../ofstd/include/ofcond.h \
 ../../ofstd/include/ofstring.h ../../ofstd/include/ofstdinc.h \
 ../../ofstd/include/ofstream.h ../include/sicert.h \
 ../../dcmdata/include/dcerror.h ../include/siprivat.h
sisha1.o: sisha1.cc ../../config/include/osconfig.h \
 ../../config/include/cfunix.h ../include/sisha1.h ../include/simac.h \
 ../include/sitypes.h ../../ofstd/include/oftypes.h \
 ../../ofstd/include/ofcond.h ../../ofstd/include/ofstring.h \
 ../../ofstd/include/ofstdinc.h ../../ofstd/include/ofstream.h \
 ../../dcmdata/include/dcerror.h
sisprof.o: sisprof.cc ../../config/include/osconfig.h \
 ../../config/include/cfunix.h ../include/sisprof.h \
 ../../ofstd/include/oftypes.h ../../dcmdata/include/dcxfer.h \
 ../../dcmdata/include/dctypes.h ../../ofstd/include/ofstdinc.h \
 ../../dcmdata/include/dcvr.h ../../ofstd/include/ofglobal.h \
 ../../ofstd/include/ofthread.h ../include/sitypes.h \
 ../../ofstd/include/ofcond.h ../../ofstd/include/ofstring.h \
 ../../ofstd/include/ofstream.h ../../dcmdata/include/dcitem.h \
 ../../ofstd/include/ofconsol.h ../../dcmdata/include/dcobject.h \
 ../../dcmdata/include/dcerror.h ../../dcmdata/include/dctag.h \
 ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dclist.h \
 ../../dcmdata/include/dcstack.h ../../dcmdata/include/dcvrui.h \
 ../../dcmdata/include/dcbytstr.h ../../dcmdata/include/dcelem.h \
 ../../dcmdata/include/dcpcache.h ../../ofstd/include/oflist.h \
 ../../dcmdata/include/dcvrat.h ../include/simac.h ../include/sialgo.h
sitypes.o: sitypes.cc ../../config/include/osconfig.h \
 ../../config/include/cfunix.h ../include/sitypes.h \
 ../../ofstd/include/oftypes.h ../../ofstd/include/ofcond.h \
 ../../ofstd/include/ofstring.h ../../ofstd/include/ofstdinc.h \
 ../../ofstd/include/ofstream.h ../../dcmdata/include/dcerror.h
