dcsignat.o: dcsignat.cc ../../config/include/dcmtk/config/osconfig.h \
 ../include/dcmtk/dcmsign/dcsignat.h ../include/dcmtk/dcmsign/sitypes.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/dcmsign/sidefine.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcxfer.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctypes.h \
 ../../oflog/include/dcmtk/oflog/oflog.h \
 ../../oflog/include/dcmtk/oflog/logger.h \
 ../../oflog/include/dcmtk/oflog/config.h \
 ../../oflog/include/dcmtk/oflog/config/defines.h \
 ../../oflog/include/dcmtk/oflog/helpers/threadcf.h \
 ../../oflog/include/dcmtk/oflog/loglevel.h \
 ../../oflog/include/dcmtk/oflog/streams.h \
 ../../oflog/include/dcmtk/oflog/tstring.h \
 ../../oflog/include/dcmtk/oflog/spi/apndatch.h \
 ../../oflog/include/dcmtk/oflog/appender.h \
 ../../oflog/include/dcmtk/oflog/layout.h \
 ../../oflog/include/dcmtk/oflog/helpers/lloguser.h \
 ../../oflog/include/dcmtk/oflog/helpers/property.h \
 ../../ofstd/include/dcmtk/ofstd/ofmap.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../../oflog/include/dcmtk/oflog/helpers/timehelp.h \
 ../../oflog/include/dcmtk/oflog/spi/logevent.h \
 ../../oflog/include/dcmtk/oflog/ndc.h \
 ../../oflog/include/dcmtk/oflog/helpers/threads.h \
 ../../oflog/include/dcmtk/oflog/helpers/pointer.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../../ofstd/include/dcmtk/ofstd/ofaptr.h \
 ../../oflog/include/dcmtk/oflog/spi/filter.h \
 ../../oflog/include/dcmtk/oflog/spi/logfact.h \
 ../../oflog/include/dcmtk/oflog/logmacro.h \
 ../../ofstd/include/dcmtk/ofstd/ofconapp.h \
 ../../ofstd/include/dcmtk/ofstd/ofcmdln.h \
 ../../ofstd/include/dcmtk/ofstd/ofconsol.h \
 ../../ofstd/include/dcmtk/ofstd/ofthread.h \
 ../../ofstd/include/dcmtk/ofstd/offile.h \
 ../../ofstd/include/dcmtk/ofstd/ofstd.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdefine.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvr.h \
 ../../ofstd/include/dcmtk/ofstd/ofglobal.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcstack.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcitem.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcobject.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcerror.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctag.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctagkey.h \
 ../../dcmdata/include/dcmtk/dcmdata/dclist.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcpcache.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrat.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcelem.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrcs.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcbytstr.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrdt.h \
 ../../ofstd/include/dcmtk/ofstd/ofdatime.h \
 ../../ofstd/include/dcmtk/ofstd/ofdate.h \
 ../../ofstd/include/dcmtk/ofstd/oftime.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrui.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrobow.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrus.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcuid.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcsequen.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdeftag.h \
 ../include/dcmtk/dcmsign/sialgo.h ../include/dcmtk/dcmsign/sicert.h \
 ../include/dcmtk/dcmsign/simac.h ../include/dcmtk/dcmsign/simaccon.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcostrmb.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcostrma.h \
 ../include/dcmtk/dcmsign/simd5.h ../include/dcmtk/dcmsign/siprivat.h \
 ../include/dcmtk/dcmsign/siripemd.h ../include/dcmtk/dcmsign/sisha1.h \
 ../include/dcmtk/dcmsign/sisprof.h ../include/dcmtk/dcmsign/sitstamp.h
siautopr.o: siautopr.cc ../../config/include/dcmtk/config/osconfig.h \
 ../include/dcmtk/dcmsign/siautopr.h ../include/dcmtk/dcmsign/sibrsapr.h \
 ../include/dcmtk/dcmsign/sisprof.h ../include/dcmtk/dcmsign/sitypes.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/dcmsign/sidefine.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcxfer.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctypes.h \
 ../../oflog/include/dcmtk/oflog/oflog.h \
 ../../oflog/include/dcmtk/oflog/logger.h \
 ../../oflog/include/dcmtk/oflog/config.h \
 ../../oflog/include/dcmtk/oflog/config/defines.h \
 ../../oflog/include/dcmtk/oflog/helpers/threadcf.h \
 ../../oflog/include/dcmtk/oflog/loglevel.h \
 ../../oflog/include/dcmtk/oflog/streams.h \
 ../../oflog/include/dcmtk/oflog/tstring.h \
 ../../oflog/include/dcmtk/oflog/spi/apndatch.h \
 ../../oflog/include/dcmtk/oflog/appender.h \
 ../../oflog/include/dcmtk/oflog/layout.h \
 ../../oflog/include/dcmtk/oflog/helpers/lloguser.h \
 ../../oflog/include/dcmtk/oflog/helpers/property.h \
 ../../ofstd/include/dcmtk/ofstd/ofmap.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../../oflog/include/dcmtk/oflog/helpers/timehelp.h \
 ../../oflog/include/dcmtk/oflog/spi/logevent.h \
 ../../oflog/include/dcmtk/oflog/ndc.h \
 ../../oflog/include/dcmtk/oflog/helpers/threads.h \
 ../../oflog/include/dcmtk/oflog/helpers/pointer.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../../ofstd/include/dcmtk/ofstd/ofaptr.h \
 ../../oflog/include/dcmtk/oflog/spi/filter.h \
 ../../oflog/include/dcmtk/oflog/spi/logfact.h \
 ../../oflog/include/dcmtk/oflog/logmacro.h \
 ../../ofstd/include/dcmtk/ofstd/ofconapp.h \
 ../../ofstd/include/dcmtk/ofstd/ofcmdln.h \
 ../../ofstd/include/dcmtk/ofstd/ofconsol.h \
 ../../ofstd/include/dcmtk/ofstd/ofthread.h \
 ../../ofstd/include/dcmtk/ofstd/offile.h \
 ../../ofstd/include/dcmtk/ofstd/ofstd.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdefine.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvr.h \
 ../../ofstd/include/dcmtk/ofstd/ofglobal.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdeftag.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctagkey.h
sibrsapr.o: sibrsapr.cc ../../config/include/dcmtk/config/osconfig.h \
 ../include/dcmtk/dcmsign/sibrsapr.h ../include/dcmtk/dcmsign/sisprof.h \
 ../include/dcmtk/dcmsign/sitypes.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/dcmsign/sidefine.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcxfer.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctypes.h \
 ../../oflog/include/dcmtk/oflog/oflog.h \
 ../../oflog/include/dcmtk/oflog/logger.h \
 ../../oflog/include/dcmtk/oflog/config.h \
 ../../oflog/include/dcmtk/oflog/config/defines.h \
 ../../oflog/include/dcmtk/oflog/helpers/threadcf.h \
 ../../oflog/include/dcmtk/oflog/loglevel.h \
 ../../oflog/include/dcmtk/oflog/streams.h \
 ../../oflog/include/dcmtk/oflog/tstring.h \
 ../../oflog/include/dcmtk/oflog/spi/apndatch.h \
 ../../oflog/include/dcmtk/oflog/appender.h \
 ../../oflog/include/dcmtk/oflog/layout.h \
 ../../oflog/include/dcmtk/oflog/helpers/lloguser.h \
 ../../oflog/include/dcmtk/oflog/helpers/property.h \
 ../../ofstd/include/dcmtk/ofstd/ofmap.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../../oflog/include/dcmtk/oflog/helpers/timehelp.h \
 ../../oflog/include/dcmtk/oflog/spi/logevent.h \
 ../../oflog/include/dcmtk/oflog/ndc.h \
 ../../oflog/include/dcmtk/oflog/helpers/threads.h \
 ../../oflog/include/dcmtk/oflog/helpers/pointer.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../../ofstd/include/dcmtk/ofstd/ofaptr.h \
 ../../oflog/include/dcmtk/oflog/spi/filter.h \
 ../../oflog/include/dcmtk/oflog/spi/logfact.h \
 ../../oflog/include/dcmtk/oflog/logmacro.h \
 ../../ofstd/include/dcmtk/ofstd/ofconapp.h \
 ../../ofstd/include/dcmtk/ofstd/ofcmdln.h \
 ../../ofstd/include/dcmtk/ofstd/ofconsol.h \
 ../../ofstd/include/dcmtk/ofstd/ofthread.h \
 ../../ofstd/include/dcmtk/ofstd/offile.h \
 ../../ofstd/include/dcmtk/ofstd/ofstd.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdefine.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvr.h \
 ../../ofstd/include/dcmtk/ofstd/ofglobal.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdeftag.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctagkey.h
sicert.o: sicert.cc ../../config/include/dcmtk/config/osconfig.h \
 ../include/dcmtk/dcmsign/sicert.h ../include/dcmtk/dcmsign/sitypes.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/dcmsign/sidefine.h ../include/dcmtk/dcmsign/sirsa.h \
 ../include/dcmtk/dcmsign/sialgo.h ../include/dcmtk/dcmsign/sidsa.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcstack.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdefine.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcitem.h \
 ../../ofstd/include/dcmtk/ofstd/offile.h \
 ../../ofstd/include/dcmtk/ofstd/ofstd.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctypes.h \
 ../../oflog/include/dcmtk/oflog/oflog.h \
 ../../oflog/include/dcmtk/oflog/logger.h \
 ../../oflog/include/dcmtk/oflog/config.h \
 ../../oflog/include/dcmtk/oflog/config/defines.h \
 ../../oflog/include/dcmtk/oflog/helpers/threadcf.h \
 ../../oflog/include/dcmtk/oflog/loglevel.h \
 ../../oflog/include/dcmtk/oflog/streams.h \
 ../../oflog/include/dcmtk/oflog/tstring.h \
 ../../oflog/include/dcmtk/oflog/spi/apndatch.h \
 ../../oflog/include/dcmtk/oflog/appender.h \
 ../../oflog/include/dcmtk/oflog/layout.h \
 ../../oflog/include/dcmtk/oflog/helpers/lloguser.h \
 ../../oflog/include/dcmtk/oflog/helpers/property.h \
 ../../ofstd/include/dcmtk/ofstd/ofmap.h \
 ../../oflog/include/dcmtk/oflog/helpers/timehelp.h \
 ../../oflog/include/dcmtk/oflog/spi/logevent.h \
 ../../oflog/include/dcmtk/oflog/ndc.h \
 ../../oflog/include/dcmtk/oflog/helpers/threads.h \
 ../../oflog/include/dcmtk/oflog/helpers/pointer.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../../ofstd/include/dcmtk/ofstd/ofaptr.h \
 ../../oflog/include/dcmtk/oflog/spi/filter.h \
 ../../oflog/include/dcmtk/oflog/spi/logfact.h \
 ../../oflog/include/dcmtk/oflog/logmacro.h \
 ../../ofstd/include/dcmtk/ofstd/ofconapp.h \
 ../../ofstd/include/dcmtk/ofstd/ofcmdln.h \
 ../../ofstd/include/dcmtk/ofstd/ofconsol.h \
 ../../ofstd/include/dcmtk/ofstd/ofthread.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcobject.h \
 ../../ofstd/include/dcmtk/ofstd/ofglobal.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcerror.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcxfer.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvr.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctag.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctagkey.h \
 ../../dcmdata/include/dcmtk/dcmdata/dclist.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcpcache.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrcs.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcbytstr.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcelem.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrobow.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdeftag.h
sicertvf.o: sicertvf.cc ../../config/include/dcmtk/config/osconfig.h \
 ../include/dcmtk/dcmsign/sicert.h ../include/dcmtk/dcmsign/sitypes.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/dcmsign/sidefine.h ../include/dcmtk/dcmsign/sicertvf.h
sicreapr.o: sicreapr.cc ../../config/include/dcmtk/config/osconfig.h \
 ../include/dcmtk/dcmsign/sicreapr.h ../include/dcmtk/dcmsign/sibrsapr.h \
 ../include/dcmtk/dcmsign/sisprof.h ../include/dcmtk/dcmsign/sitypes.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/dcmsign/sidefine.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcxfer.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctypes.h \
 ../../oflog/include/dcmtk/oflog/oflog.h \
 ../../oflog/include/dcmtk/oflog/logger.h \
 ../../oflog/include/dcmtk/oflog/config.h \
 ../../oflog/include/dcmtk/oflog/config/defines.h \
 ../../oflog/include/dcmtk/oflog/helpers/threadcf.h \
 ../../oflog/include/dcmtk/oflog/loglevel.h \
 ../../oflog/include/dcmtk/oflog/streams.h \
 ../../oflog/include/dcmtk/oflog/tstring.h \
 ../../oflog/include/dcmtk/oflog/spi/apndatch.h \
 ../../oflog/include/dcmtk/oflog/appender.h \
 ../../oflog/include/dcmtk/oflog/layout.h \
 ../../oflog/include/dcmtk/oflog/helpers/lloguser.h \
 ../../oflog/include/dcmtk/oflog/helpers/property.h \
 ../../ofstd/include/dcmtk/ofstd/ofmap.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../../oflog/include/dcmtk/oflog/helpers/timehelp.h \
 ../../oflog/include/dcmtk/oflog/spi/logevent.h \
 ../../oflog/include/dcmtk/oflog/ndc.h \
 ../../oflog/include/dcmtk/oflog/helpers/threads.h \
 ../../oflog/include/dcmtk/oflog/helpers/pointer.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../../ofstd/include/dcmtk/ofstd/ofaptr.h \
 ../../oflog/include/dcmtk/oflog/spi/filter.h \
 ../../oflog/include/dcmtk/oflog/spi/logfact.h \
 ../../oflog/include/dcmtk/oflog/logmacro.h \
 ../../ofstd/include/dcmtk/ofstd/ofconapp.h \
 ../../ofstd/include/dcmtk/ofstd/ofcmdln.h \
 ../../ofstd/include/dcmtk/ofstd/ofconsol.h \
 ../../ofstd/include/dcmtk/ofstd/ofthread.h \
 ../../ofstd/include/dcmtk/ofstd/offile.h \
 ../../ofstd/include/dcmtk/ofstd/ofstd.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdefine.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvr.h \
 ../../ofstd/include/dcmtk/ofstd/ofglobal.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdeftag.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctagkey.h
sidsa.o: sidsa.cc ../../config/include/dcmtk/config/osconfig.h \
 ../include/dcmtk/dcmsign/sidsa.h ../include/dcmtk/dcmsign/sialgo.h \
 ../include/dcmtk/dcmsign/sitypes.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/dcmsign/sidefine.h ../include/dcmtk/dcmsign/sicert.h \
 ../include/dcmtk/dcmsign/siprivat.h
simaccon.o: simaccon.cc ../../config/include/dcmtk/config/osconfig.h \
 ../include/dcmtk/dcmsign/simaccon.h ../include/dcmtk/dcmsign/sitypes.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/dcmsign/sidefine.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcostrmb.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcostrma.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcxfer.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctypes.h \
 ../../oflog/include/dcmtk/oflog/oflog.h \
 ../../oflog/include/dcmtk/oflog/logger.h \
 ../../oflog/include/dcmtk/oflog/config.h \
 ../../oflog/include/dcmtk/oflog/config/defines.h \
 ../../oflog/include/dcmtk/oflog/helpers/threadcf.h \
 ../../oflog/include/dcmtk/oflog/loglevel.h \
 ../../oflog/include/dcmtk/oflog/streams.h \
 ../../oflog/include/dcmtk/oflog/tstring.h \
 ../../oflog/include/dcmtk/oflog/spi/apndatch.h \
 ../../oflog/include/dcmtk/oflog/appender.h \
 ../../oflog/include/dcmtk/oflog/layout.h \
 ../../oflog/include/dcmtk/oflog/helpers/lloguser.h \
 ../../oflog/include/dcmtk/oflog/helpers/property.h \
 ../../ofstd/include/dcmtk/ofstd/ofmap.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../../oflog/include/dcmtk/oflog/helpers/timehelp.h \
 ../../oflog/include/dcmtk/oflog/spi/logevent.h \
 ../../oflog/include/dcmtk/oflog/ndc.h \
 ../../oflog/include/dcmtk/oflog/helpers/threads.h \
 ../../oflog/include/dcmtk/oflog/helpers/pointer.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../../ofstd/include/dcmtk/ofstd/ofaptr.h \
 ../../oflog/include/dcmtk/oflog/spi/filter.h \
 ../../oflog/include/dcmtk/oflog/spi/logfact.h \
 ../../oflog/include/dcmtk/oflog/logmacro.h \
 ../../ofstd/include/dcmtk/ofstd/ofconapp.h \
 ../../ofstd/include/dcmtk/ofstd/ofcmdln.h \
 ../../ofstd/include/dcmtk/ofstd/ofconsol.h \
 ../../ofstd/include/dcmtk/ofstd/ofthread.h \
 ../../ofstd/include/dcmtk/ofstd/offile.h \
 ../../ofstd/include/dcmtk/ofstd/ofstd.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdefine.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvr.h \
 ../../ofstd/include/dcmtk/ofstd/ofglobal.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdeftag.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctagkey.h \
 ../include/dcmtk/dcmsign/simac.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcitem.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcobject.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcerror.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctag.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcstack.h \
 ../../dcmdata/include/dcmtk/dcmdata/dclist.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcpcache.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrat.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcelem.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcwcache.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcfcache.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcistrma.h
simd5.o: simd5.cc ../../config/include/dcmtk/config/osconfig.h \
 ../include/dcmtk/dcmsign/simd5.h ../include/dcmtk/dcmsign/simac.h \
 ../include/dcmtk/dcmsign/sitypes.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/dcmsign/sidefine.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcerror.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdefine.h
sinullpr.o: sinullpr.cc ../../config/include/dcmtk/config/osconfig.h \
 ../include/dcmtk/dcmsign/sinullpr.h ../include/dcmtk/dcmsign/sisprof.h \
 ../include/dcmtk/dcmsign/sitypes.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/dcmsign/sidefine.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcxfer.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctypes.h \
 ../../oflog/include/dcmtk/oflog/oflog.h \
 ../../oflog/include/dcmtk/oflog/logger.h \
 ../../oflog/include/dcmtk/oflog/config.h \
 ../../oflog/include/dcmtk/oflog/config/defines.h \
 ../../oflog/include/dcmtk/oflog/helpers/threadcf.h \
 ../../oflog/include/dcmtk/oflog/loglevel.h \
 ../../oflog/include/dcmtk/oflog/streams.h \
 ../../oflog/include/dcmtk/oflog/tstring.h \
 ../../oflog/include/dcmtk/oflog/spi/apndatch.h \
 ../../oflog/include/dcmtk/oflog/appender.h \
 ../../oflog/include/dcmtk/oflog/layout.h \
 ../../oflog/include/dcmtk/oflog/helpers/lloguser.h \
 ../../oflog/include/dcmtk/oflog/helpers/property.h \
 ../../ofstd/include/dcmtk/ofstd/ofmap.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../../oflog/include/dcmtk/oflog/helpers/timehelp.h \
 ../../oflog/include/dcmtk/oflog/spi/logevent.h \
 ../../oflog/include/dcmtk/oflog/ndc.h \
 ../../oflog/include/dcmtk/oflog/helpers/threads.h \
 ../../oflog/include/dcmtk/oflog/helpers/pointer.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../../ofstd/include/dcmtk/ofstd/ofaptr.h \
 ../../oflog/include/dcmtk/oflog/spi/filter.h \
 ../../oflog/include/dcmtk/oflog/spi/logfact.h \
 ../../oflog/include/dcmtk/oflog/logmacro.h \
 ../../ofstd/include/dcmtk/ofstd/ofconapp.h \
 ../../ofstd/include/dcmtk/ofstd/ofcmdln.h \
 ../../ofstd/include/dcmtk/ofstd/ofconsol.h \
 ../../ofstd/include/dcmtk/ofstd/ofthread.h \
 ../../ofstd/include/dcmtk/ofstd/offile.h \
 ../../ofstd/include/dcmtk/ofstd/ofstd.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdefine.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvr.h \
 ../../ofstd/include/dcmtk/ofstd/ofglobal.h
siprivat.o: siprivat.cc ../../config/include/dcmtk/config/osconfig.h \
 ../include/dcmtk/dcmsign/siprivat.h ../include/dcmtk/dcmsign/sitypes.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/dcmsign/sidefine.h ../include/dcmtk/dcmsign/sirsa.h \
 ../include/dcmtk/dcmsign/sialgo.h ../include/dcmtk/dcmsign/sidsa.h \
 ../include/dcmtk/dcmsign/sicert.h
siripemd.o: siripemd.cc ../../config/include/dcmtk/config/osconfig.h \
 ../include/dcmtk/dcmsign/siripemd.h ../include/dcmtk/dcmsign/simac.h \
 ../include/dcmtk/dcmsign/sitypes.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/dcmsign/sidefine.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcerror.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdefine.h
sirsa.o: sirsa.cc ../../config/include/dcmtk/config/osconfig.h \
 ../include/dcmtk/dcmsign/sirsa.h ../include/dcmtk/dcmsign/sialgo.h \
 ../include/dcmtk/dcmsign/sitypes.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/dcmsign/sidefine.h ../include/dcmtk/dcmsign/sicert.h \
 ../include/dcmtk/dcmsign/siprivat.h
sisha1.o: sisha1.cc ../../config/include/dcmtk/config/osconfig.h \
 ../include/dcmtk/dcmsign/sisha1.h ../include/dcmtk/dcmsign/simac.h \
 ../include/dcmtk/dcmsign/sitypes.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/dcmsign/sidefine.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcerror.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdefine.h
sisprof.o: sisprof.cc ../../config/include/dcmtk/config/osconfig.h \
 ../include/dcmtk/dcmsign/sisprof.h ../include/dcmtk/dcmsign/sitypes.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/dcmsign/sidefine.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcxfer.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctypes.h \
 ../../oflog/include/dcmtk/oflog/oflog.h \
 ../../oflog/include/dcmtk/oflog/logger.h \
 ../../oflog/include/dcmtk/oflog/config.h \
 ../../oflog/include/dcmtk/oflog/config/defines.h \
 ../../oflog/include/dcmtk/oflog/helpers/threadcf.h \
 ../../oflog/include/dcmtk/oflog/loglevel.h \
 ../../oflog/include/dcmtk/oflog/streams.h \
 ../../oflog/include/dcmtk/oflog/tstring.h \
 ../../oflog/include/dcmtk/oflog/spi/apndatch.h \
 ../../oflog/include/dcmtk/oflog/appender.h \
 ../../oflog/include/dcmtk/oflog/layout.h \
 ../../oflog/include/dcmtk/oflog/helpers/lloguser.h \
 ../../oflog/include/dcmtk/oflog/helpers/property.h \
 ../../ofstd/include/dcmtk/ofstd/ofmap.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../../oflog/include/dcmtk/oflog/helpers/timehelp.h \
 ../../oflog/include/dcmtk/oflog/spi/logevent.h \
 ../../oflog/include/dcmtk/oflog/ndc.h \
 ../../oflog/include/dcmtk/oflog/helpers/threads.h \
 ../../oflog/include/dcmtk/oflog/helpers/pointer.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../../ofstd/include/dcmtk/ofstd/ofaptr.h \
 ../../oflog/include/dcmtk/oflog/spi/filter.h \
 ../../oflog/include/dcmtk/oflog/spi/logfact.h \
 ../../oflog/include/dcmtk/oflog/logmacro.h \
 ../../ofstd/include/dcmtk/ofstd/ofconapp.h \
 ../../ofstd/include/dcmtk/ofstd/ofcmdln.h \
 ../../ofstd/include/dcmtk/ofstd/ofconsol.h \
 ../../ofstd/include/dcmtk/ofstd/ofthread.h \
 ../../ofstd/include/dcmtk/ofstd/offile.h \
 ../../ofstd/include/dcmtk/ofstd/ofstd.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdefine.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvr.h \
 ../../ofstd/include/dcmtk/ofstd/ofglobal.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcitem.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcobject.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcerror.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctag.h \
 ../../dcmdata/include/dcmtk/dcmdata/dctagkey.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcstack.h \
 ../../dcmdata/include/dcmtk/dcmdata/dclist.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcpcache.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcvrat.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcelem.h \
 ../include/dcmtk/dcmsign/simac.h ../include/dcmtk/dcmsign/sialgo.h
sitypes.o: sitypes.cc ../../config/include/dcmtk/config/osconfig.h \
 ../include/dcmtk/dcmsign/sitypes.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/dcmsign/sidefine.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcerror.h \
 ../../dcmdata/include/dcmtk/dcmdata/dcdefine.h
