wlds.o: wlds.cc ../../config/include/osconfig.h \
 ../../dcmnet/include/dicom.h ../../dcmnet/include/cond.h \
 ../../ofstd/include/ofconsol.h ../../ofstd/include/ofstream.h \
 ../../ofstd/include/ofthread.h ../../ofstd/include/oftypes.h \
 ../../dcmdata/include/dcerror.h ../../ofstd/include/ofcond.h \
 ../../ofstd/include/ofstring.h ../../dcmnet/include/dcompat.h \
 ../../ofstd/include/ofbmanip.h ../../dcmdata/include/dctypes.h \
 ../../dcmdata/include/dcuid.h ../include/wltypdef.h \
 ../../dcmdata/include/dcdatset.h ../../dcmdata/include/dcitem.h \
 ../../dcmdata/include/dcobject.h ../../ofstd/include/ofglobal.h \
 ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
 ../../dcmdata/include/dcstream.h ../../dcmdata/include/dctag.h \
 ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dcdicent.h \
 ../../dcmdata/include/dclist.h ../../dcmdata/include/dcstack.h \
 ../../dcmdata/include/dcvrui.h ../../dcmdata/include/dcbytstr.h \
 ../../dcmdata/include/dcelem.h ../../dcmdata/include/dcvrat.h \
 ../../dcmdata/include/dcvrlo.h ../../dcmdata/include/dcchrstr.h \
 ../../dcmdata/include/dcdict.h ../../dcmdata/include/dchashdi.h \
 ../../ofstd/include/oflist.h ../../dcmdata/include/dcdeftag.h \
 ../../dcmdata/include/dcsequen.h ../include/wlds.h
wlmactmg.o: wlmactmg.cc ../../config/include/osconfig.h \
 ../../ofstd/include/ofcond.h ../../ofstd/include/oftypes.h \
 ../../ofstd/include/ofstring.h ../../ofstd/include/ofstream.h \
 ../../dcmnet/include/dicom.h ../../dcmnet/include/cond.h \
 ../../ofstd/include/ofconsol.h ../../ofstd/include/ofthread.h \
 ../../dcmdata/include/dcerror.h ../../dcmnet/include/dcompat.h \
 ../../ofstd/include/ofbmanip.h ../../dcmdata/include/dctypes.h \
 ../../dcmdata/include/dcuid.h ../include/wltypdef.h \
 ../../dcmdata/include/dcdatset.h ../../dcmdata/include/dcitem.h \
 ../../dcmdata/include/dcobject.h ../../ofstd/include/ofglobal.h \
 ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
 ../../dcmdata/include/dcstream.h ../../dcmdata/include/dctag.h \
 ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dcdicent.h \
 ../../dcmdata/include/dclist.h ../../dcmdata/include/dcstack.h \
 ../../dcmdata/include/dcvrui.h ../../dcmdata/include/dcbytstr.h \
 ../../dcmdata/include/dcelem.h ../../dcmdata/include/dcvrat.h \
 ../../dcmdata/include/dcvrlo.h ../../dcmdata/include/dcchrstr.h \
 ../../dcmdata/include/dcdict.h ../../dcmdata/include/dchashdi.h \
 ../../ofstd/include/oflist.h ../../dcmdata/include/dcdeftag.h \
 ../include/wlds.h ../../ofstd/include/ofcmdln.h \
 ../../dcmnet/include/assoc.h ../../dcmnet/include/lst.h \
 ../../dcmnet/include/dul.h ../../dcmnet/include/extneg.h \
 ../../dcmnet/include/dimse.h ../../dcmnet/include/diutil.h \
 ../include/wlmactmg.h
