wldbim.o: wldbim.cc ../../config/include/osconfig.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/oftypes.h ../../dcmnet/include/dicom.h \
  ../../dcmnet/include/cond.h ../../dcmdata/include/dcerror.h \
  ../../ofstd/include/ofcond.h ../../ofstd/include/ofstring.h \
  ../../dcmnet/include/dcompat.h ../../ofstd/include/ofbmanip.h \
  ../../dcmdata/include/dctypes.h ../../dcmdata/include/dcuid.h \
  ../include/wltypdef.h ../../dcmdata/include/dctk.h \
  ../../dcmdata/include/dcswap.h ../../dcmdata/include/dcxfer.h \
  ../../dcmdata/include/dcvr.h ../../ofstd/include/ofglobal.h \
  ../../dcmdata/include/dcstream.h ../../dcmdata/include/dcvm.h \
  ../../dcmdata/include/dcdefine.h ../../dcmdata/include/dcdebug.h \
  ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dctag.h \
  ../../dcmdata/include/dcdicent.h ../../dcmdata/include/dchashdi.h \
  ../../ofstd/include/oflist.h ../../dcmdata/include/dcdict.h \
  ../../dcmdata/include/dcdeftag.h ../../dcmdata/include/dcobject.h \
  ../../dcmdata/include/dclist.h ../../dcmdata/include/dcstack.h \
  ../../dcmdata/include/dcelem.h ../../dcmdata/include/dcitem.h \
  ../../dcmdata/include/dcvrui.h ../../dcmdata/include/dcbytstr.h \
  ../../dcmdata/include/dcmetinf.h ../../dcmdata/include/dcdatset.h \
  ../../dcmdata/include/dcsequen.h ../../dcmdata/include/dcfilefo.h \
  ../../dcmdata/include/dcdicdir.h ../../dcmdata/include/dcdirrec.h \
  ../../dcmdata/include/dcvrulup.h ../../dcmdata/include/dcvrul.h \
  ../../dcmdata/include/dcpixseq.h ../../dcmdata/include/dcvrae.h \
  ../../dcmdata/include/dcvras.h ../../dcmdata/include/dcvrcs.h \
  ../../dcmdata/include/dcvrda.h ../../dcmdata/include/dcvrds.h \
  ../../dcmdata/include/dcvrdt.h ../../dcmdata/include/dcvris.h \
  ../../dcmdata/include/dcvrtm.h ../../dcmdata/include/dcchrstr.h \
  ../../dcmdata/include/dcvrlo.h ../../dcmdata/include/dcvrlt.h \
  ../../dcmdata/include/dcvrpn.h ../../dcmdata/include/dcvrsh.h \
  ../../dcmdata/include/dcvrst.h ../../dcmdata/include/dcvrut.h \
  ../../dcmdata/include/dcvrobow.h ../../dcmdata/include/dcpixel.h \
  ../../dcmdata/include/dcvrpobw.h ../../dcmdata/include/dcovlay.h \
  ../../dcmdata/include/dcvrat.h ../../dcmdata/include/dcvrss.h \
  ../../dcmdata/include/dcvrus.h ../../dcmdata/include/dcvrsl.h \
  ../../dcmdata/include/dcvrfl.h ../../dcmdata/include/dcvrfd.h \
  ../../dcmdata/include/cmdlnarg.h ../include/wldbim.h
wlds.o: wlds.cc ../../config/include/osconfig.h \
  ../../dcmnet/include/dicom.h ../../dcmnet/include/cond.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/oftypes.h ../../dcmdata/include/dcerror.h \
  ../../ofstd/include/ofcond.h ../../ofstd/include/ofstring.h \
  ../../dcmnet/include/dcompat.h ../../ofstd/include/ofbmanip.h \
  ../../dcmdata/include/dctypes.h ../../dcmdata/include/dcuid.h \
  ../include/wltypdef.h ../../dcmdata/include/dcdatset.h \
  ../../dcmdata/include/dcitem.h ../../dcmdata/include/dcobject.h \
  ../../ofstd/include/ofglobal.h ../../dcmdata/include/dcxfer.h \
  ../../dcmdata/include/dcvr.h ../../dcmdata/include/dcstream.h \
  ../../dcmdata/include/dctag.h ../../dcmdata/include/dctagkey.h \
  ../../dcmdata/include/dcdicent.h ../../dcmdata/include/dclist.h \
  ../../dcmdata/include/dcstack.h ../../dcmdata/include/dcvrui.h \
  ../../dcmdata/include/dcbytstr.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcvrat.h ../../dcmdata/include/dcvrlo.h \
  ../../dcmdata/include/dcchrstr.h ../../dcmdata/include/dcdict.h \
  ../../dcmdata/include/dchashdi.h ../../ofstd/include/oflist.h \
  ../../dcmdata/include/dcdeftag.h ../../dcmdata/include/dcsequen.h \
  ../include/wlds.h
wldsdb.o: wldsdb.cc ../../config/include/osconfig.h \
  ../../dcmnet/include/dicom.h ../../dcmnet/include/cond.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/oftypes.h ../../dcmdata/include/dcerror.h \
  ../../ofstd/include/ofcond.h ../../ofstd/include/ofstring.h \
  ../../dcmnet/include/dcompat.h ../../ofstd/include/ofbmanip.h \
  ../../dcmdata/include/dctypes.h ../../dcmdata/include/dcuid.h \
  ../include/wltypdef.h ../../dcmdata/include/dcdatset.h \
  ../../dcmdata/include/dcitem.h ../../dcmdata/include/dcobject.h \
  ../../ofstd/include/ofglobal.h ../../dcmdata/include/dcxfer.h \
  ../../dcmdata/include/dcvr.h ../../dcmdata/include/dcstream.h \
  ../../dcmdata/include/dctag.h ../../dcmdata/include/dctagkey.h \
  ../../dcmdata/include/dcdicent.h ../../dcmdata/include/dclist.h \
  ../../dcmdata/include/dcstack.h ../../dcmdata/include/dcvrui.h \
  ../../dcmdata/include/dcbytstr.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcdeftag.h ../../dcmdata/include/dcsequen.h \
  ../../dcmdata/include/dcvrat.h ../../dcmdata/include/dcvrlo.h \
  ../../dcmdata/include/dcchrstr.h ../include/wldbim.h ../include/wlds.h \
  ../include/wldsdb.h
wldsfs.o: wldsfs.cc ../../config/include/osconfig.h \
  ../../dcmnet/include/dicom.h ../../dcmnet/include/cond.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/oftypes.h ../../dcmdata/include/dcerror.h \
  ../../ofstd/include/ofcond.h ../../ofstd/include/ofstring.h \
  ../../dcmnet/include/dcompat.h ../../ofstd/include/ofbmanip.h \
  ../../dcmdata/include/dctypes.h ../../dcmdata/include/dcuid.h \
  ../include/wltypdef.h ../../dcmdata/include/dcdatset.h \
  ../../dcmdata/include/dcitem.h ../../dcmdata/include/dcobject.h \
  ../../ofstd/include/ofglobal.h ../../dcmdata/include/dcxfer.h \
  ../../dcmdata/include/dcvr.h ../../dcmdata/include/dcstream.h \
  ../../dcmdata/include/dctag.h ../../dcmdata/include/dctagkey.h \
  ../../dcmdata/include/dcdicent.h ../../dcmdata/include/dclist.h \
  ../../dcmdata/include/dcstack.h ../../dcmdata/include/dcvrui.h \
  ../../dcmdata/include/dcbytstr.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcvrat.h ../../dcmdata/include/dcvrlo.h \
  ../../dcmdata/include/dcchrstr.h ../../dcmdata/include/dcdeftag.h \
  ../../dcmdata/include/dcfilefo.h ../../dcmdata/include/dcsequen.h \
  ../../dcmnet/include/diutil.h ../../dcmnet/include/dimse.h \
  ../../dcmnet/include/lst.h ../../ofstd/include/oflist.h \
  ../../dcmnet/include/dul.h ../../dcmnet/include/extneg.h \
  ../../dcmnet/include/assoc.h ../../dcmdata/include/dcvm.h \
  ../include/wlds.h ../include/wldsfs.h
wlmactmg.o: wlmactmg.cc ../../config/include/osconfig.h \
  ../../dcmnet/include/dicom.h ../../dcmnet/include/cond.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/oftypes.h ../../dcmdata/include/dcerror.h \
  ../../ofstd/include/ofcond.h ../../ofstd/include/ofstring.h \
  ../../dcmnet/include/dcompat.h ../../ofstd/include/ofbmanip.h \
  ../../dcmdata/include/dctypes.h ../../dcmdata/include/dcuid.h \
  ../include/wltypdef.h ../../dcmdata/include/dcdatset.h \
  ../../dcmdata/include/dcitem.h ../../dcmdata/include/dcobject.h \
  ../../ofstd/include/ofglobal.h ../../dcmdata/include/dcxfer.h \
  ../../dcmdata/include/dcvr.h ../../dcmdata/include/dcstream.h \
  ../../dcmdata/include/dctag.h ../../dcmdata/include/dctagkey.h \
  ../../dcmdata/include/dcdicent.h ../../dcmdata/include/dclist.h \
  ../../dcmdata/include/dcstack.h ../../dcmdata/include/dcvrui.h \
  ../../dcmdata/include/dcbytstr.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcvrat.h ../../dcmdata/include/dcvrlo.h \
  ../../dcmdata/include/dcchrstr.h ../../dcmdata/include/dcdict.h \
  ../../dcmdata/include/dchashdi.h ../../ofstd/include/oflist.h \
  ../../dcmdata/include/dcdeftag.h ../../dcmdata/include/dcsequen.h \
  ../include/wlds.h ../../ofstd/include/ofcmdln.h \
  ../../dcmnet/include/assoc.h ../../dcmnet/include/lst.h \
  ../../dcmnet/include/dul.h ../../dcmnet/include/extneg.h \
  ../../dcmnet/include/dimse.h ../include/wldsdb.h ../include/wldsfs.h \
  ../../dcmnet/include/diutil.h ../include/wlmactmg.h
