apndimpl.o: apndimpl.cc ../include/dcmtk/oflog/appender.h \
 ../include/dcmtk/oflog/config.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h \
 ../include/dcmtk/oflog/layout.h ../include/dcmtk/oflog/loglevel.h \
 ../include/dcmtk/oflog/streams.h ../include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/oflog/helpers/lloguser.h \
 ../include/dcmtk/oflog/helpers/property.h \
 ../../ofstd/include/dcmtk/ofstd/ofmap.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../include/dcmtk/oflog/helpers/timehelp.h \
 ../include/dcmtk/oflog/spi/logevent.h ../include/dcmtk/oflog/ndc.h \
 ../include/dcmtk/oflog/helpers/threads.h \
 ../include/dcmtk/oflog/helpers/pointer.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../../ofstd/include/dcmtk/ofstd/ofaptr.h \
 ../include/dcmtk/oflog/spi/filter.h \
 ../include/dcmtk/oflog/helpers/apndimpl.h \
 ../include/dcmtk/oflog/spi/apndatch.h \
 ../include/dcmtk/oflog/helpers/loglog.h
appender.o: appender.cc ../include/dcmtk/oflog/appender.h \
 ../include/dcmtk/oflog/config.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h \
 ../include/dcmtk/oflog/layout.h ../include/dcmtk/oflog/loglevel.h \
 ../include/dcmtk/oflog/streams.h ../include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/oflog/helpers/lloguser.h \
 ../include/dcmtk/oflog/helpers/property.h \
 ../../ofstd/include/dcmtk/ofstd/ofmap.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../include/dcmtk/oflog/helpers/timehelp.h \
 ../include/dcmtk/oflog/spi/logevent.h ../include/dcmtk/oflog/ndc.h \
 ../include/dcmtk/oflog/helpers/threads.h \
 ../include/dcmtk/oflog/helpers/pointer.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../../ofstd/include/dcmtk/ofstd/ofaptr.h \
 ../include/dcmtk/oflog/spi/filter.h \
 ../include/dcmtk/oflog/helpers/loglog.h \
 ../include/dcmtk/oflog/helpers/strhelp.h \
 ../include/dcmtk/oflog/spi/factory.h ../include/dcmtk/oflog/spi/objreg.h
config.o: config.cc ../include/dcmtk/oflog/configrt.h \
 ../include/dcmtk/oflog/config.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h \
 ../include/dcmtk/oflog/appender.h ../include/dcmtk/oflog/layout.h \
 ../include/dcmtk/oflog/loglevel.h ../include/dcmtk/oflog/streams.h \
 ../include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/oflog/helpers/lloguser.h \
 ../include/dcmtk/oflog/helpers/property.h \
 ../../ofstd/include/dcmtk/ofstd/ofmap.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../include/dcmtk/oflog/helpers/timehelp.h \
 ../include/dcmtk/oflog/spi/logevent.h ../include/dcmtk/oflog/ndc.h \
 ../include/dcmtk/oflog/helpers/threads.h \
 ../include/dcmtk/oflog/helpers/pointer.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../../ofstd/include/dcmtk/ofstd/ofaptr.h \
 ../include/dcmtk/oflog/spi/filter.h ../include/dcmtk/oflog/hierarchy.h \
 ../include/dcmtk/oflog/logger.h ../include/dcmtk/oflog/spi/apndatch.h \
 ../include/dcmtk/oflog/spi/logfact.h ../include/dcmtk/oflog/logmacro.h \
 ../include/dcmtk/oflog/hierlock.h \
 ../include/dcmtk/oflog/helpers/loglog.h \
 ../include/dcmtk/oflog/helpers/sleep.h \
 ../include/dcmtk/oflog/helpers/strhelp.h \
 ../include/dcmtk/oflog/helpers/syncprims.h \
 ../include/dcmtk/oflog/helpers/syncppth.h \
 ../include/dcmtk/oflog/spi/factory.h ../include/dcmtk/oflog/spi/objreg.h \
 ../include/dcmtk/oflog/spi/logimpl.h \
 ../include/dcmtk/oflog/helpers/apndimpl.h
consap.o: consap.cc ../include/dcmtk/oflog/layout.h \
 ../include/dcmtk/oflog/config.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h \
 ../include/dcmtk/oflog/loglevel.h ../include/dcmtk/oflog/streams.h \
 ../include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/oflog/helpers/lloguser.h \
 ../include/dcmtk/oflog/helpers/property.h \
 ../../ofstd/include/dcmtk/ofstd/ofmap.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../include/dcmtk/oflog/helpers/timehelp.h \
 ../include/dcmtk/oflog/spi/logevent.h ../include/dcmtk/oflog/ndc.h \
 ../include/dcmtk/oflog/helpers/threads.h \
 ../include/dcmtk/oflog/helpers/pointer.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../../ofstd/include/dcmtk/ofstd/ofaptr.h ../include/dcmtk/oflog/consap.h \
 ../include/dcmtk/oflog/appender.h ../include/dcmtk/oflog/spi/filter.h \
 ../include/dcmtk/oflog/helpers/loglog.h \
 ../include/dcmtk/oflog/helpers/strhelp.h \
 ../../ofstd/include/dcmtk/ofstd/ofconsol.h \
 ../../ofstd/include/dcmtk/ofstd/ofthread.h
factory.o: factory.cc ../include/dcmtk/oflog/spi/factory.h \
 ../include/dcmtk/oflog/config.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h \
 ../include/dcmtk/oflog/appender.h ../include/dcmtk/oflog/layout.h \
 ../include/dcmtk/oflog/loglevel.h ../include/dcmtk/oflog/streams.h \
 ../include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/oflog/helpers/lloguser.h \
 ../include/dcmtk/oflog/helpers/property.h \
 ../../ofstd/include/dcmtk/ofstd/ofmap.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../include/dcmtk/oflog/helpers/timehelp.h \
 ../include/dcmtk/oflog/spi/logevent.h ../include/dcmtk/oflog/ndc.h \
 ../include/dcmtk/oflog/helpers/threads.h \
 ../include/dcmtk/oflog/helpers/pointer.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../../ofstd/include/dcmtk/ofstd/ofaptr.h \
 ../include/dcmtk/oflog/spi/filter.h ../include/dcmtk/oflog/spi/objreg.h \
 ../include/dcmtk/oflog/spi/logfact.h ../include/dcmtk/oflog/consap.h \
 ../include/dcmtk/oflog/fileap.h ../include/dcmtk/oflog/fstreams.h \
 ../include/dcmtk/oflog/nullap.h ../include/dcmtk/oflog/socketap.h \
 ../include/dcmtk/oflog/helpers/socket.h \
 ../include/dcmtk/oflog/helpers/sockbuff.h \
 ../include/dcmtk/oflog/helpers/syncprims.h \
 ../include/dcmtk/oflog/helpers/syncppth.h \
 ../include/dcmtk/oflog/syslogap.h \
 ../include/dcmtk/oflog/helpers/loglog.h
fileap.o: fileap.cc ../include/dcmtk/oflog/fileap.h \
 ../include/dcmtk/oflog/config.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h \
 ../include/dcmtk/oflog/appender.h ../include/dcmtk/oflog/layout.h \
 ../include/dcmtk/oflog/loglevel.h ../include/dcmtk/oflog/streams.h \
 ../include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/oflog/helpers/lloguser.h \
 ../include/dcmtk/oflog/helpers/property.h \
 ../../ofstd/include/dcmtk/ofstd/ofmap.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../include/dcmtk/oflog/helpers/timehelp.h \
 ../include/dcmtk/oflog/spi/logevent.h ../include/dcmtk/oflog/ndc.h \
 ../include/dcmtk/oflog/helpers/threads.h \
 ../include/dcmtk/oflog/helpers/pointer.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../../ofstd/include/dcmtk/ofstd/ofaptr.h \
 ../include/dcmtk/oflog/spi/filter.h ../include/dcmtk/oflog/fstreams.h \
 ../include/dcmtk/oflog/helpers/loglog.h \
 ../include/dcmtk/oflog/helpers/strhelp.h
filter.o: filter.cc ../include/dcmtk/oflog/spi/filter.h \
 ../include/dcmtk/oflog/config.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h \
 ../include/dcmtk/oflog/helpers/pointer.h \
 ../include/dcmtk/oflog/helpers/property.h \
 ../include/dcmtk/oflog/streams.h ../include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../../ofstd/include/dcmtk/ofstd/ofmap.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../include/dcmtk/oflog/spi/logevent.h ../include/dcmtk/oflog/loglevel.h \
 ../include/dcmtk/oflog/ndc.h ../include/dcmtk/oflog/helpers/lloguser.h \
 ../include/dcmtk/oflog/helpers/threads.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../include/dcmtk/oflog/helpers/timehelp.h \
 ../../ofstd/include/dcmtk/ofstd/ofaptr.h \
 ../include/dcmtk/oflog/helpers/loglog.h \
 ../include/dcmtk/oflog/helpers/strhelp.h
globinit.o: globinit.cc ../include/dcmtk/oflog/config.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h \
 ../include/dcmtk/oflog/logger.h ../include/dcmtk/oflog/loglevel.h \
 ../include/dcmtk/oflog/streams.h ../include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/oflog/spi/apndatch.h ../include/dcmtk/oflog/appender.h \
 ../include/dcmtk/oflog/layout.h \
 ../include/dcmtk/oflog/helpers/lloguser.h \
 ../include/dcmtk/oflog/helpers/property.h \
 ../../ofstd/include/dcmtk/ofstd/ofmap.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../include/dcmtk/oflog/helpers/timehelp.h \
 ../include/dcmtk/oflog/spi/logevent.h ../include/dcmtk/oflog/ndc.h \
 ../include/dcmtk/oflog/helpers/threads.h \
 ../include/dcmtk/oflog/helpers/pointer.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../../ofstd/include/dcmtk/ofstd/ofaptr.h \
 ../include/dcmtk/oflog/spi/filter.h ../include/dcmtk/oflog/spi/logfact.h \
 ../include/dcmtk/oflog/logmacro.h \
 ../include/dcmtk/oflog/helpers/loglog.h
hierarchy.o: hierarchy.cc ../include/dcmtk/oflog/hierarchy.h \
 ../include/dcmtk/oflog/config.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h \
 ../include/dcmtk/oflog/logger.h ../include/dcmtk/oflog/loglevel.h \
 ../include/dcmtk/oflog/streams.h ../include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/oflog/spi/apndatch.h ../include/dcmtk/oflog/appender.h \
 ../include/dcmtk/oflog/layout.h \
 ../include/dcmtk/oflog/helpers/lloguser.h \
 ../include/dcmtk/oflog/helpers/property.h \
 ../../ofstd/include/dcmtk/ofstd/ofmap.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../include/dcmtk/oflog/helpers/timehelp.h \
 ../include/dcmtk/oflog/spi/logevent.h ../include/dcmtk/oflog/ndc.h \
 ../include/dcmtk/oflog/helpers/threads.h \
 ../include/dcmtk/oflog/helpers/pointer.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../../ofstd/include/dcmtk/ofstd/ofaptr.h \
 ../include/dcmtk/oflog/spi/filter.h ../include/dcmtk/oflog/spi/logfact.h \
 ../include/dcmtk/oflog/logmacro.h \
 ../include/dcmtk/oflog/helpers/loglog.h \
 ../include/dcmtk/oflog/spi/logimpl.h \
 ../include/dcmtk/oflog/helpers/apndimpl.h \
 ../include/dcmtk/oflog/spi/rootlog.h
hierlock.o: hierlock.cc ../include/dcmtk/oflog/hierlock.h \
 ../include/dcmtk/oflog/hierarchy.h ../include/dcmtk/oflog/config.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h \
 ../include/dcmtk/oflog/logger.h ../include/dcmtk/oflog/loglevel.h \
 ../include/dcmtk/oflog/streams.h ../include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/oflog/spi/apndatch.h ../include/dcmtk/oflog/appender.h \
 ../include/dcmtk/oflog/layout.h \
 ../include/dcmtk/oflog/helpers/lloguser.h \
 ../include/dcmtk/oflog/helpers/property.h \
 ../../ofstd/include/dcmtk/ofstd/ofmap.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../include/dcmtk/oflog/helpers/timehelp.h \
 ../include/dcmtk/oflog/spi/logevent.h ../include/dcmtk/oflog/ndc.h \
 ../include/dcmtk/oflog/helpers/threads.h \
 ../include/dcmtk/oflog/helpers/pointer.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../../ofstd/include/dcmtk/ofstd/ofaptr.h \
 ../include/dcmtk/oflog/spi/filter.h ../include/dcmtk/oflog/spi/logfact.h \
 ../include/dcmtk/oflog/logmacro.h \
 ../include/dcmtk/oflog/helpers/loglog.h \
 ../include/dcmtk/oflog/spi/logimpl.h \
 ../include/dcmtk/oflog/helpers/apndimpl.h
layout.o: layout.cc ../include/dcmtk/oflog/layout.h \
 ../include/dcmtk/oflog/config.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h \
 ../include/dcmtk/oflog/loglevel.h ../include/dcmtk/oflog/streams.h \
 ../include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/oflog/helpers/lloguser.h \
 ../include/dcmtk/oflog/helpers/property.h \
 ../../ofstd/include/dcmtk/ofstd/ofmap.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../include/dcmtk/oflog/helpers/timehelp.h \
 ../include/dcmtk/oflog/spi/logevent.h ../include/dcmtk/oflog/ndc.h \
 ../include/dcmtk/oflog/helpers/threads.h \
 ../include/dcmtk/oflog/helpers/pointer.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../../ofstd/include/dcmtk/ofstd/ofaptr.h \
 ../include/dcmtk/oflog/helpers/strhelp.h
lloguser.o: lloguser.cc ../include/dcmtk/oflog/streams.h \
 ../include/dcmtk/oflog/config.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h \
 ../include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/oflog/helpers/lloguser.h \
 ../include/dcmtk/oflog/helpers/loglog.h \
 ../include/dcmtk/oflog/helpers/pointer.h \
 ../include/dcmtk/oflog/helpers/threads.h
logevent.o: logevent.cc ../include/dcmtk/oflog/spi/logevent.h \
 ../include/dcmtk/oflog/config.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h \
 ../include/dcmtk/oflog/loglevel.h ../include/dcmtk/oflog/streams.h \
 ../include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h ../include/dcmtk/oflog/ndc.h \
 ../include/dcmtk/oflog/helpers/lloguser.h \
 ../include/dcmtk/oflog/helpers/threads.h \
 ../include/dcmtk/oflog/helpers/pointer.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../include/dcmtk/oflog/helpers/timehelp.h \
 ../../ofstd/include/dcmtk/ofstd/ofaptr.h
logger.o: logger.cc ../include/dcmtk/oflog/logger.h \
 ../include/dcmtk/oflog/config.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h \
 ../include/dcmtk/oflog/loglevel.h ../include/dcmtk/oflog/streams.h \
 ../include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/oflog/spi/apndatch.h ../include/dcmtk/oflog/appender.h \
 ../include/dcmtk/oflog/layout.h \
 ../include/dcmtk/oflog/helpers/lloguser.h \
 ../include/dcmtk/oflog/helpers/property.h \
 ../../ofstd/include/dcmtk/ofstd/ofmap.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../include/dcmtk/oflog/helpers/timehelp.h \
 ../include/dcmtk/oflog/spi/logevent.h ../include/dcmtk/oflog/ndc.h \
 ../include/dcmtk/oflog/helpers/threads.h \
 ../include/dcmtk/oflog/helpers/pointer.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../../ofstd/include/dcmtk/ofstd/ofaptr.h \
 ../include/dcmtk/oflog/spi/filter.h ../include/dcmtk/oflog/spi/logfact.h \
 ../include/dcmtk/oflog/logmacro.h ../include/dcmtk/oflog/hierarchy.h \
 ../include/dcmtk/oflog/helpers/loglog.h \
 ../include/dcmtk/oflog/spi/logimpl.h \
 ../include/dcmtk/oflog/helpers/apndimpl.h
logimpl.o: logimpl.cc ../include/dcmtk/oflog/spi/logimpl.h \
 ../include/dcmtk/oflog/config.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h \
 ../include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/oflog/helpers/apndimpl.h \
 ../include/dcmtk/oflog/layout.h ../include/dcmtk/oflog/loglevel.h \
 ../include/dcmtk/oflog/streams.h \
 ../include/dcmtk/oflog/helpers/lloguser.h \
 ../include/dcmtk/oflog/helpers/property.h \
 ../../ofstd/include/dcmtk/ofstd/ofmap.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../include/dcmtk/oflog/helpers/timehelp.h \
 ../include/dcmtk/oflog/spi/logevent.h ../include/dcmtk/oflog/ndc.h \
 ../include/dcmtk/oflog/helpers/threads.h \
 ../include/dcmtk/oflog/helpers/pointer.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../../ofstd/include/dcmtk/ofstd/ofaptr.h \
 ../include/dcmtk/oflog/spi/apndatch.h ../include/dcmtk/oflog/appender.h \
 ../include/dcmtk/oflog/spi/filter.h ../include/dcmtk/oflog/spi/logfact.h \
 ../include/dcmtk/oflog/hierarchy.h ../include/dcmtk/oflog/logger.h \
 ../include/dcmtk/oflog/logmacro.h \
 ../include/dcmtk/oflog/helpers/loglog.h \
 ../include/dcmtk/oflog/spi/rootlog.h
loglevel.o: loglevel.cc ../include/dcmtk/oflog/loglevel.h \
 ../include/dcmtk/oflog/config.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h \
 ../include/dcmtk/oflog/streams.h ../include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/oflog/helpers/loglog.h \
 ../include/dcmtk/oflog/helpers/pointer.h \
 ../include/dcmtk/oflog/helpers/threads.h \
 ../include/dcmtk/oflog/helpers/strhelp.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h
loglog.o: loglog.cc ../include/dcmtk/oflog/streams.h \
 ../include/dcmtk/oflog/config.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h \
 ../include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/oflog/helpers/loglog.h \
 ../include/dcmtk/oflog/helpers/pointer.h \
 ../include/dcmtk/oflog/helpers/threads.h \
 ../../ofstd/include/dcmtk/ofstd/ofconsol.h \
 ../../ofstd/include/dcmtk/ofstd/ofthread.h
ndc.o: ndc.cc ../include/dcmtk/oflog/config.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h ../include/dcmtk/oflog/ndc.h \
 ../include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/oflog/helpers/lloguser.h \
 ../include/dcmtk/oflog/helpers/threads.h \
 ../include/dcmtk/oflog/helpers/pointer.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../include/dcmtk/oflog/helpers/loglog.h
ntelogap.o: ntelogap.cc ../include/dcmtk/oflog/ntelogap.h \
 ../include/dcmtk/oflog/config.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h \
 ../include/dcmtk/oflog/appender.h ../include/dcmtk/oflog/layout.h \
 ../include/dcmtk/oflog/loglevel.h ../include/dcmtk/oflog/streams.h \
 ../include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/oflog/helpers/lloguser.h \
 ../include/dcmtk/oflog/helpers/property.h \
 ../../ofstd/include/dcmtk/ofstd/ofmap.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../include/dcmtk/oflog/helpers/timehelp.h \
 ../include/dcmtk/oflog/spi/logevent.h ../include/dcmtk/oflog/ndc.h \
 ../include/dcmtk/oflog/helpers/threads.h \
 ../include/dcmtk/oflog/helpers/pointer.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../../ofstd/include/dcmtk/ofstd/ofaptr.h \
 ../include/dcmtk/oflog/spi/filter.h \
 ../include/dcmtk/oflog/helpers/loglog.h
nullap.o: nullap.cc ../include/dcmtk/oflog/nullap.h \
 ../include/dcmtk/oflog/config.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h \
 ../include/dcmtk/oflog/appender.h ../include/dcmtk/oflog/layout.h \
 ../include/dcmtk/oflog/loglevel.h ../include/dcmtk/oflog/streams.h \
 ../include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/oflog/helpers/lloguser.h \
 ../include/dcmtk/oflog/helpers/property.h \
 ../../ofstd/include/dcmtk/ofstd/ofmap.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../include/dcmtk/oflog/helpers/timehelp.h \
 ../include/dcmtk/oflog/spi/logevent.h ../include/dcmtk/oflog/ndc.h \
 ../include/dcmtk/oflog/helpers/threads.h \
 ../include/dcmtk/oflog/helpers/pointer.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../../ofstd/include/dcmtk/ofstd/ofaptr.h \
 ../include/dcmtk/oflog/spi/filter.h
objreg.o: objreg.cc ../include/dcmtk/oflog/spi/objreg.h \
 ../include/dcmtk/oflog/config.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h \
 ../include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/oflog/helpers/threads.h \
 ../include/dcmtk/oflog/helpers/pointer.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../../ofstd/include/dcmtk/ofstd/ofmap.h
oflog.o: oflog.cc ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofstd.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/ofdate.h \
 ../../ofstd/include/dcmtk/ofstd/oftime.h ../include/dcmtk/oflog/oflog.h \
 ../include/dcmtk/oflog/logger.h ../include/dcmtk/oflog/config.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h \
 ../include/dcmtk/oflog/loglevel.h ../include/dcmtk/oflog/streams.h \
 ../include/dcmtk/oflog/tstring.h ../include/dcmtk/oflog/spi/apndatch.h \
 ../include/dcmtk/oflog/appender.h ../include/dcmtk/oflog/layout.h \
 ../include/dcmtk/oflog/helpers/lloguser.h \
 ../include/dcmtk/oflog/helpers/property.h \
 ../../ofstd/include/dcmtk/ofstd/ofmap.h \
 ../include/dcmtk/oflog/helpers/timehelp.h \
 ../include/dcmtk/oflog/spi/logevent.h ../include/dcmtk/oflog/ndc.h \
 ../include/dcmtk/oflog/helpers/threads.h \
 ../include/dcmtk/oflog/helpers/pointer.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../../ofstd/include/dcmtk/ofstd/ofaptr.h \
 ../include/dcmtk/oflog/spi/filter.h ../include/dcmtk/oflog/spi/logfact.h \
 ../include/dcmtk/oflog/logmacro.h \
 ../../ofstd/include/dcmtk/ofstd/ofconapp.h \
 ../../ofstd/include/dcmtk/ofstd/ofcmdln.h \
 ../../ofstd/include/dcmtk/ofstd/ofconsol.h \
 ../../ofstd/include/dcmtk/ofstd/ofthread.h \
 ../../ofstd/include/dcmtk/ofstd/offile.h \
 ../include/dcmtk/oflog/configrt.h ../include/dcmtk/oflog/hierarchy.h \
 ../include/dcmtk/oflog/consap.h ../include/dcmtk/oflog/helpers/loglog.h \
 ../include/dcmtk/oflog/helpers/socket.h \
 ../include/dcmtk/oflog/helpers/sockbuff.h \
 ../include/dcmtk/oflog/helpers/strhelp.h
patlay.o: patlay.cc ../include/dcmtk/oflog/layout.h \
 ../include/dcmtk/oflog/config.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h \
 ../include/dcmtk/oflog/loglevel.h ../include/dcmtk/oflog/streams.h \
 ../include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/oflog/helpers/lloguser.h \
 ../include/dcmtk/oflog/helpers/property.h \
 ../../ofstd/include/dcmtk/ofstd/ofmap.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../include/dcmtk/oflog/helpers/timehelp.h \
 ../include/dcmtk/oflog/spi/logevent.h ../include/dcmtk/oflog/ndc.h \
 ../include/dcmtk/oflog/helpers/threads.h \
 ../include/dcmtk/oflog/helpers/pointer.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../../ofstd/include/dcmtk/ofstd/ofaptr.h \
 ../include/dcmtk/oflog/helpers/loglog.h \
 ../include/dcmtk/oflog/helpers/strhelp.h \
 ../include/dcmtk/oflog/helpers/socket.h \
 ../include/dcmtk/oflog/helpers/sockbuff.h
pointer.o: pointer.cc ../include/dcmtk/oflog/streams.h \
 ../include/dcmtk/oflog/config.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h \
 ../include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/oflog/helpers/pointer.h \
 ../include/dcmtk/oflog/helpers/threads.h
property.o: property.cc ../include/dcmtk/oflog/helpers/property.h \
 ../include/dcmtk/oflog/config.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h \
 ../include/dcmtk/oflog/streams.h ../include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../../ofstd/include/dcmtk/ofstd/ofmap.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../include/dcmtk/oflog/fstreams.h
rootlog.o: rootlog.cc ../include/dcmtk/oflog/spi/rootlog.h \
 ../include/dcmtk/oflog/config.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h \
 ../include/dcmtk/oflog/helpers/loglog.h ../include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/oflog/helpers/pointer.h \
 ../include/dcmtk/oflog/helpers/threads.h \
 ../include/dcmtk/oflog/spi/logimpl.h \
 ../include/dcmtk/oflog/helpers/apndimpl.h \
 ../include/dcmtk/oflog/layout.h ../include/dcmtk/oflog/loglevel.h \
 ../include/dcmtk/oflog/streams.h \
 ../include/dcmtk/oflog/helpers/lloguser.h \
 ../include/dcmtk/oflog/helpers/property.h \
 ../../ofstd/include/dcmtk/ofstd/ofmap.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../include/dcmtk/oflog/helpers/timehelp.h \
 ../include/dcmtk/oflog/spi/logevent.h ../include/dcmtk/oflog/ndc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../../ofstd/include/dcmtk/ofstd/ofaptr.h \
 ../include/dcmtk/oflog/spi/apndatch.h ../include/dcmtk/oflog/appender.h \
 ../include/dcmtk/oflog/spi/filter.h ../include/dcmtk/oflog/spi/logfact.h
sleep.o: sleep.cc ../include/dcmtk/oflog/helpers/sleep.h \
 ../include/dcmtk/oflog/config.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h \
 ../../ofstd/include/dcmtk/ofstd/ofstd.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h
sockbuff.o: sockbuff.cc ../include/dcmtk/oflog/helpers/sockbuff.h \
 ../include/dcmtk/oflog/config.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h \
 ../include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/oflog/helpers/lloguser.h \
 ../include/dcmtk/oflog/helpers/loglog.h \
 ../include/dcmtk/oflog/helpers/pointer.h \
 ../include/dcmtk/oflog/helpers/threads.h
socket.o: socket.cc ../include/dcmtk/oflog/helpers/socket.h \
 ../include/dcmtk/oflog/config.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h \
 ../include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/oflog/helpers/sockbuff.h \
 ../include/dcmtk/oflog/helpers/lloguser.h \
 ../include/dcmtk/oflog/helpers/loglog.h \
 ../include/dcmtk/oflog/helpers/pointer.h \
 ../include/dcmtk/oflog/helpers/threads.h
socketap.o: socketap.cc ../include/dcmtk/oflog/socketap.h \
 ../include/dcmtk/oflog/config.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h \
 ../include/dcmtk/oflog/appender.h ../include/dcmtk/oflog/layout.h \
 ../include/dcmtk/oflog/loglevel.h ../include/dcmtk/oflog/streams.h \
 ../include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/oflog/helpers/lloguser.h \
 ../include/dcmtk/oflog/helpers/property.h \
 ../../ofstd/include/dcmtk/ofstd/ofmap.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../include/dcmtk/oflog/helpers/timehelp.h \
 ../include/dcmtk/oflog/spi/logevent.h ../include/dcmtk/oflog/ndc.h \
 ../include/dcmtk/oflog/helpers/threads.h \
 ../include/dcmtk/oflog/helpers/pointer.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../../ofstd/include/dcmtk/ofstd/ofaptr.h \
 ../include/dcmtk/oflog/spi/filter.h \
 ../include/dcmtk/oflog/helpers/socket.h \
 ../include/dcmtk/oflog/helpers/sockbuff.h \
 ../include/dcmtk/oflog/helpers/syncprims.h \
 ../include/dcmtk/oflog/helpers/syncppth.h \
 ../include/dcmtk/oflog/helpers/loglog.h \
 ../include/dcmtk/oflog/helpers/sleep.h
strhelp.o: strhelp.cc ../include/dcmtk/oflog/helpers/strhelp.h \
 ../include/dcmtk/oflog/config.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h \
 ../include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../include/dcmtk/oflog/streams.h ../include/dcmtk/oflog/logmacro.h \
 ../../ofstd/include/dcmtk/ofstd/ofstd.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h
syncprims.o: syncprims.cc ../include/dcmtk/oflog/helpers/syncprims.h \
 ../include/dcmtk/oflog/config.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h \
 ../include/dcmtk/oflog/helpers/timehelp.h \
 ../include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/oflog/helpers/syncppth.h \
 ../../ofstd/include/dcmtk/ofstd/ofconsol.h \
 ../../ofstd/include/dcmtk/ofstd/ofthread.h
syslogap.o: syslogap.cc ../include/dcmtk/oflog/syslogap.h \
 ../include/dcmtk/oflog/config.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h \
 ../include/dcmtk/oflog/appender.h ../include/dcmtk/oflog/layout.h \
 ../include/dcmtk/oflog/loglevel.h ../include/dcmtk/oflog/streams.h \
 ../include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/oflog/helpers/lloguser.h \
 ../include/dcmtk/oflog/helpers/property.h \
 ../../ofstd/include/dcmtk/ofstd/ofmap.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../include/dcmtk/oflog/helpers/timehelp.h \
 ../include/dcmtk/oflog/spi/logevent.h ../include/dcmtk/oflog/ndc.h \
 ../include/dcmtk/oflog/helpers/threads.h \
 ../include/dcmtk/oflog/helpers/pointer.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../../ofstd/include/dcmtk/ofstd/ofaptr.h \
 ../include/dcmtk/oflog/spi/filter.h \
 ../include/dcmtk/oflog/helpers/loglog.h
threads.o: threads.cc ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../include/dcmtk/oflog/config.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h \
 ../include/dcmtk/oflog/helpers/threads.h \
 ../include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/oflog/helpers/pointer.h \
 ../include/dcmtk/oflog/streams.h ../include/dcmtk/oflog/ndc.h \
 ../include/dcmtk/oflog/helpers/lloguser.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../include/dcmtk/oflog/helpers/loglog.h \
 ../include/dcmtk/oflog/helpers/strhelp.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../include/dcmtk/oflog/helpers/timehelp.h \
 ../include/dcmtk/oflog/helpers/syncprims.h \
 ../include/dcmtk/oflog/helpers/syncppth.h
timehelp.o: timehelp.cc ../include/dcmtk/oflog/helpers/timehelp.h \
 ../include/dcmtk/oflog/config.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h \
 ../include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/oflog/streams.h \
 ../include/dcmtk/oflog/helpers/strhelp.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h
unixsock.o: unixsock.cc ../include/dcmtk/oflog/helpers/socket.h \
 ../include/dcmtk/oflog/config.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h \
 ../include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/oflog/helpers/sockbuff.h \
 ../include/dcmtk/oflog/helpers/lloguser.h \
 ../include/dcmtk/oflog/helpers/loglog.h \
 ../include/dcmtk/oflog/helpers/pointer.h \
 ../include/dcmtk/oflog/helpers/threads.h \
 ../include/dcmtk/oflog/spi/logevent.h ../include/dcmtk/oflog/loglevel.h \
 ../include/dcmtk/oflog/streams.h ../include/dcmtk/oflog/ndc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstack.h \
 ../include/dcmtk/oflog/helpers/timehelp.h \
 ../../ofstd/include/dcmtk/ofstd/ofaptr.h
winconap.o: winconap.cc ../include/dcmtk/oflog/winconap.h \
 ../include/dcmtk/oflog/config.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h \
 ../include/dcmtk/oflog/helpers/loglog.h ../include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/oflog/helpers/pointer.h \
 ../include/dcmtk/oflog/helpers/threads.h \
 ../include/dcmtk/oflog/helpers/strhelp.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h
windebap.o: windebap.cc ../include/dcmtk/oflog/windebap.h \
 ../include/dcmtk/oflog/config.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h
winsock.o: winsock.cc ../include/dcmtk/oflog/helpers/socket.h \
 ../include/dcmtk/oflog/config.h \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../include/dcmtk/oflog/config/defines.h \
 ../include/dcmtk/oflog/helpers/threadcf.h \
 ../include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/oflog/helpers/sockbuff.h \
 ../include/dcmtk/oflog/helpers/lloguser.h \
 ../include/dcmtk/oflog/helpers/loglog.h \
 ../include/dcmtk/oflog/helpers/pointer.h \
 ../include/dcmtk/oflog/helpers/threads.h
