oficonv_tests.o: oficonv_tests.cc \
 ../../config/include/dcmtk/config/osconfig.h oficonv_tests.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../include/dcmtk/oficonv/iconv.h ../include/dcmtk/oficonv/oidefine.h \
 ../../ofstd/include/dcmtk/ofstd/oftest.h \
 ../../ofstd/include/dcmtk/ofstd/ofconapp.h \
 ../../ofstd/include/dcmtk/ofstd/ofcmdln.h \
 ../../ofstd/include/dcmtk/ofstd/ofexbl.h \
 ../../ofstd/include/dcmtk/ofstd/oftraits.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../../ofstd/include/dcmtk/ofstd/ofconsol.h \
 ../../ofstd/include/dcmtk/ofstd/ofthread.h \
 ../../ofstd/include/dcmtk/ofstd/offile.h \
 ../../ofstd/include/dcmtk/ofstd/ofstd.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/ofdiag.h \
 ../../ofstd/include/dcmtk/ofstd/diag/push.def \
 ../../ofstd/include/dcmtk/ofstd/diag/useafree.def \
 ../../ofstd/include/dcmtk/ofstd/diag/pop.def \
 ../../ofstd/include/dcmtk/ofstd/oflimits.h \
 ../../config/include/dcmtk/config/arith.h \
 ../../ofstd/include/dcmtk/ofstd/oferror.h \
 ../../ofstd/include/dcmtk/ofstd/ofexit.h
tests.o: tests.cc ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/oftest.h \
 ../../ofstd/include/dcmtk/ofstd/ofconapp.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../../ofstd/include/dcmtk/ofstd/ofcmdln.h \
 ../../ofstd/include/dcmtk/ofstd/ofexbl.h \
 ../../ofstd/include/dcmtk/ofstd/oftraits.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofconsol.h \
 ../../ofstd/include/dcmtk/ofstd/ofthread.h \
 ../../ofstd/include/dcmtk/ofstd/offile.h \
 ../../ofstd/include/dcmtk/ofstd/ofstd.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/ofdiag.h \
 ../../ofstd/include/dcmtk/ofstd/diag/push.def \
 ../../ofstd/include/dcmtk/ofstd/diag/useafree.def \
 ../../ofstd/include/dcmtk/ofstd/diag/pop.def \
 ../../ofstd/include/dcmtk/ofstd/oflimits.h \
 ../../config/include/dcmtk/config/arith.h \
 ../../ofstd/include/dcmtk/ofstd/oferror.h \
 ../../ofstd/include/dcmtk/ofstd/ofexit.h
ticonv.o: ticonv.cc ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/oftest.h \
 ../../ofstd/include/dcmtk/ofstd/ofconapp.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../../ofstd/include/dcmtk/ofstd/ofcmdln.h \
 ../../ofstd/include/dcmtk/ofstd/ofexbl.h \
 ../../ofstd/include/dcmtk/ofstd/oftraits.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofconsol.h \
 ../../ofstd/include/dcmtk/ofstd/ofthread.h \
 ../../ofstd/include/dcmtk/ofstd/offile.h \
 ../../ofstd/include/dcmtk/ofstd/ofstd.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/ofdiag.h \
 ../../ofstd/include/dcmtk/ofstd/diag/push.def \
 ../../ofstd/include/dcmtk/ofstd/diag/useafree.def \
 ../../ofstd/include/dcmtk/ofstd/diag/pop.def \
 ../../ofstd/include/dcmtk/ofstd/oflimits.h \
 ../../config/include/dcmtk/config/arith.h \
 ../../ofstd/include/dcmtk/ofstd/oferror.h \
 ../../ofstd/include/dcmtk/ofstd/ofexit.h \
 ../include/dcmtk/oficonv/iconv.h ../include/dcmtk/oficonv/oidefine.h \
 oficonv_tests.h tables_invalids.h
ticonv_chinese.o: ticonv_chinese.cc \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/oftest.h \
 ../../ofstd/include/dcmtk/ofstd/ofconapp.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../../ofstd/include/dcmtk/ofstd/ofcmdln.h \
 ../../ofstd/include/dcmtk/ofstd/ofexbl.h \
 ../../ofstd/include/dcmtk/ofstd/oftraits.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofconsol.h \
 ../../ofstd/include/dcmtk/ofstd/ofthread.h \
 ../../ofstd/include/dcmtk/ofstd/offile.h \
 ../../ofstd/include/dcmtk/ofstd/ofstd.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/ofdiag.h \
 ../../ofstd/include/dcmtk/ofstd/diag/push.def \
 ../../ofstd/include/dcmtk/ofstd/diag/useafree.def \
 ../../ofstd/include/dcmtk/ofstd/diag/pop.def \
 ../../ofstd/include/dcmtk/ofstd/oflimits.h \
 ../../config/include/dcmtk/config/arith.h \
 ../../ofstd/include/dcmtk/ofstd/oferror.h \
 ../../ofstd/include/dcmtk/ofstd/ofexit.h oficonv_tests.h \
 ../include/dcmtk/oficonv/iconv.h ../include/dcmtk/oficonv/oidefine.h \
 tables_gb18030.h tables_gb2312.h tables_gbk.h
ticonv_iso8859.o: ticonv_iso8859.cc \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/oftest.h \
 ../../ofstd/include/dcmtk/ofstd/ofconapp.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../../ofstd/include/dcmtk/ofstd/ofcmdln.h \
 ../../ofstd/include/dcmtk/ofstd/ofexbl.h \
 ../../ofstd/include/dcmtk/ofstd/oftraits.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofconsol.h \
 ../../ofstd/include/dcmtk/ofstd/ofthread.h \
 ../../ofstd/include/dcmtk/ofstd/offile.h \
 ../../ofstd/include/dcmtk/ofstd/ofstd.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/ofdiag.h \
 ../../ofstd/include/dcmtk/ofstd/diag/push.def \
 ../../ofstd/include/dcmtk/ofstd/diag/useafree.def \
 ../../ofstd/include/dcmtk/ofstd/diag/pop.def \
 ../../ofstd/include/dcmtk/ofstd/oflimits.h \
 ../../config/include/dcmtk/config/arith.h \
 ../../ofstd/include/dcmtk/ofstd/oferror.h \
 ../../ofstd/include/dcmtk/ofstd/ofexit.h \
 ../include/dcmtk/oficonv/iconv.h ../include/dcmtk/oficonv/oidefine.h \
 oficonv_tests.h tables_iso8859.h
ticonv_japanese.o: ticonv_japanese.cc \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/oftest.h \
 ../../ofstd/include/dcmtk/ofstd/ofconapp.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../../ofstd/include/dcmtk/ofstd/ofcmdln.h \
 ../../ofstd/include/dcmtk/ofstd/ofexbl.h \
 ../../ofstd/include/dcmtk/ofstd/oftraits.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofconsol.h \
 ../../ofstd/include/dcmtk/ofstd/ofthread.h \
 ../../ofstd/include/dcmtk/ofstd/offile.h \
 ../../ofstd/include/dcmtk/ofstd/ofstd.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/ofdiag.h \
 ../../ofstd/include/dcmtk/ofstd/diag/push.def \
 ../../ofstd/include/dcmtk/ofstd/diag/useafree.def \
 ../../ofstd/include/dcmtk/ofstd/diag/pop.def \
 ../../ofstd/include/dcmtk/ofstd/oflimits.h \
 ../../config/include/dcmtk/config/arith.h \
 ../../ofstd/include/dcmtk/ofstd/oferror.h \
 ../../ofstd/include/dcmtk/ofstd/ofexit.h oficonv_tests.h \
 ../include/dcmtk/oficonv/iconv.h ../include/dcmtk/oficonv/oidefine.h \
 tables_jis_x0201.h tables_jis_x0208.h tables_jis_x0212.h
ticonv_korean.o: ticonv_korean.cc \
 ../../config/include/dcmtk/config/osconfig.h \
 ../../ofstd/include/dcmtk/ofstd/oftest.h \
 ../../ofstd/include/dcmtk/ofstd/ofconapp.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../../ofstd/include/dcmtk/ofstd/ofcmdln.h \
 ../../ofstd/include/dcmtk/ofstd/ofexbl.h \
 ../../ofstd/include/dcmtk/ofstd/oftraits.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofconsol.h \
 ../../ofstd/include/dcmtk/ofstd/ofthread.h \
 ../../ofstd/include/dcmtk/ofstd/offile.h \
 ../../ofstd/include/dcmtk/ofstd/ofstd.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/ofdiag.h \
 ../../ofstd/include/dcmtk/ofstd/diag/push.def \
 ../../ofstd/include/dcmtk/ofstd/diag/useafree.def \
 ../../ofstd/include/dcmtk/ofstd/diag/pop.def \
 ../../ofstd/include/dcmtk/ofstd/oflimits.h \
 ../../config/include/dcmtk/config/arith.h \
 ../../ofstd/include/dcmtk/ofstd/oferror.h \
 ../../ofstd/include/dcmtk/ofstd/ofexit.h \
 ../include/dcmtk/oficonv/iconv.h ../include/dcmtk/oficonv/oidefine.h \
 oficonv_tests.h tables_ksx_1001.h
