convobj.o: convobj.cc ../include/dctk.h ../include/dctypes.h \
 ../include/dcswap.h ../include/dcstream.h ../include/dcvr.h \
 ../include/dcdicenu.h ../include/ddicenuz.i ../include/dcxfer.h \
 ../include/dcobject.h ../include/dctag.h ../include/dcstack.h \
 ../include/dcelem.h ../include/dcitem.h ../include/dcvrui.h \
 ../include/dcbytstr.h ../include/dclist.h ../include/dcmetinf.h \
 ../include/dcdatset.h ../include/dcsequen.h ../include/dcfilefo.h \
 ../include/dicomdir/dcdicdir.h ../include/dicomdir/dcdirrec.h \
 ../include/dcvrulup.h ../include/dcvrul.h ../include/dcpixseq.h \
 ../include/dcvrae.h ../include/dcvras.h ../include/dcvrcs.h \
 ../include/dcvrda.h ../include/dcvrds.h ../include/dcvrdt.h \
 ../include/dcvris.h ../include/dcvrtm.h ../include/dcchrstr.h \
 ../include/dcvrlo.h ../include/dcvrlt.h ../include/dcvrpn.h \
 ../include/dcvrsh.h ../include/dcvrst.h ../include/dcvrobow.h \
 ../include/dcpxitem.h ../include/dcvrat.h ../include/dcvrss.h \
 ../include/dcvrus.h ../include/dcvrsl.h ../include/dcvrfl.h \
 ../include/dcvrfd.h ../include/dcdebug.h
dcimapix.o: dcimapix.cc ../include/dcdebug.h dcmutils.h \
 ../include/dctk.h ../include/dctypes.h ../include/dcswap.h \
 ../include/dcstream.h ../include/dcvr.h ../include/dcdicenu.h \
 ../include/ddicenuz.i ../include/dcxfer.h ../include/dcobject.h \
 ../include/dctag.h ../include/dcstack.h ../include/dcelem.h \
 ../include/dcitem.h ../include/dcvrui.h ../include/dcbytstr.h \
 ../include/dclist.h ../include/dcmetinf.h ../include/dcdatset.h \
 ../include/dcsequen.h ../include/dcfilefo.h \
 ../include/dicomdir/dcdicdir.h ../include/dicomdir/dcdirrec.h \
 ../include/dcvrulup.h ../include/dcvrul.h ../include/dcpixseq.h \
 ../include/dcvrae.h ../include/dcvras.h ../include/dcvrcs.h \
 ../include/dcvrda.h ../include/dcvrds.h ../include/dcvrdt.h \
 ../include/dcvris.h ../include/dcvrtm.h ../include/dcchrstr.h \
 ../include/dcvrlo.h ../include/dcvrlt.h ../include/dcvrpn.h \
 ../include/dcvrsh.h ../include/dcvrst.h ../include/dcvrobow.h \
 ../include/dcpxitem.h ../include/dcvrat.h ../include/dcvrss.h \
 ../include/dcvrus.h ../include/dcvrsl.h ../include/dcvrfl.h \
 ../include/dcvrfd.h dcimapix.h
dcm2ppm.o: dcm2ppm.cc ../include/dctk.h ../include/dctypes.h \
 ../include/dcswap.h ../include/dcstream.h ../include/dcvr.h \
 ../include/dcdicenu.h ../include/ddicenuz.i ../include/dcxfer.h \
 ../include/dcobject.h ../include/dctag.h ../include/dcstack.h \
 ../include/dcelem.h ../include/dcitem.h ../include/dcvrui.h \
 ../include/dcbytstr.h ../include/dclist.h ../include/dcmetinf.h \
 ../include/dcdatset.h ../include/dcsequen.h ../include/dcfilefo.h \
 ../include/dicomdir/dcdicdir.h ../include/dicomdir/dcdirrec.h \
 ../include/dcvrulup.h ../include/dcvrul.h ../include/dcpixseq.h \
 ../include/dcvrae.h ../include/dcvras.h ../include/dcvrcs.h \
 ../include/dcvrda.h ../include/dcvrds.h ../include/dcvrdt.h \
 ../include/dcvris.h ../include/dcvrtm.h ../include/dcchrstr.h \
 ../include/dcvrlo.h ../include/dcvrlt.h ../include/dcvrpn.h \
 ../include/dcvrsh.h ../include/dcvrst.h ../include/dcvrobow.h \
 ../include/dcpxitem.h ../include/dcvrat.h ../include/dcvrss.h \
 ../include/dcvrus.h ../include/dcvrsl.h ../include/dcvrfl.h \
 ../include/dcvrfd.h ../include/dcdebug.h dcmutils.h dcimapix.h
dcmdump.o: dcmdump.cc ../include/dctk.h ../include/dctypes.h \
 ../include/dcswap.h ../include/dcstream.h ../include/dcvr.h \
 ../include/dcdicenu.h ../include/ddicenuz.i ../include/dcxfer.h \
 ../include/dcobject.h ../include/dctag.h ../include/dcstack.h \
 ../include/dcelem.h ../include/dcitem.h ../include/dcvrui.h \
 ../include/dcbytstr.h ../include/dclist.h ../include/dcmetinf.h \
 ../include/dcdatset.h ../include/dcsequen.h ../include/dcfilefo.h \
 ../include/dicomdir/dcdicdir.h ../include/dicomdir/dcdirrec.h \
 ../include/dcvrulup.h ../include/dcvrul.h ../include/dcpixseq.h \
 ../include/dcvrae.h ../include/dcvras.h ../include/dcvrcs.h \
 ../include/dcvrda.h ../include/dcvrds.h ../include/dcvrdt.h \
 ../include/dcvris.h ../include/dcvrtm.h ../include/dcchrstr.h \
 ../include/dcvrlo.h ../include/dcvrlt.h ../include/dcvrpn.h \
 ../include/dcvrsh.h ../include/dcvrst.h ../include/dcvrobow.h \
 ../include/dcpxitem.h ../include/dcvrat.h ../include/dcvrss.h \
 ../include/dcvrus.h ../include/dcvrsl.h ../include/dcvrfl.h \
 ../include/dcvrfd.h ../include/dcdebug.h
dcmutils.o: dcmutils.cc dcmutils.h ../include/dctk.h \
 ../include/dctypes.h ../include/dcswap.h ../include/dcstream.h \
 ../include/dcvr.h ../include/dcdicenu.h ../include/ddicenuz.i \
 ../include/dcxfer.h ../include/dcobject.h ../include/dctag.h \
 ../include/dcstack.h ../include/dcelem.h ../include/dcitem.h \
 ../include/dcvrui.h ../include/dcbytstr.h ../include/dclist.h \
 ../include/dcmetinf.h ../include/dcdatset.h ../include/dcsequen.h \
 ../include/dcfilefo.h ../include/dicomdir/dcdicdir.h \
 ../include/dicomdir/dcdirrec.h ../include/dcvrulup.h \
 ../include/dcvrul.h ../include/dcpixseq.h ../include/dcvrae.h \
 ../include/dcvras.h ../include/dcvrcs.h ../include/dcvrda.h \
 ../include/dcvrds.h ../include/dcvrdt.h ../include/dcvris.h \
 ../include/dcvrtm.h ../include/dcchrstr.h ../include/dcvrlo.h \
 ../include/dcvrlt.h ../include/dcvrpn.h ../include/dcvrsh.h \
 ../include/dcvrst.h ../include/dcvrobow.h ../include/dcpxitem.h \
 ../include/dcvrat.h ../include/dcvrss.h ../include/dcvrus.h \
 ../include/dcvrsl.h ../include/dcvrfl.h ../include/dcvrfd.h \
 ../include/dcdebug.h
ds2file.o: ds2file.cc ../include/dctk.h ../include/dctypes.h \
 ../include/dcswap.h ../include/dcstream.h ../include/dcvr.h \
 ../include/dcdicenu.h ../include/ddicenuz.i ../include/dcxfer.h \
 ../include/dcobject.h ../include/dctag.h ../include/dcstack.h \
 ../include/dcelem.h ../include/dcitem.h ../include/dcvrui.h \
 ../include/dcbytstr.h ../include/dclist.h ../include/dcmetinf.h \
 ../include/dcdatset.h ../include/dcsequen.h ../include/dcfilefo.h \
 ../include/dicomdir/dcdicdir.h ../include/dicomdir/dcdirrec.h \
 ../include/dcvrulup.h ../include/dcvrul.h ../include/dcpixseq.h \
 ../include/dcvrae.h ../include/dcvras.h ../include/dcvrcs.h \
 ../include/dcvrda.h ../include/dcvrds.h ../include/dcvrdt.h \
 ../include/dcvris.h ../include/dcvrtm.h ../include/dcchrstr.h \
 ../include/dcvrlo.h ../include/dcvrlt.h ../include/dcvrpn.h \
 ../include/dcvrsh.h ../include/dcvrst.h ../include/dcvrobow.h \
 ../include/dcpxitem.h ../include/dcvrat.h ../include/dcvrss.h \
 ../include/dcvrus.h ../include/dcvrsl.h ../include/dcvrfl.h \
 ../include/dcvrfd.h ../include/dcdebug.h
file2ds.o: file2ds.cc ../include/dctk.h ../include/dctypes.h \
 ../include/dcswap.h ../include/dcstream.h ../include/dcvr.h \
 ../include/dcdicenu.h ../include/ddicenuz.i ../include/dcxfer.h \
 ../include/dcobject.h ../include/dctag.h ../include/dcstack.h \
 ../include/dcelem.h ../include/dcitem.h ../include/dcvrui.h \
 ../include/dcbytstr.h ../include/dclist.h ../include/dcmetinf.h \
 ../include/dcdatset.h ../include/dcsequen.h ../include/dcfilefo.h \
 ../include/dicomdir/dcdicdir.h ../include/dicomdir/dcdirrec.h \
 ../include/dcvrulup.h ../include/dcvrul.h ../include/dcpixseq.h \
 ../include/dcvrae.h ../include/dcvras.h ../include/dcvrcs.h \
 ../include/dcvrda.h ../include/dcvrds.h ../include/dcvrdt.h \
 ../include/dcvris.h ../include/dcvrtm.h ../include/dcchrstr.h \
 ../include/dcvrlo.h ../include/dcvrlt.h ../include/dcvrpn.h \
 ../include/dcvrsh.h ../include/dcvrst.h ../include/dcvrobow.h \
 ../include/dcpxitem.h ../include/dcvrat.h ../include/dcvrss.h \
 ../include/dcvrus.h ../include/dcvrsl.h ../include/dcvrfl.h \
 ../include/dcvrfd.h ../include/dcdebug.h
mknldir.o: mknldir.cc ../include/dctk.h ../include/dctypes.h \
 ../include/dcswap.h ../include/dcstream.h ../include/dcvr.h \
 ../include/dcdicenu.h ../include/ddicenuz.i ../include/dcxfer.h \
 ../include/dcobject.h ../include/dctag.h ../include/dcstack.h \
 ../include/dcelem.h ../include/dcitem.h ../include/dcvrui.h \
 ../include/dcbytstr.h ../include/dclist.h ../include/dcmetinf.h \
 ../include/dcdatset.h ../include/dcsequen.h ../include/dcfilefo.h \
 ../include/dicomdir/dcdicdir.h ../include/dicomdir/dcdirrec.h \
 ../include/dcvrulup.h ../include/dcvrul.h ../include/dcpixseq.h \
 ../include/dcvrae.h ../include/dcvras.h ../include/dcvrcs.h \
 ../include/dcvrda.h ../include/dcvrds.h ../include/dcvrdt.h \
 ../include/dcvris.h ../include/dcvrtm.h ../include/dcchrstr.h \
 ../include/dcvrlo.h ../include/dcvrlt.h ../include/dcvrpn.h \
 ../include/dcvrsh.h ../include/dcvrst.h ../include/dcvrobow.h \
 ../include/dcpxitem.h ../include/dcvrat.h ../include/dcvrss.h \
 ../include/dcvrus.h ../include/dcvrsl.h ../include/dcvrfl.h \
 ../include/dcvrfd.h ../include/dcdebug.h
ppm2dcm.o: ppm2dcm.cc ../include/dctk.h ../include/dctypes.h \
 ../include/dcswap.h ../include/dcstream.h ../include/dcvr.h \
 ../include/dcdicenu.h ../include/ddicenuz.i ../include/dcxfer.h \
 ../include/dcobject.h ../include/dctag.h ../include/dcstack.h \
 ../include/dcelem.h ../include/dcitem.h ../include/dcvrui.h \
 ../include/dcbytstr.h ../include/dclist.h ../include/dcmetinf.h \
 ../include/dcdatset.h ../include/dcsequen.h ../include/dcfilefo.h \
 ../include/dicomdir/dcdicdir.h ../include/dicomdir/dcdirrec.h \
 ../include/dcvrulup.h ../include/dcvrul.h ../include/dcpixseq.h \
 ../include/dcvrae.h ../include/dcvras.h ../include/dcvrcs.h \
 ../include/dcvrda.h ../include/dcvrds.h ../include/dcvrdt.h \
 ../include/dcvris.h ../include/dcvrtm.h ../include/dcchrstr.h \
 ../include/dcvrlo.h ../include/dcvrlt.h ../include/dcvrpn.h \
 ../include/dcvrsh.h ../include/dcvrst.h ../include/dcvrobow.h \
 ../include/dcpxitem.h ../include/dcvrat.h ../include/dcvrss.h \
 ../include/dcvrus.h ../include/dcvrsl.h ../include/dcvrfl.h \
 ../include/dcvrfd.h ../include/dcdebug.h dcmutils.h dcimapix.h
