.TH "dcm2pdf" 1 "Mon Dec 15 2025" "Version 3.7.0" "OFFIS DCMTK" \" -*- nroff -*-
.nh
.SH NAME
dcm2pdf \- Extract PDF file from DICOM encapsulated PDF

.SH "SYNOPSIS"
.PP
.PP
.nf
dcm2pdf [options] dcmfile-in pdffile-out
.fi
.PP
.SH "DESCRIPTION"
.PP
The \fBdcm2pdf\fP tool is deprecated\&. Use \fBdcmdecap\fP instead, which supports the same command line parameters, and more\&.
.SH "SEE ALSO"
.PP
\fBdcmdecap\fP(1)
.SH "COPYRIGHT"
.PP
Copyright (C) 2007-2025 by OFFIS e\&.V\&., Escherweg 2, 26121 Oldenburg, Germany\&.
