.TH "dcmgpdir" 1 "Mon Dec 16 2024 12:00:01" "Version 3.6.9" "OFFIS DCMTK" \" -*- nroff -*-
.nh
.SH NAME
dcmgpdir \- Create a general purpose DICOMDIR 
.PP

.SH "SYNOPSIS"
.PP
.PP
.nf
dcmgpdir [options] [dcmfile-in\&.\&.\&.]
.fi
.PP
.SH "DESCRIPTION"
.PP
The \fBdcmgpdir\fP tool is deprecated\&. Use \fBdcmmkdir\fP instead, which supports the same command line parameters, and more\&.
.SH "SEE ALSO"
.PP
\fBdcmmkdir\fP(1)
.SH "COPYRIGHT"
.PP
Copyright (C) 1996-2024 by OFFIS e\&.V\&., Escherweg 2, 26121 Oldenburg, Germany\&. 
