.TH "dcmj2pnm" 1 "Mon Dec 16 2024 12:00:01" "Version 3.6.9" "OFFIS DCMTK" \" -*- nroff -*-
.nh
.SH NAME
dcmj2pnm \- Convert DICOM images to PGM/PPM, PNG, TIFF, JPEG or BMP 
.PP

.SH "SYNOPSIS"
.PP
.PP
.nf
dcmj2pnm [options] dcmfile-in [bitmap-out]
.fi
.PP
.SH "DESCRIPTION"
.PP
The \fBdcmj2pnm\fP tool is deprecated\&. Use \fBdcm2img\fP instead, which supports the same command line parameters, and more\&.
.SH "SEE ALSO"
.PP
\fBdcm2img\fP(1)
.SH "COPYRIGHT"
.PP
Copyright (C) 2001-2024 by OFFIS e\&.V\&., Escherweg 2, 26121 Oldenburg, Germany\&. 
