.TH "mkcsmapper" 1 "Tue Dec 19 2023" "Version 3.6.8" "OFFIS DCMTK" \" -*- nroff -*-
.nh
.SH NAME
mkcsmapper \- Create csmapper conversion files for oficonv

.SH "SYNOPSIS"
.PP
.PP
.nf
mkcsmapper [-d] [-m | -p] [-o outfile] [infile]
.fi
.PP
.SH "DESCRIPTION"
.PP
The \fBmkcsmapper\fP utility generates binary conversion data from plain text conversion tables for the oficonv library\&. The conversion data has three components: The conversion mapping between specific character encodings, a directory of available mapping files, and a pivot file, which contains the possible source and destination encoding pairs or the set of mappings to use for a compound encoding\&.
.SH "PARAMETERS"
.PP
.PP
.nf
infile  input file (from oficonv/datasrc/csmapper) to be converted
.fi
.PP
.SH "OPTIONS"
.PP
.SS "general options"
.PP
.nf
  -d    debug mode, print debug information

  -m    create directory of available mapping files

  -p    create pivot file

  -o    [f]ilename: string
        store output in file f
.fi
.PP
.SH "EXIT STATUS"
.PP
The \fBmkcsmapper\fP utility exits 0 on success, and >0 if an error occurs\&.
.SH "SEE ALSO"
.PP
\fBmkesdb\fP(1)
.SH "COPYRIGHT"
.PP
This man page is derived from the FreeBSD mkcsmapper man page, Copyright (C) 2009 Gabor Kovesdan gabor@FreeBSD.org
