.TH "stl2dcm" 1 "Mon Dec 15 2025" "Version 3.7.0" "OFFIS DCMTK" \" -*- nroff -*-
.nh
.SH NAME
stl2dcm \- Encapsulate STL file into DICOM file format

.SH "SYNOPSIS"
.PP
.PP
.nf
stl2dcm [options] stlfile-in dcmfile-out
.fi
.PP
.SH "DESCRIPTION"
.PP
The \fBstl2dcm\fP tool is deprecated\&. Use \fBdcmencap\fP instead, which supports the same command line parameters, and more\&.
.SH "SEE ALSO"
.PP
\fBdcmencap\fP(1)
.SH "COPYRIGHT"
.PP
Copyright (C) 2018-2025 by OFFIS e\&.V\&., Escherweg 2, 26121 Oldenburg, Germany\&.
