xml2dcm.o: xml2dcm.cc ../../config/include/dcmtk/config/osconfig.h \
 ../include/dcmtk/dcmdata/dcmxml/xml2dcm.h \
 ../include/dcmtk/dcmdata/dcmxml/dcxmldf.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h
