xml2dcm.o: xml2dcm.cc ../../config/include/dcmtk/config/osconfig.h \
 ../include/dcmtk/dcmdata/dcmxml/xml2dcm.h \
 ../include/dcmtk/dcmdata/dcmxml/dcxmldf.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../../ofstd/include/dcmtk/ofstd/ofdiag.h \
 ../../ofstd/include/dcmtk/ofstd/diag/push.def \
 ../../ofstd/include/dcmtk/ofstd/diag/useafree.def \
 ../../ofstd/include/dcmtk/ofstd/diag/pop.def \
 ../include/dcmtk/dcmdata/dcxfer.h ../include/dcmtk/dcmdata/dctypes.h \
 ../../oflog/include/dcmtk/oflog/oflog.h \
 ../../oflog/include/dcmtk/oflog/logger.h \
 ../../oflog/include/dcmtk/oflog/config.h \
 ../../oflog/include/dcmtk/oflog/config/defines.h \
 ../../oflog/include/dcmtk/oflog/helpers/threadcf.h \
 ../../oflog/include/dcmtk/oflog/loglevel.h \
 ../../ofstd/include/dcmtk/ofstd/ofvector.h \
 ../../oflog/include/dcmtk/oflog/tstring.h \
 ../../oflog/include/dcmtk/oflog/tchar.h \
 ../../oflog/include/dcmtk/oflog/spi/apndatch.h \
 ../../oflog/include/dcmtk/oflog/appender.h \
 ../../ofstd/include/dcmtk/ofstd/ofmem.h \
 ../../ofstd/include/dcmtk/ofstd/ofutil.h \
 ../../ofstd/include/dcmtk/ofstd/oftraits.h \
 ../../ofstd/include/dcmtk/ofstd/variadic/tuplefwd.h \
 ../../oflog/include/dcmtk/oflog/layout.h \
 ../../oflog/include/dcmtk/oflog/streams.h \
 ../../oflog/include/dcmtk/oflog/helpers/pointer.h \
 ../../oflog/include/dcmtk/oflog/thread/syncprim.h \
 ../../oflog/include/dcmtk/oflog/spi/filter.h \
 ../../oflog/include/dcmtk/oflog/helpers/lockfile.h \
 ../../oflog/include/dcmtk/oflog/spi/logfact.h \
 ../../oflog/include/dcmtk/oflog/logmacro.h \
 ../../oflog/include/dcmtk/oflog/helpers/snprintf.h \
 ../../oflog/include/dcmtk/oflog/tracelog.h \
 ../include/dcmtk/dcmdata/dcdefine.h ../include/dcmtk/dcmdata/dcvr.h \
 ../../ofstd/include/dcmtk/ofstd/ofglobal.h \
 ../../ofstd/include/dcmtk/ofstd/ofthread.h \
 ../../ofstd/include/dcmtk/ofstd/ofdeprec.h \
 ../include/dcmtk/dcmdata/dcsequen.h \
 ../../ofstd/include/dcmtk/ofstd/offile.h \
 ../../ofstd/include/dcmtk/ofstd/ofstd.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../../ofstd/include/dcmtk/ofstd/oflimits.h \
 ../../ofstd/include/dcmtk/ofstd/oferror.h \
 ../include/dcmtk/dcmdata/dcelem.h ../include/dcmtk/dcmdata/dcobject.h \
 ../include/dcmtk/dcmdata/dcerror.h ../include/dcmtk/dcmdata/dctag.h \
 ../include/dcmtk/dcmdata/dctagkey.h \
 ../../ofstd/include/dcmtk/ofstd/diag/ignrattr.def \
 ../include/dcmtk/dcmdata/dcstack.h ../include/dcmtk/dcmdata/dclist.h \
 ../include/dcmtk/dcmdata/dcitem.h ../include/dcmtk/dcmdata/dcpcache.h \
 ../include/dcmtk/dcmdata/dcpixseq.h ../include/dcmtk/dcmdata/dcofsetl.h \
 ../include/dcmtk/dcmdata/dcpixel.h ../include/dcmtk/dcmdata/dcvrpobw.h \
 ../include/dcmtk/dcmdata/dcvrobow.h ../include/dcmtk/dcmdata/dcpxitem.h \
 ../include/dcmtk/dcmdata/dcdeftag.h ../include/dcmtk/dcmdata/dcfilefo.h \
 ../include/dcmtk/dcmdata/dcdatset.h ../include/dcmtk/dcmdata/dcmetinf.h \
 ../include/dcmtk/dcmdata/dcswap.h
