dcmdspfn.o: dcmdspfn.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../dcmdata/include/dctk.h \
  ../../dcmdata/include/dctypes.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/ofstdinc.h ../../dcmdata/include/dcswap.h \
  ../../dcmdata/include/dcerror.h ../../ofstd/include/ofcond.h \
  ../../ofstd/include/ofstring.h ../../ofstd/include/ofcast.h \
  ../../ofstd/include/ofstream.h ../../dcmdata/include/dcxfer.h \
  ../../dcmdata/include/dcvr.h ../../ofstd/include/ofglobal.h \
  ../../ofstd/include/ofthread.h ../../dcmdata/include/dcistrma.h \
  ../../dcmdata/include/dcostrma.h ../../dcmdata/include/dcuid.h \
  ../../dcmdata/include/dcvm.h ../../dcmdata/include/dcdefine.h \
  ../../dcmdata/include/dcdebug.h ../../dcmdata/include/dctagkey.h \
  ../../dcmdata/include/dctag.h ../../dcmdata/include/dcdicent.h \
  ../../dcmdata/include/dchashdi.h ../../ofstd/include/oflist.h \
  ../../dcmdata/include/dcdict.h ../../dcmdata/include/dcdeftag.h \
  ../../dcmdata/include/dcobject.h ../../ofstd/include/ofconsol.h \
  ../../dcmdata/include/dclist.h ../../dcmdata/include/dcstack.h \
  ../../dcmdata/include/dcelem.h ../../dcmdata/include/dcitem.h \
  ../../dcmdata/include/dcvrui.h ../../dcmdata/include/dcbytstr.h \
  ../../dcmdata/include/dcpcache.h ../../dcmdata/include/dcmetinf.h \
  ../../dcmdata/include/dcdatset.h ../../dcmdata/include/dcsequen.h \
  ../../dcmdata/include/dcfilefo.h ../../dcmdata/include/dcdicdir.h \
  ../../dcmdata/include/dcdirrec.h ../../dcmdata/include/dcvrulup.h \
  ../../dcmdata/include/dcvrul.h ../../dcmdata/include/dcpixseq.h \
  ../../dcmdata/include/dcofsetl.h ../../dcmdata/include/dcvrae.h \
  ../../dcmdata/include/dcvras.h ../../dcmdata/include/dcvrcs.h \
  ../../dcmdata/include/dcvrda.h ../../ofstd/include/ofdate.h \
  ../../dcmdata/include/dcvrds.h ../../dcmdata/include/dcvrdt.h \
  ../../ofstd/include/ofdatime.h ../../ofstd/include/oftime.h \
  ../../dcmdata/include/dcvris.h ../../dcmdata/include/dcvrtm.h \
  ../../dcmdata/include/dcchrstr.h ../../dcmdata/include/dcvrlo.h \
  ../../dcmdata/include/dcvrlt.h ../../dcmdata/include/dcvrpn.h \
  ../../dcmdata/include/dcvrsh.h ../../dcmdata/include/dcvrst.h \
  ../../dcmdata/include/dcvrut.h ../../dcmdata/include/dcvrobow.h \
  ../../dcmdata/include/dcpixel.h ../../dcmdata/include/dcvrpobw.h \
  ../../dcmdata/include/dcovlay.h ../../dcmdata/include/dcvrat.h \
  ../../dcmdata/include/dcvrss.h ../../dcmdata/include/dcvrus.h \
  ../../dcmdata/include/dcvrsl.h ../../dcmdata/include/dcvrfl.h \
  ../../dcmdata/include/dcvrfd.h ../../dcmdata/include/dcvrof.h \
  ../../dcmdata/include/cmdlnarg.h ../../ofstd/include/ofconapp.h \
  ../../ofstd/include/ofcmdln.h ../include/digsdfn.h \
  ../include/didispfn.h ../include/didislut.h ../include/dibaslut.h \
  ../include/diutils.h ../include/digsdlut.h ../include/diciefn.h \
  ../include/dicielut.h
dcod2lum.o: dcod2lum.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofstdinc.h \
  ../../ofstd/include/ofstream.h ../../ofstd/include/ofconsol.h \
  ../../ofstd/include/ofthread.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/ofstring.h ../../ofstd/include/ofcast.h \
  ../include/didispfn.h ../include/didislut.h ../include/dibaslut.h \
  ../include/diutils.h ../../dcmdata/include/dctypes.h \
  ../../ofstd/include/ofglobal.h ../../dcmdata/include/dcuid.h
dconvlum.o: dconvlum.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofstdinc.h \
  ../../ofstd/include/ofstream.h ../../ofstd/include/ofconsol.h \
  ../../ofstd/include/ofthread.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/ofstring.h ../../ofstd/include/ofcast.h \
  ../../ofstd/include/ofstd.h ../../ofstd/include/oflist.h \
  ../../dcmdata/include/dcuid.h ../../dcmdata/include/dctypes.h
