wlcefs.o: wlcefs.cc ../../config/include/osconfig.h \
 ../../config/include/cfunix.h ../../dcmnet/include/dicom.h \
 ../../ofstd/include/ofstdinc.h ../../dcmnet/include/cond.h \
 ../../ofstd/include/ofconsol.h ../../ofstd/include/ofstream.h \
 ../../ofstd/include/ofthread.h ../../ofstd/include/oftypes.h \
 ../../dcmdata/include/dcerror.h ../../ofstd/include/ofcond.h \
 ../../ofstd/include/ofstring.h ../../dcmnet/include/dcompat.h \
 ../../ofstd/include/ofbmanip.h ../../dcmdata/include/dctypes.h \
 ../../dcmdata/include/dcuid.h ../../ofstd/include/ofcmdln.h \
 ../../ofstd/include/oflist.h ../include/wltypdef.h \
 ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
 ../../ofstd/include/ofglobal.h ../../ofstd/include/ofconapp.h \
 ../../dcmnet/include/assoc.h ../../dcmnet/include/lst.h \
 ../../dcmnet/include/dul.h ../../dcmnet/include/extneg.h \
 ../../dcmdata/include/cmdlnarg.h ../../dcmnet/include/dimse.h \
 ../../dcmdata/include/dcdatset.h ../../dcmdata/include/dcitem.h \
 ../../dcmdata/include/dcobject.h ../../dcmdata/include/dctag.h \
 ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dclist.h \
 ../../dcmdata/include/dcstack.h ../../dcmdata/include/dcvrui.h \
 ../../dcmdata/include/dcbytstr.h ../../dcmdata/include/dcelem.h \
 ../../dcmdata/include/dcpcache.h ../../dcmdata/include/dcdebug.h \
 ../../dcmdata/include/dcvrat.h ../../dcmdata/include/dcvrlo.h \
 ../../dcmdata/include/dcchrstr.h ../include/wlds.h \
 ../../dcmdata/include/dcsequen.h ../include/wldsfs.h \
 ../include/wlmactmg.h wlcefs.h
wlmscpfs.o: wlmscpfs.cc ../../config/include/osconfig.h \
 ../../config/include/cfunix.h ../../dcmnet/include/dicom.h \
 ../../ofstd/include/ofstdinc.h ../../dcmnet/include/cond.h \
 ../../ofstd/include/ofconsol.h ../../ofstd/include/ofstream.h \
 ../../ofstd/include/ofthread.h ../../ofstd/include/oftypes.h \
 ../../dcmdata/include/dcerror.h ../../ofstd/include/ofcond.h \
 ../../ofstd/include/ofstring.h ../../dcmnet/include/dcompat.h \
 ../../ofstd/include/ofbmanip.h ../../dcmdata/include/dctypes.h \
 ../../dcmdata/include/dcuid.h ../../ofstd/include/ofcmdln.h \
 ../../ofstd/include/oflist.h ../include/wltypdef.h \
 ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
 ../../ofstd/include/ofglobal.h ../../ofstd/include/ofconapp.h \
 wlcefs.h ../include/wlds.h ../include/wldsfs.h
