msgserv.o: msgserv.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofstdinc.h \
  ../include/dvpsmsg.h ../../dcmdata/include/dctypes.h \
  ../../ofstd/include/oftypes.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../../ofstd/include/ofstream.h \
  ../../dcmdata/include/cmdlnarg.h ../../ofstd/include/ofconapp.h \
  ../../ofstd/include/ofcmdln.h ../../ofstd/include/oflist.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofthread.h \
  ../../dcmdata/include/dcdebug.h ../../ofstd/include/ofglobal.h \
  ../../dcmnet/include/dcmtrans.h ../../dcmnet/include/dcmlayer.h \
  ../../dcmdata/include/dcuid.h ../../dcmnet/include/dcompat.h \
  ../../ofstd/include/ofbmanip.h
