dcmqridx.o: dcmqridx.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofstdinc.h \
  ../../dcmnet/include/dicom.h ../../dcmnet/include/cond.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofstream.h \
  ../../ofstd/include/ofthread.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/ofstring.h ../../ofstd/include/ofcast.h \
  ../../dcmdata/include/dcerror.h ../../ofstd/include/ofcond.h \
  ../../dcmnet/include/dcompat.h ../../ofstd/include/ofbmanip.h \
  ../../dcmdata/include/dctypes.h ../../dcmdata/include/dcuid.h \
  ../include/dcmqrdbs.h ../include/dcmqrdbi.h ../include/dcmqrdba.h \
  ../../dcmnet/include/dimse.h ../../dcmnet/include/lst.h \
  ../../ofstd/include/oflist.h ../../dcmnet/include/dul.h \
  ../../ofstd/include/ofglobal.h ../../dcmnet/include/extneg.h \
  ../../dcmnet/include/assoc.h ../../dcmdata/include/dcdatset.h \
  ../../dcmdata/include/dcitem.h ../../dcmdata/include/dcobject.h \
  ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
  ../../dcmdata/include/dctag.h ../../dcmdata/include/dctagkey.h \
  ../../dcmdata/include/dclist.h ../../dcmdata/include/dcstack.h \
  ../../dcmdata/include/dcvrui.h ../../dcmdata/include/dcbytstr.h \
  ../../dcmdata/include/dcelem.h ../../dcmdata/include/dcpcache.h \
  ../../ofstd/include/offname.h ../../dcmnet/include/diutil.h \
  ../../dcmdata/include/dcdebug.h ../../dcmdata/include/dcdict.h \
  ../../dcmdata/include/dchashdi.h ../../dcmdata/include/cmdlnarg.h \
  ../../ofstd/include/ofconapp.h ../../ofstd/include/ofcmdln.h
dcmqrscp.o: dcmqrscp.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofstdinc.h \
  ../../dcmnet/include/dicom.h ../../dcmnet/include/cond.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofstream.h \
  ../../ofstd/include/ofthread.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/ofstring.h ../../ofstd/include/ofcast.h \
  ../../dcmdata/include/dcerror.h ../../ofstd/include/ofcond.h \
  ../../dcmnet/include/dcompat.h ../../ofstd/include/ofbmanip.h \
  ../../dcmdata/include/dctypes.h ../../dcmdata/include/dcuid.h \
  ../include/dcmqropt.h ../../dcmdata/include/dcxfer.h \
  ../../dcmdata/include/dcvr.h ../../ofstd/include/ofglobal.h \
  ../../dcmnet/include/assoc.h ../../dcmnet/include/lst.h \
  ../../ofstd/include/oflist.h ../../dcmnet/include/dul.h \
  ../../dcmnet/include/extneg.h ../include/dcmqrcnf.h \
  ../../ofstd/include/ofcmdln.h ../../ofstd/include/ofconapp.h \
  ../../dcmnet/include/dimse.h ../../dcmdata/include/dcdatset.h \
  ../../dcmdata/include/dcitem.h ../../dcmdata/include/dcobject.h \
  ../../dcmdata/include/dctag.h ../../dcmdata/include/dctagkey.h \
  ../../dcmdata/include/dclist.h ../../dcmdata/include/dcstack.h \
  ../../dcmdata/include/dcvrui.h ../../dcmdata/include/dcbytstr.h \
  ../../dcmdata/include/dcelem.h ../../dcmdata/include/dcpcache.h \
  ../include/dcmqrscp.h ../include/dcmqrptb.h \
  ../../dcmdata/include/dcdict.h ../../dcmdata/include/dchashdi.h \
  ../../dcmdata/include/dcdebug.h ../../dcmdata/include/cmdlnarg.h \
  ../include/dcmqrdbi.h ../include/dcmqrdba.h \
  ../../ofstd/include/offname.h
dcmqrti.o: dcmqrti.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofstdinc.h \
  ../include/dcmqrtis.h ../../dcmnet/include/dicom.h \
  ../../dcmnet/include/cond.h ../../ofstd/include/ofconsol.h \
  ../../ofstd/include/ofstream.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/oftypes.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../../dcmdata/include/dcerror.h \
  ../../ofstd/include/ofcond.h ../../dcmnet/include/dcompat.h \
  ../../ofstd/include/ofbmanip.h ../../dcmdata/include/dctypes.h \
  ../../dcmdata/include/dcuid.h ../../dcmnet/include/assoc.h \
  ../../dcmnet/include/lst.h ../../ofstd/include/oflist.h \
  ../../dcmnet/include/dul.h ../../ofstd/include/ofglobal.h \
  ../../dcmnet/include/extneg.h ../../dcmnet/include/dimse.h \
  ../../dcmdata/include/dcdatset.h ../../dcmdata/include/dcitem.h \
  ../../dcmdata/include/dcobject.h ../../dcmdata/include/dcxfer.h \
  ../../dcmdata/include/dcvr.h ../../dcmdata/include/dctag.h \
  ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dclist.h \
  ../../dcmdata/include/dcstack.h ../../dcmdata/include/dcvrui.h \
  ../../dcmdata/include/dcbytstr.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcpcache.h ../../ofstd/include/ofcmdln.h \
  ../include/dcmqrcnf.h ../../dcmdata/include/dcdict.h \
  ../../dcmdata/include/dchashdi.h ../../dcmdata/include/cmdlnarg.h \
  ../../dcmdata/include/dcdebug.h ../../ofstd/include/ofconapp.h
