i2d.o: i2d.cc ../../config/include/dcmtk/config/osconfig.h \
 ../include/dcmtk/dcmdata/libi2d/i2d.h \
 ../include/dcmtk/dcmdata/libi2d/i2doutpl.h \
 ../../oflog/include/dcmtk/oflog/oflog.h \
 ../../oflog/include/dcmtk/oflog/logger.h \
 ../../oflog/include/dcmtk/oflog/config.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../oflog/include/dcmtk/oflog/config/defines.h \
 ../../oflog/include/dcmtk/oflog/helpers/threadcf.h \
 ../../oflog/include/dcmtk/oflog/loglevel.h \
 ../../ofstd/include/dcmtk/ofstd/ofvector.h \
 ../../oflog/include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../../oflog/include/dcmtk/oflog/tchar.h \
 ../../oflog/include/dcmtk/oflog/spi/apndatch.h \
 ../../oflog/include/dcmtk/oflog/appender.h \
 ../../ofstd/include/dcmtk/ofstd/ofmem.h \
 ../../ofstd/include/dcmtk/ofstd/ofutil.h \
 ../../ofstd/include/dcmtk/ofstd/oftraits.h \
 ../../ofstd/include/dcmtk/ofstd/variadic/tuplefwd.h \
 ../../oflog/include/dcmtk/oflog/layout.h \
 ../../oflog/include/dcmtk/oflog/streams.h \
 ../../oflog/include/dcmtk/oflog/helpers/pointer.h \
 ../../oflog/include/dcmtk/oflog/thread/syncprim.h \
 ../../oflog/include/dcmtk/oflog/spi/filter.h \
 ../../oflog/include/dcmtk/oflog/helpers/lockfile.h \
 ../../oflog/include/dcmtk/oflog/spi/logfact.h \
 ../../oflog/include/dcmtk/oflog/logmacro.h \
 ../../oflog/include/dcmtk/oflog/helpers/snprintf.h \
 ../../oflog/include/dcmtk/oflog/tracelog.h \
 ../../ofstd/include/dcmtk/ofstd/ofconapp.h \
 ../../ofstd/include/dcmtk/ofstd/ofcmdln.h \
 ../../ofstd/include/dcmtk/ofstd/ofexbl.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../../ofstd/include/dcmtk/ofstd/ofconsol.h \
 ../../ofstd/include/dcmtk/ofstd/ofthread.h \
 ../../ofstd/include/dcmtk/ofstd/offile.h \
 ../../ofstd/include/dcmtk/ofstd/ofstd.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/oflimits.h \
 ../../config/include/dcmtk/config/arith.h \
 ../../ofstd/include/dcmtk/ofstd/oferror.h \
 ../../ofstd/include/dcmtk/ofstd/ofexit.h \
 ../include/dcmtk/dcmdata/dcdatset.h ../include/dcmtk/dcmdata/dcitem.h \
 ../include/dcmtk/dcmdata/dctypes.h ../include/dcmtk/dcmdata/dcdefine.h \
 ../include/dcmtk/dcmdata/dcobject.h \
 ../../ofstd/include/dcmtk/ofstd/ofglobal.h \
 ../include/dcmtk/dcmdata/dcerror.h ../include/dcmtk/dcmdata/dcxfer.h \
 ../include/dcmtk/dcmdata/dcvr.h ../include/dcmtk/dcmdata/dctag.h \
 ../include/dcmtk/dcmdata/dctagkey.h ../include/dcmtk/dcmdata/dcstack.h \
 ../include/dcmtk/dcmdata/dclist.h ../include/dcmtk/dcmdata/dcpcache.h \
 ../include/dcmtk/dcmdata/dcelem.h \
 ../include/dcmtk/dcmdata/libi2d/i2define.h \
 ../include/dcmtk/dcmdata/libi2d/i2dimgs.h \
 ../include/dcmtk/dcmdata/dcpixel.h ../include/dcmtk/dcmdata/dcvrpobw.h \
 ../include/dcmtk/dcmdata/dcvrobow.h ../include/dcmtk/dcmdata/dcpxitem.h \
 ../include/dcmtk/dcmdata/dcofsetl.h ../include/dcmtk/dcmdata/dcfilefo.h \
 ../include/dcmtk/dcmdata/dcsequen.h ../include/dcmtk/dcmdata/dcdeftag.h \
 ../include/dcmtk/dcmdata/dcuid.h ../include/dcmtk/dcmdata/dcpixseq.h \
 ../include/dcmtk/dcmdata/dcpath.h
i2dbmps.o: i2dbmps.cc ../../config/include/dcmtk/config/osconfig.h \
 ../include/dcmtk/dcmdata/libi2d/i2dbmps.h \
 ../include/dcmtk/dcmdata/libi2d/i2dimgs.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../include/dcmtk/dcmdata/dcxfer.h ../include/dcmtk/dcmdata/dctypes.h \
 ../../oflog/include/dcmtk/oflog/oflog.h \
 ../../oflog/include/dcmtk/oflog/logger.h \
 ../../oflog/include/dcmtk/oflog/config.h \
 ../../oflog/include/dcmtk/oflog/config/defines.h \
 ../../oflog/include/dcmtk/oflog/helpers/threadcf.h \
 ../../oflog/include/dcmtk/oflog/loglevel.h \
 ../../ofstd/include/dcmtk/ofstd/ofvector.h \
 ../../oflog/include/dcmtk/oflog/tstring.h \
 ../../oflog/include/dcmtk/oflog/tchar.h \
 ../../oflog/include/dcmtk/oflog/spi/apndatch.h \
 ../../oflog/include/dcmtk/oflog/appender.h \
 ../../ofstd/include/dcmtk/ofstd/ofmem.h \
 ../../ofstd/include/dcmtk/ofstd/ofutil.h \
 ../../ofstd/include/dcmtk/ofstd/oftraits.h \
 ../../ofstd/include/dcmtk/ofstd/variadic/tuplefwd.h \
 ../../oflog/include/dcmtk/oflog/layout.h \
 ../../oflog/include/dcmtk/oflog/streams.h \
 ../../oflog/include/dcmtk/oflog/helpers/pointer.h \
 ../../oflog/include/dcmtk/oflog/thread/syncprim.h \
 ../../oflog/include/dcmtk/oflog/spi/filter.h \
 ../../oflog/include/dcmtk/oflog/helpers/lockfile.h \
 ../../oflog/include/dcmtk/oflog/spi/logfact.h \
 ../../oflog/include/dcmtk/oflog/logmacro.h \
 ../../oflog/include/dcmtk/oflog/helpers/snprintf.h \
 ../../oflog/include/dcmtk/oflog/tracelog.h \
 ../../ofstd/include/dcmtk/ofstd/ofconapp.h \
 ../../ofstd/include/dcmtk/ofstd/ofcmdln.h \
 ../../ofstd/include/dcmtk/ofstd/ofexbl.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../../ofstd/include/dcmtk/ofstd/ofconsol.h \
 ../../ofstd/include/dcmtk/ofstd/ofthread.h \
 ../../ofstd/include/dcmtk/ofstd/offile.h \
 ../../ofstd/include/dcmtk/ofstd/ofstd.h \
 ../../ofstd/include/dcmtk/ofstd/oflimits.h \
 ../../config/include/dcmtk/config/arith.h \
 ../../ofstd/include/dcmtk/ofstd/oferror.h \
 ../../ofstd/include/dcmtk/ofstd/ofexit.h \
 ../include/dcmtk/dcmdata/dcdefine.h ../include/dcmtk/dcmdata/dcvr.h \
 ../../ofstd/include/dcmtk/ofstd/ofglobal.h \
 ../include/dcmtk/dcmdata/libi2d/i2define.h \
 ../include/dcmtk/dcmdata/dcerror.h \
 ../include/dcmtk/dcmdata/libi2d/i2doutpl.h \
 ../include/dcmtk/dcmdata/dcdatset.h ../include/dcmtk/dcmdata/dcitem.h \
 ../include/dcmtk/dcmdata/dcobject.h ../include/dcmtk/dcmdata/dctag.h \
 ../include/dcmtk/dcmdata/dctagkey.h ../include/dcmtk/dcmdata/dcstack.h \
 ../include/dcmtk/dcmdata/dclist.h ../include/dcmtk/dcmdata/dcpcache.h \
 ../include/dcmtk/dcmdata/dcelem.h
i2djpgs.o: i2djpgs.cc ../../config/include/dcmtk/config/osconfig.h \
 ../include/dcmtk/dcmdata/libi2d/i2djpgs.h \
 ../../ofstd/include/dcmtk/ofstd/offile.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstd.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../../ofstd/include/dcmtk/ofstd/oftraits.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/oflimits.h \
 ../../config/include/dcmtk/config/arith.h \
 ../../ofstd/include/dcmtk/ofstd/oferror.h \
 ../include/dcmtk/dcmdata/libi2d/i2dimgs.h \
 ../include/dcmtk/dcmdata/dcxfer.h ../include/dcmtk/dcmdata/dctypes.h \
 ../../oflog/include/dcmtk/oflog/oflog.h \
 ../../oflog/include/dcmtk/oflog/logger.h \
 ../../oflog/include/dcmtk/oflog/config.h \
 ../../oflog/include/dcmtk/oflog/config/defines.h \
 ../../oflog/include/dcmtk/oflog/helpers/threadcf.h \
 ../../oflog/include/dcmtk/oflog/loglevel.h \
 ../../ofstd/include/dcmtk/ofstd/ofvector.h \
 ../../oflog/include/dcmtk/oflog/tstring.h \
 ../../oflog/include/dcmtk/oflog/tchar.h \
 ../../oflog/include/dcmtk/oflog/spi/apndatch.h \
 ../../oflog/include/dcmtk/oflog/appender.h \
 ../../ofstd/include/dcmtk/ofstd/ofmem.h \
 ../../ofstd/include/dcmtk/ofstd/ofutil.h \
 ../../ofstd/include/dcmtk/ofstd/variadic/tuplefwd.h \
 ../../oflog/include/dcmtk/oflog/layout.h \
 ../../oflog/include/dcmtk/oflog/streams.h \
 ../../oflog/include/dcmtk/oflog/helpers/pointer.h \
 ../../oflog/include/dcmtk/oflog/thread/syncprim.h \
 ../../oflog/include/dcmtk/oflog/spi/filter.h \
 ../../oflog/include/dcmtk/oflog/helpers/lockfile.h \
 ../../oflog/include/dcmtk/oflog/spi/logfact.h \
 ../../oflog/include/dcmtk/oflog/logmacro.h \
 ../../oflog/include/dcmtk/oflog/helpers/snprintf.h \
 ../../oflog/include/dcmtk/oflog/tracelog.h \
 ../../ofstd/include/dcmtk/ofstd/ofconapp.h \
 ../../ofstd/include/dcmtk/ofstd/ofcmdln.h \
 ../../ofstd/include/dcmtk/ofstd/ofexbl.h \
 ../../ofstd/include/dcmtk/ofstd/ofconsol.h \
 ../../ofstd/include/dcmtk/ofstd/ofthread.h \
 ../../ofstd/include/dcmtk/ofstd/ofexit.h \
 ../include/dcmtk/dcmdata/dcdefine.h ../include/dcmtk/dcmdata/dcvr.h \
 ../../ofstd/include/dcmtk/ofstd/ofglobal.h \
 ../include/dcmtk/dcmdata/libi2d/i2define.h \
 ../include/dcmtk/dcmdata/libi2d/i2doutpl.h \
 ../include/dcmtk/dcmdata/dcdatset.h ../include/dcmtk/dcmdata/dcitem.h \
 ../include/dcmtk/dcmdata/dcobject.h ../include/dcmtk/dcmdata/dcerror.h \
 ../include/dcmtk/dcmdata/dctag.h ../include/dcmtk/dcmdata/dctagkey.h \
 ../include/dcmtk/dcmdata/dcstack.h ../include/dcmtk/dcmdata/dclist.h \
 ../include/dcmtk/dcmdata/dcpcache.h ../include/dcmtk/dcmdata/dcelem.h
i2dplnsc.o: i2dplnsc.cc ../../config/include/dcmtk/config/osconfig.h \
 ../include/dcmtk/dcmdata/libi2d/i2dplnsc.h \
 ../include/dcmtk/dcmdata/libi2d/i2doutpl.h \
 ../../oflog/include/dcmtk/oflog/oflog.h \
 ../../oflog/include/dcmtk/oflog/logger.h \
 ../../oflog/include/dcmtk/oflog/config.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../oflog/include/dcmtk/oflog/config/defines.h \
 ../../oflog/include/dcmtk/oflog/helpers/threadcf.h \
 ../../oflog/include/dcmtk/oflog/loglevel.h \
 ../../ofstd/include/dcmtk/ofstd/ofvector.h \
 ../../oflog/include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../../oflog/include/dcmtk/oflog/tchar.h \
 ../../oflog/include/dcmtk/oflog/spi/apndatch.h \
 ../../oflog/include/dcmtk/oflog/appender.h \
 ../../ofstd/include/dcmtk/ofstd/ofmem.h \
 ../../ofstd/include/dcmtk/ofstd/ofutil.h \
 ../../ofstd/include/dcmtk/ofstd/oftraits.h \
 ../../ofstd/include/dcmtk/ofstd/variadic/tuplefwd.h \
 ../../oflog/include/dcmtk/oflog/layout.h \
 ../../oflog/include/dcmtk/oflog/streams.h \
 ../../oflog/include/dcmtk/oflog/helpers/pointer.h \
 ../../oflog/include/dcmtk/oflog/thread/syncprim.h \
 ../../oflog/include/dcmtk/oflog/spi/filter.h \
 ../../oflog/include/dcmtk/oflog/helpers/lockfile.h \
 ../../oflog/include/dcmtk/oflog/spi/logfact.h \
 ../../oflog/include/dcmtk/oflog/logmacro.h \
 ../../oflog/include/dcmtk/oflog/helpers/snprintf.h \
 ../../oflog/include/dcmtk/oflog/tracelog.h \
 ../../ofstd/include/dcmtk/ofstd/ofconapp.h \
 ../../ofstd/include/dcmtk/ofstd/ofcmdln.h \
 ../../ofstd/include/dcmtk/ofstd/ofexbl.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../../ofstd/include/dcmtk/ofstd/ofconsol.h \
 ../../ofstd/include/dcmtk/ofstd/ofthread.h \
 ../../ofstd/include/dcmtk/ofstd/offile.h \
 ../../ofstd/include/dcmtk/ofstd/ofstd.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/oflimits.h \
 ../../config/include/dcmtk/config/arith.h \
 ../../ofstd/include/dcmtk/ofstd/oferror.h \
 ../../ofstd/include/dcmtk/ofstd/ofexit.h \
 ../include/dcmtk/dcmdata/dcdatset.h ../include/dcmtk/dcmdata/dcitem.h \
 ../include/dcmtk/dcmdata/dctypes.h ../include/dcmtk/dcmdata/dcdefine.h \
 ../include/dcmtk/dcmdata/dcobject.h \
 ../../ofstd/include/dcmtk/ofstd/ofglobal.h \
 ../include/dcmtk/dcmdata/dcerror.h ../include/dcmtk/dcmdata/dcxfer.h \
 ../include/dcmtk/dcmdata/dcvr.h ../include/dcmtk/dcmdata/dctag.h \
 ../include/dcmtk/dcmdata/dctagkey.h ../include/dcmtk/dcmdata/dcstack.h \
 ../include/dcmtk/dcmdata/dclist.h ../include/dcmtk/dcmdata/dcpcache.h \
 ../include/dcmtk/dcmdata/dcelem.h \
 ../include/dcmtk/dcmdata/libi2d/i2define.h \
 ../include/dcmtk/dcmdata/dcdeftag.h ../include/dcmtk/dcmdata/dcuid.h
i2dplsc.o: i2dplsc.cc ../../config/include/dcmtk/config/osconfig.h \
 ../include/dcmtk/dcmdata/libi2d/i2dplsc.h \
 ../include/dcmtk/dcmdata/libi2d/i2doutpl.h \
 ../../oflog/include/dcmtk/oflog/oflog.h \
 ../../oflog/include/dcmtk/oflog/logger.h \
 ../../oflog/include/dcmtk/oflog/config.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../oflog/include/dcmtk/oflog/config/defines.h \
 ../../oflog/include/dcmtk/oflog/helpers/threadcf.h \
 ../../oflog/include/dcmtk/oflog/loglevel.h \
 ../../ofstd/include/dcmtk/ofstd/ofvector.h \
 ../../oflog/include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../../oflog/include/dcmtk/oflog/tchar.h \
 ../../oflog/include/dcmtk/oflog/spi/apndatch.h \
 ../../oflog/include/dcmtk/oflog/appender.h \
 ../../ofstd/include/dcmtk/ofstd/ofmem.h \
 ../../ofstd/include/dcmtk/ofstd/ofutil.h \
 ../../ofstd/include/dcmtk/ofstd/oftraits.h \
 ../../ofstd/include/dcmtk/ofstd/variadic/tuplefwd.h \
 ../../oflog/include/dcmtk/oflog/layout.h \
 ../../oflog/include/dcmtk/oflog/streams.h \
 ../../oflog/include/dcmtk/oflog/helpers/pointer.h \
 ../../oflog/include/dcmtk/oflog/thread/syncprim.h \
 ../../oflog/include/dcmtk/oflog/spi/filter.h \
 ../../oflog/include/dcmtk/oflog/helpers/lockfile.h \
 ../../oflog/include/dcmtk/oflog/spi/logfact.h \
 ../../oflog/include/dcmtk/oflog/logmacro.h \
 ../../oflog/include/dcmtk/oflog/helpers/snprintf.h \
 ../../oflog/include/dcmtk/oflog/tracelog.h \
 ../../ofstd/include/dcmtk/ofstd/ofconapp.h \
 ../../ofstd/include/dcmtk/ofstd/ofcmdln.h \
 ../../ofstd/include/dcmtk/ofstd/ofexbl.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../../ofstd/include/dcmtk/ofstd/ofconsol.h \
 ../../ofstd/include/dcmtk/ofstd/ofthread.h \
 ../../ofstd/include/dcmtk/ofstd/offile.h \
 ../../ofstd/include/dcmtk/ofstd/ofstd.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/oflimits.h \
 ../../config/include/dcmtk/config/arith.h \
 ../../ofstd/include/dcmtk/ofstd/oferror.h \
 ../../ofstd/include/dcmtk/ofstd/ofexit.h \
 ../include/dcmtk/dcmdata/dcdatset.h ../include/dcmtk/dcmdata/dcitem.h \
 ../include/dcmtk/dcmdata/dctypes.h ../include/dcmtk/dcmdata/dcdefine.h \
 ../include/dcmtk/dcmdata/dcobject.h \
 ../../ofstd/include/dcmtk/ofstd/ofglobal.h \
 ../include/dcmtk/dcmdata/dcerror.h ../include/dcmtk/dcmdata/dcxfer.h \
 ../include/dcmtk/dcmdata/dcvr.h ../include/dcmtk/dcmdata/dctag.h \
 ../include/dcmtk/dcmdata/dctagkey.h ../include/dcmtk/dcmdata/dcstack.h \
 ../include/dcmtk/dcmdata/dclist.h ../include/dcmtk/dcmdata/dcpcache.h \
 ../include/dcmtk/dcmdata/dcelem.h \
 ../include/dcmtk/dcmdata/libi2d/i2define.h \
 ../include/dcmtk/dcmdata/dcdeftag.h ../include/dcmtk/dcmdata/dcuid.h
i2dplvlp.o: i2dplvlp.cc ../../config/include/dcmtk/config/osconfig.h \
 ../include/dcmtk/dcmdata/libi2d/i2dplvlp.h \
 ../include/dcmtk/dcmdata/libi2d/i2doutpl.h \
 ../../oflog/include/dcmtk/oflog/oflog.h \
 ../../oflog/include/dcmtk/oflog/logger.h \
 ../../oflog/include/dcmtk/oflog/config.h \
 ../../ofstd/include/dcmtk/ofstd/ofdefine.h \
 ../../ofstd/include/dcmtk/ofstd/ofcast.h \
 ../../ofstd/include/dcmtk/ofstd/ofexport.h \
 ../../ofstd/include/dcmtk/ofstd/ofstdinc.h \
 ../../oflog/include/dcmtk/oflog/config/defines.h \
 ../../oflog/include/dcmtk/oflog/helpers/threadcf.h \
 ../../oflog/include/dcmtk/oflog/loglevel.h \
 ../../ofstd/include/dcmtk/ofstd/ofvector.h \
 ../../oflog/include/dcmtk/oflog/tstring.h \
 ../../ofstd/include/dcmtk/ofstd/ofstring.h \
 ../../ofstd/include/dcmtk/ofstd/oftypes.h \
 ../../ofstd/include/dcmtk/ofstd/ofstream.h \
 ../../oflog/include/dcmtk/oflog/tchar.h \
 ../../oflog/include/dcmtk/oflog/spi/apndatch.h \
 ../../oflog/include/dcmtk/oflog/appender.h \
 ../../ofstd/include/dcmtk/ofstd/ofmem.h \
 ../../ofstd/include/dcmtk/ofstd/ofutil.h \
 ../../ofstd/include/dcmtk/ofstd/oftraits.h \
 ../../ofstd/include/dcmtk/ofstd/variadic/tuplefwd.h \
 ../../oflog/include/dcmtk/oflog/layout.h \
 ../../oflog/include/dcmtk/oflog/streams.h \
 ../../oflog/include/dcmtk/oflog/helpers/pointer.h \
 ../../oflog/include/dcmtk/oflog/thread/syncprim.h \
 ../../oflog/include/dcmtk/oflog/spi/filter.h \
 ../../oflog/include/dcmtk/oflog/helpers/lockfile.h \
 ../../oflog/include/dcmtk/oflog/spi/logfact.h \
 ../../oflog/include/dcmtk/oflog/logmacro.h \
 ../../oflog/include/dcmtk/oflog/helpers/snprintf.h \
 ../../oflog/include/dcmtk/oflog/tracelog.h \
 ../../ofstd/include/dcmtk/ofstd/ofconapp.h \
 ../../ofstd/include/dcmtk/ofstd/ofcmdln.h \
 ../../ofstd/include/dcmtk/ofstd/ofexbl.h \
 ../../ofstd/include/dcmtk/ofstd/oflist.h \
 ../../ofstd/include/dcmtk/ofstd/ofconsol.h \
 ../../ofstd/include/dcmtk/ofstd/ofthread.h \
 ../../ofstd/include/dcmtk/ofstd/offile.h \
 ../../ofstd/include/dcmtk/ofstd/ofstd.h \
 ../../ofstd/include/dcmtk/ofstd/ofcond.h \
 ../../ofstd/include/dcmtk/ofstd/oflimits.h \
 ../../config/include/dcmtk/config/arith.h \
 ../../ofstd/include/dcmtk/ofstd/oferror.h \
 ../../ofstd/include/dcmtk/ofstd/ofexit.h \
 ../include/dcmtk/dcmdata/dcdatset.h ../include/dcmtk/dcmdata/dcitem.h \
 ../include/dcmtk/dcmdata/dctypes.h ../include/dcmtk/dcmdata/dcdefine.h \
 ../include/dcmtk/dcmdata/dcobject.h \
 ../../ofstd/include/dcmtk/ofstd/ofglobal.h \
 ../include/dcmtk/dcmdata/dcerror.h ../include/dcmtk/dcmdata/dcxfer.h \
 ../include/dcmtk/dcmdata/dcvr.h ../include/dcmtk/dcmdata/dctag.h \
 ../include/dcmtk/dcmdata/dctagkey.h ../include/dcmtk/dcmdata/dcstack.h \
 ../include/dcmtk/dcmdata/dclist.h ../include/dcmtk/dcmdata/dcpcache.h \
 ../include/dcmtk/dcmdata/dcelem.h \
 ../include/dcmtk/dcmdata/libi2d/i2define.h \
 ../include/dcmtk/dcmdata/dcdeftag.h ../include/dcmtk/dcmdata/dcuid.h
