#
#	Makefile for libraries
#


@SET_MAKE@

SHELL = /bin/sh
VPATH=@srcdir@:@top_srcdir@/include:@top_srcdir@/@configdir@/include
srcdir=@srcdir@
top_srcdir=@top_srcdir@
configdir=@top_srcdir@/@configdir@

# Special defines for the Library, define them in LOCALDEFS

LOCALDEFS= 

include $(configdir)/@common_makefile@

objs= 	#all objects in library

all: library.a



install: all
	$(configdir)/mkinstalldirs $(libdir)
	$(INSTALL_DATA) library.a $(libdir)/library.a


clean:
	(cd $(dicomdir); $(MAKE) clean)
	rm -f $(objs) library.a $(TRASH)

distclean: 
	(cd $(dicomdir); $(MAKE) distclean) 
	rm -f $(objs) library.a $(DISTTRASH)


libdcmdata.a: $(objs) 
	$(AR) $(ARFLAGS) $@ $(objs) 
	$(RANLIB) $@


dependencies:
	$(CXX) -MM $(includes) *.cc  > $(DEP)
	(cd $(dicomdir); touch $(DEP); $(MAKE) dependencies)

$(objs): config.h

include $(DEP)

