ddpiimpl.o: ddpiimpl.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/ddpiimpl.h \
  ../../dcmdata/include/dcddirif.h ../../dcmdata/include/dcdicdir.h \
  ../../ofstd/include/ofconsol.h ../../ofstd/include/ofstream.h \
  ../../ofstd/include/ofthread.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/ofstring.h ../../ofstd/include/ofcast.h \
  ../../ofstd/include/ofstdinc.h ../../dcmdata/include/dctypes.h \
  ../../dcmdata/include/dcitem.h ../../dcmdata/include/dcobject.h \
  ../../ofstd/include/ofglobal.h ../../dcmdata/include/dcerror.h \
  ../../ofstd/include/ofcond.h ../../dcmdata/include/dcxfer.h \
  ../../dcmdata/include/dcvr.h ../../dcmdata/include/dctag.h \
  ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dclist.h \
  ../../dcmdata/include/dcstack.h ../../dcmdata/include/dcvrui.h \
  ../../dcmdata/include/dcbytstr.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcpcache.h ../../ofstd/include/oflist.h \
  ../../dcmdata/include/dcfilefo.h ../../dcmdata/include/dcsequen.h \
  ../../dcmdata/include/dcdatset.h ../../dcmdata/include/dcdirrec.h \
  ../../dcmdata/include/dcvrulup.h ../../dcmdata/include/dcvrul.h \
  ../../dcmimgle/include/dcmimage.h ../../dcmimgle/include/dimoimg.h \
  ../../dcmimgle/include/diimage.h ../../dcmimgle/include/diovlay.h \
  ../../dcmimgle/include/diobjcou.h ../../dcmimgle/include/diovdat.h \
  ../../dcmimgle/include/diovpln.h ../../dcmimgle/include/diutils.h \
  ../../dcmimgle/include/dimopx.h ../../dcmimgle/include/dipixel.h \
  ../../dcmimgle/include/dimomod.h ../../dcmimgle/include/diluptab.h \
  ../../dcmimgle/include/dibaslut.h ../../dcmimgle/include/dimoopx.h \
  ../../dcmimgle/include/didispfn.h ../../dcmimgle/include/didislut.h \
  ../../dcmimgle/include/discalet.h ../../dcmimgle/include/ditranst.h \
  ../../ofstd/include/ofbmanip.h ../../dcmimgle/include/dipxrept.h
dipijpeg.o: dipijpeg.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../../ofstd/include/ofconsol.h \
  ../../ofstd/include/ofstream.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/oftypes.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../../ofstd/include/ofstdinc.h \
  ../../dcmdata/include/dctypes.h ../../dcmimgle/include/diimage.h \
  ../../dcmdata/include/dcitem.h ../../dcmdata/include/dcobject.h \
  ../../ofstd/include/ofglobal.h ../../dcmdata/include/dcerror.h \
  ../../ofstd/include/ofcond.h ../../dcmdata/include/dcxfer.h \
  ../../dcmdata/include/dcvr.h ../../dcmdata/include/dctag.h \
  ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dclist.h \
  ../../dcmdata/include/dcstack.h ../../dcmdata/include/dcvrui.h \
  ../../dcmdata/include/dcbytstr.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcpcache.h ../../ofstd/include/oflist.h \
  ../../dcmimgle/include/diovlay.h ../../dcmimgle/include/diobjcou.h \
  ../../dcmimgle/include/diovdat.h ../../dcmimgle/include/diovpln.h \
  ../../dcmimgle/include/diutils.h ../include/dipijpeg.h \
  ../../dcmimgle/include/diplugin.h ../include/djutils.h \
  ../../dcmjpeg/libijg8/jpeglib8.h ../../dcmjpeg/libijg8/jconfig8.h \
  ../../dcmjpeg/libijg8/jmorecfg8.h ../../dcmjpeg/libijg8/jerror8.h \
  ../../dcmjpeg/libijg8/jpegint8.h ../../dcmjpeg/libijg8/jversion8.h
djcodecd.o: djcodecd.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/djcodecd.h \
  ../../ofstd/include/oftypes.h ../../dcmdata/include/dccodec.h \
  ../../dcmdata/include/dctypes.h ../../ofstd/include/ofstdinc.h \
  ../../dcmdata/include/dcerror.h ../../ofstd/include/ofcond.h \
  ../../ofstd/include/ofstring.h ../../ofstd/include/ofcast.h \
  ../../ofstd/include/ofstream.h ../../dcmdata/include/dcxfer.h \
  ../../dcmdata/include/dcvr.h ../../ofstd/include/ofglobal.h \
  ../../ofstd/include/ofthread.h ../../ofstd/include/oflist.h \
  ../include/djutils.h ../../dcmimgle/include/diutils.h \
  ../../dcmdata/include/dcdatset.h ../../ofstd/include/ofconsol.h \
  ../../dcmdata/include/dcitem.h ../../dcmdata/include/dcobject.h \
  ../../dcmdata/include/dctag.h ../../dcmdata/include/dctagkey.h \
  ../../dcmdata/include/dclist.h ../../dcmdata/include/dcstack.h \
  ../../dcmdata/include/dcvrui.h ../../dcmdata/include/dcbytstr.h \
  ../../dcmdata/include/dcelem.h ../../dcmdata/include/dcpcache.h \
  ../../dcmdata/include/dcdeftag.h ../../dcmdata/include/dcpixseq.h \
  ../../dcmdata/include/dcsequen.h ../../dcmdata/include/dcofsetl.h \
  ../../dcmdata/include/dcpxitem.h ../../dcmdata/include/dcvrobow.h \
  ../../dcmdata/include/dcvrpobw.h ../../dcmdata/include/dcswap.h \
  ../../dcmdata/include/dcuid.h ../include/djcparam.h \
  ../include/djdecabs.h
djcodece.o: djcodece.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/djcodece.h \
  ../../ofstd/include/oftypes.h ../../dcmdata/include/dccodec.h \
  ../../dcmdata/include/dctypes.h ../../ofstd/include/ofstdinc.h \
  ../../dcmdata/include/dcerror.h ../../ofstd/include/ofcond.h \
  ../../ofstd/include/ofstring.h ../../ofstd/include/ofcast.h \
  ../../ofstd/include/ofstream.h ../../dcmdata/include/dcxfer.h \
  ../../dcmdata/include/dcvr.h ../../ofstd/include/ofglobal.h \
  ../../ofstd/include/ofthread.h ../../ofstd/include/oflist.h \
  ../include/djutils.h ../../dcmimgle/include/diutils.h \
  ../../ofstd/include/ofstd.h ../../dcmdata/include/dcdatset.h \
  ../../ofstd/include/ofconsol.h ../../dcmdata/include/dcitem.h \
  ../../dcmdata/include/dcobject.h ../../dcmdata/include/dctag.h \
  ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dclist.h \
  ../../dcmdata/include/dcstack.h ../../dcmdata/include/dcvrui.h \
  ../../dcmdata/include/dcbytstr.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcpcache.h ../../dcmdata/include/dcdeftag.h \
  ../../dcmdata/include/dcovlay.h ../../dcmdata/include/dcvrpobw.h \
  ../../dcmdata/include/dcvrobow.h ../../dcmdata/include/dcpixseq.h \
  ../../dcmdata/include/dcsequen.h ../../dcmdata/include/dcofsetl.h \
  ../../dcmdata/include/dcpxitem.h ../../dcmdata/include/dcuid.h \
  ../../dcmdata/include/dcvrcs.h ../../dcmdata/include/dcvrds.h \
  ../../dcmdata/include/dcvrlt.h ../../dcmdata/include/dcchrstr.h \
  ../../dcmdata/include/dcvrst.h ../../dcmdata/include/dcvrus.h \
  ../../dcmdata/include/dcswap.h ../include/djcparam.h \
  ../include/djencabs.h ../../dcmimgle/include/dcmimage.h \
  ../../dcmimgle/include/dimoimg.h ../../dcmimgle/include/diimage.h \
  ../../dcmimgle/include/diovlay.h ../../dcmimgle/include/diobjcou.h \
  ../../dcmimgle/include/diovdat.h ../../dcmimgle/include/diovpln.h \
  ../../dcmimgle/include/dimopx.h ../../dcmimgle/include/dipixel.h \
  ../../dcmimgle/include/dimomod.h ../../dcmimgle/include/diluptab.h \
  ../../dcmimgle/include/dibaslut.h ../../dcmimgle/include/dimoopx.h \
  ../../dcmimgle/include/didispfn.h ../../dcmimgle/include/didislut.h
djcparam.o: djcparam.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/djcparam.h \
  ../../dcmdata/include/dccodec.h ../../dcmdata/include/dctypes.h \
  ../../ofstd/include/oftypes.h ../../ofstd/include/ofstdinc.h \
  ../../dcmdata/include/dcerror.h ../../ofstd/include/ofcond.h \
  ../../ofstd/include/ofstring.h ../../ofstd/include/ofcast.h \
  ../../ofstd/include/ofstream.h ../../dcmdata/include/dcxfer.h \
  ../../dcmdata/include/dcvr.h ../../ofstd/include/ofglobal.h \
  ../../ofstd/include/ofthread.h ../../ofstd/include/oflist.h \
  ../include/djutils.h ../../dcmimgle/include/diutils.h
djdecbas.o: djdecbas.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/djdecbas.h \
  ../include/djcodecd.h ../../ofstd/include/oftypes.h \
  ../../dcmdata/include/dccodec.h ../../dcmdata/include/dctypes.h \
  ../../ofstd/include/ofstdinc.h ../../dcmdata/include/dcerror.h \
  ../../ofstd/include/ofcond.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../../ofstd/include/ofstream.h \
  ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
  ../../ofstd/include/ofglobal.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/oflist.h ../include/djutils.h \
  ../../dcmimgle/include/diutils.h ../include/djcparam.h \
  ../include/djrploss.h ../../dcmdata/include/dcpixel.h \
  ../../ofstd/include/ofconsol.h ../../dcmdata/include/dcvrpobw.h \
  ../../dcmdata/include/dcvrobow.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcobject.h ../../dcmdata/include/dctag.h \
  ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dclist.h \
  ../../dcmdata/include/dcstack.h ../include/djdijg8.h \
  ../include/djdecabs.h
djdecext.o: djdecext.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/djdecext.h \
  ../include/djcodecd.h ../../ofstd/include/oftypes.h \
  ../../dcmdata/include/dccodec.h ../../dcmdata/include/dctypes.h \
  ../../ofstd/include/ofstdinc.h ../../dcmdata/include/dcerror.h \
  ../../ofstd/include/ofcond.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../../ofstd/include/ofstream.h \
  ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
  ../../ofstd/include/ofglobal.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/oflist.h ../include/djutils.h \
  ../../dcmimgle/include/diutils.h ../include/djcparam.h \
  ../include/djrploss.h ../../dcmdata/include/dcpixel.h \
  ../../ofstd/include/ofconsol.h ../../dcmdata/include/dcvrpobw.h \
  ../../dcmdata/include/dcvrobow.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcobject.h ../../dcmdata/include/dctag.h \
  ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dclist.h \
  ../../dcmdata/include/dcstack.h ../include/djdijg8.h \
  ../include/djdecabs.h ../include/djdijg12.h
djdeclol.o: djdeclol.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/djdeclol.h \
  ../include/djcodecd.h ../../ofstd/include/oftypes.h \
  ../../dcmdata/include/dccodec.h ../../dcmdata/include/dctypes.h \
  ../../ofstd/include/ofstdinc.h ../../dcmdata/include/dcerror.h \
  ../../ofstd/include/ofcond.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../../ofstd/include/ofstream.h \
  ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
  ../../ofstd/include/ofglobal.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/oflist.h ../include/djutils.h \
  ../../dcmimgle/include/diutils.h ../include/djcparam.h \
  ../include/djrplol.h ../../dcmdata/include/dcpixel.h \
  ../../ofstd/include/ofconsol.h ../../dcmdata/include/dcvrpobw.h \
  ../../dcmdata/include/dcvrobow.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcobject.h ../../dcmdata/include/dctag.h \
  ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dclist.h \
  ../../dcmdata/include/dcstack.h ../include/djdijg8.h \
  ../include/djdecabs.h ../include/djdijg12.h ../include/djdijg16.h
djdecode.o: djdecode.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/djdecode.h \
  ../../ofstd/include/oftypes.h ../include/djutils.h \
  ../../ofstd/include/ofcond.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../../ofstd/include/ofstdinc.h \
  ../../ofstd/include/ofstream.h ../../dcmimgle/include/diutils.h \
  ../../dcmdata/include/dctypes.h ../../ofstd/include/ofglobal.h \
  ../../ofstd/include/ofthread.h ../../dcmdata/include/dccodec.h \
  ../../dcmdata/include/dcerror.h ../../dcmdata/include/dcxfer.h \
  ../../dcmdata/include/dcvr.h ../../ofstd/include/oflist.h \
  ../include/djdecbas.h ../include/djcodecd.h ../include/djdecext.h \
  ../include/djdecsps.h ../include/djdecpro.h ../include/djdecsv1.h \
  ../include/djdeclol.h ../include/djcparam.h
djdecpro.o: djdecpro.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/djdecpro.h \
  ../include/djcodecd.h ../../ofstd/include/oftypes.h \
  ../../dcmdata/include/dccodec.h ../../dcmdata/include/dctypes.h \
  ../../ofstd/include/ofstdinc.h ../../dcmdata/include/dcerror.h \
  ../../ofstd/include/ofcond.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../../ofstd/include/ofstream.h \
  ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
  ../../ofstd/include/ofglobal.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/oflist.h ../include/djutils.h \
  ../../dcmimgle/include/diutils.h ../include/djcparam.h \
  ../include/djrploss.h ../../dcmdata/include/dcpixel.h \
  ../../ofstd/include/ofconsol.h ../../dcmdata/include/dcvrpobw.h \
  ../../dcmdata/include/dcvrobow.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcobject.h ../../dcmdata/include/dctag.h \
  ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dclist.h \
  ../../dcmdata/include/dcstack.h ../include/djdijg8.h \
  ../include/djdecabs.h ../include/djdijg12.h
djdecsps.o: djdecsps.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/djdecsps.h \
  ../include/djcodecd.h ../../ofstd/include/oftypes.h \
  ../../dcmdata/include/dccodec.h ../../dcmdata/include/dctypes.h \
  ../../ofstd/include/ofstdinc.h ../../dcmdata/include/dcerror.h \
  ../../ofstd/include/ofcond.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../../ofstd/include/ofstream.h \
  ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
  ../../ofstd/include/ofglobal.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/oflist.h ../include/djutils.h \
  ../../dcmimgle/include/diutils.h ../include/djcparam.h \
  ../include/djrploss.h ../../dcmdata/include/dcpixel.h \
  ../../ofstd/include/ofconsol.h ../../dcmdata/include/dcvrpobw.h \
  ../../dcmdata/include/dcvrobow.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcobject.h ../../dcmdata/include/dctag.h \
  ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dclist.h \
  ../../dcmdata/include/dcstack.h ../include/djdijg8.h \
  ../include/djdecabs.h ../include/djdijg12.h
djdecsv1.o: djdecsv1.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/djdecsv1.h \
  ../include/djcodecd.h ../../ofstd/include/oftypes.h \
  ../../dcmdata/include/dccodec.h ../../dcmdata/include/dctypes.h \
  ../../ofstd/include/ofstdinc.h ../../dcmdata/include/dcerror.h \
  ../../ofstd/include/ofcond.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../../ofstd/include/ofstream.h \
  ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
  ../../ofstd/include/ofglobal.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/oflist.h ../include/djutils.h \
  ../../dcmimgle/include/diutils.h ../include/djcparam.h \
  ../include/djrplol.h ../../dcmdata/include/dcpixel.h \
  ../../ofstd/include/ofconsol.h ../../dcmdata/include/dcvrpobw.h \
  ../../dcmdata/include/dcvrobow.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcobject.h ../../dcmdata/include/dctag.h \
  ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dclist.h \
  ../../dcmdata/include/dcstack.h ../include/djdijg8.h \
  ../include/djdecabs.h ../include/djdijg12.h ../include/djdijg16.h
djdijg12.o: djdijg12.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/djdijg12.h \
  ../include/djdecabs.h ../../dcmdata/include/dctypes.h \
  ../../ofstd/include/oftypes.h ../../ofstd/include/ofstdinc.h \
  ../include/djutils.h ../../ofstd/include/ofcond.h \
  ../../ofstd/include/ofstring.h ../../ofstd/include/ofcast.h \
  ../../ofstd/include/ofstream.h ../../dcmimgle/include/diutils.h \
  ../../ofstd/include/ofglobal.h ../../ofstd/include/ofthread.h \
  ../include/djcparam.h ../../dcmdata/include/dccodec.h \
  ../../dcmdata/include/dcerror.h ../../dcmdata/include/dcxfer.h \
  ../../dcmdata/include/dcvr.h ../../ofstd/include/oflist.h \
  ../../ofstd/include/ofconsol.h ../../dcmjpeg/libijg12/jpeglib12.h \
  ../../dcmjpeg/libijg12/jconfig12.h ../../dcmjpeg/libijg12/jmorecfg12.h \
  ../../dcmjpeg/libijg12/jerror12.h
djdijg16.o: djdijg16.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/djdijg16.h \
  ../include/djdecabs.h ../../dcmdata/include/dctypes.h \
  ../../ofstd/include/oftypes.h ../../ofstd/include/ofstdinc.h \
  ../include/djutils.h ../../ofstd/include/ofcond.h \
  ../../ofstd/include/ofstring.h ../../ofstd/include/ofcast.h \
  ../../ofstd/include/ofstream.h ../../dcmimgle/include/diutils.h \
  ../../ofstd/include/ofglobal.h ../../ofstd/include/ofthread.h \
  ../include/djcparam.h ../../dcmdata/include/dccodec.h \
  ../../dcmdata/include/dcerror.h ../../dcmdata/include/dcxfer.h \
  ../../dcmdata/include/dcvr.h ../../ofstd/include/oflist.h \
  ../../ofstd/include/ofconsol.h ../../dcmjpeg/libijg16/jpeglib16.h \
  ../../dcmjpeg/libijg16/jconfig16.h ../../dcmjpeg/libijg16/jmorecfg16.h \
  ../../dcmjpeg/libijg16/jerror16.h
djdijg8.o: djdijg8.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/djdijg8.h \
  ../include/djdecabs.h ../../dcmdata/include/dctypes.h \
  ../../ofstd/include/oftypes.h ../../ofstd/include/ofstdinc.h \
  ../include/djutils.h ../../ofstd/include/ofcond.h \
  ../../ofstd/include/ofstring.h ../../ofstd/include/ofcast.h \
  ../../ofstd/include/ofstream.h ../../dcmimgle/include/diutils.h \
  ../../ofstd/include/ofglobal.h ../../ofstd/include/ofthread.h \
  ../include/djcparam.h ../../dcmdata/include/dccodec.h \
  ../../dcmdata/include/dcerror.h ../../dcmdata/include/dcxfer.h \
  ../../dcmdata/include/dcvr.h ../../ofstd/include/oflist.h \
  ../../ofstd/include/ofconsol.h ../../dcmjpeg/libijg8/jpeglib8.h \
  ../../dcmjpeg/libijg8/jconfig8.h ../../dcmjpeg/libijg8/jmorecfg8.h \
  ../../dcmjpeg/libijg8/jerror8.h
djeijg12.o: djeijg12.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/djeijg12.h \
  ../../ofstd/include/oflist.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/ofcast.h ../../ofstd/include/ofstdinc.h \
  ../include/djencabs.h ../../dcmdata/include/dctypes.h \
  ../../dcmimgle/include/diutils.h ../../ofstd/include/ofglobal.h \
  ../../ofstd/include/ofthread.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofstream.h ../include/djutils.h \
  ../../ofstd/include/ofcond.h ../include/djcparam.h \
  ../../dcmdata/include/dccodec.h ../../dcmdata/include/dcerror.h \
  ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
  ../../ofstd/include/ofconsol.h ../../dcmjpeg/libijg12/jpeglib12.h \
  ../../dcmjpeg/libijg12/jconfig12.h ../../dcmjpeg/libijg12/jmorecfg12.h \
  ../../dcmjpeg/libijg12/jerror12.h ../../dcmjpeg/libijg12/jpegint12.h
djeijg16.o: djeijg16.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/djeijg16.h \
  ../../ofstd/include/oflist.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/ofcast.h ../../ofstd/include/ofstdinc.h \
  ../include/djencabs.h ../../dcmdata/include/dctypes.h \
  ../../dcmimgle/include/diutils.h ../../ofstd/include/ofglobal.h \
  ../../ofstd/include/ofthread.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofstream.h ../include/djutils.h \
  ../../ofstd/include/ofcond.h ../include/djcparam.h \
  ../../dcmdata/include/dccodec.h ../../dcmdata/include/dcerror.h \
  ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
  ../../ofstd/include/ofconsol.h ../../dcmjpeg/libijg16/jpeglib16.h \
  ../../dcmjpeg/libijg16/jconfig16.h ../../dcmjpeg/libijg16/jmorecfg16.h \
  ../../dcmjpeg/libijg16/jerror16.h ../../dcmjpeg/libijg16/jpegint16.h
djeijg8.o: djeijg8.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/djeijg8.h \
  ../../ofstd/include/oflist.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/ofcast.h ../../ofstd/include/ofstdinc.h \
  ../include/djencabs.h ../../dcmdata/include/dctypes.h \
  ../../dcmimgle/include/diutils.h ../../ofstd/include/ofglobal.h \
  ../../ofstd/include/ofthread.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofstream.h ../include/djutils.h \
  ../../ofstd/include/ofcond.h ../include/djcparam.h \
  ../../dcmdata/include/dccodec.h ../../dcmdata/include/dcerror.h \
  ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
  ../../ofstd/include/ofconsol.h ../../dcmjpeg/libijg8/jpeglib8.h \
  ../../dcmjpeg/libijg8/jconfig8.h ../../dcmjpeg/libijg8/jmorecfg8.h \
  ../../dcmjpeg/libijg8/jerror8.h ../../dcmjpeg/libijg8/jpegint8.h
djencbas.o: djencbas.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/djencbas.h \
  ../include/djcodece.h ../../ofstd/include/oftypes.h \
  ../../dcmdata/include/dccodec.h ../../dcmdata/include/dctypes.h \
  ../../ofstd/include/ofstdinc.h ../../dcmdata/include/dcerror.h \
  ../../ofstd/include/ofcond.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../../ofstd/include/ofstream.h \
  ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
  ../../ofstd/include/ofglobal.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/oflist.h ../include/djutils.h \
  ../../dcmimgle/include/diutils.h ../include/djcparam.h \
  ../include/djrploss.h ../../dcmdata/include/dcpixel.h \
  ../../ofstd/include/ofconsol.h ../../dcmdata/include/dcvrpobw.h \
  ../../dcmdata/include/dcvrobow.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcobject.h ../../dcmdata/include/dctag.h \
  ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dclist.h \
  ../../dcmdata/include/dcstack.h ../include/djeijg8.h \
  ../include/djencabs.h
djencext.o: djencext.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/djencext.h \
  ../include/djcodece.h ../../ofstd/include/oftypes.h \
  ../../dcmdata/include/dccodec.h ../../dcmdata/include/dctypes.h \
  ../../ofstd/include/ofstdinc.h ../../dcmdata/include/dcerror.h \
  ../../ofstd/include/ofcond.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../../ofstd/include/ofstream.h \
  ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
  ../../ofstd/include/ofglobal.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/oflist.h ../include/djutils.h \
  ../../dcmimgle/include/diutils.h ../include/djcparam.h \
  ../include/djrploss.h ../../dcmdata/include/dcpixel.h \
  ../../ofstd/include/ofconsol.h ../../dcmdata/include/dcvrpobw.h \
  ../../dcmdata/include/dcvrobow.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcobject.h ../../dcmdata/include/dctag.h \
  ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dclist.h \
  ../../dcmdata/include/dcstack.h ../include/djeijg8.h \
  ../include/djencabs.h ../include/djeijg12.h
djenclol.o: djenclol.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/djenclol.h \
  ../include/djcodece.h ../../ofstd/include/oftypes.h \
  ../../dcmdata/include/dccodec.h ../../dcmdata/include/dctypes.h \
  ../../ofstd/include/ofstdinc.h ../../dcmdata/include/dcerror.h \
  ../../ofstd/include/ofcond.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../../ofstd/include/ofstream.h \
  ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
  ../../ofstd/include/ofglobal.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/oflist.h ../include/djutils.h \
  ../../dcmimgle/include/diutils.h ../include/djcparam.h \
  ../include/djrplol.h ../../dcmdata/include/dcpixel.h \
  ../../ofstd/include/ofconsol.h ../../dcmdata/include/dcvrpobw.h \
  ../../dcmdata/include/dcvrobow.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcobject.h ../../dcmdata/include/dctag.h \
  ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dclist.h \
  ../../dcmdata/include/dcstack.h ../include/djeijg8.h \
  ../include/djencabs.h ../include/djeijg12.h ../include/djeijg16.h
djencode.o: djencode.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/djencode.h \
  ../../ofstd/include/oftypes.h ../include/djutils.h \
  ../../ofstd/include/ofcond.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../../ofstd/include/ofstdinc.h \
  ../../ofstd/include/ofstream.h ../../dcmimgle/include/diutils.h \
  ../../dcmdata/include/dctypes.h ../../ofstd/include/ofglobal.h \
  ../../ofstd/include/ofthread.h ../../dcmdata/include/dccodec.h \
  ../../dcmdata/include/dcerror.h ../../dcmdata/include/dcxfer.h \
  ../../dcmdata/include/dcvr.h ../../ofstd/include/oflist.h \
  ../include/djencbas.h ../include/djcodece.h ../include/djencext.h \
  ../include/djencsps.h ../include/djencpro.h ../include/djencsv1.h \
  ../include/djenclol.h ../include/djcparam.h
djencpro.o: djencpro.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/djencpro.h \
  ../include/djcodece.h ../../ofstd/include/oftypes.h \
  ../../dcmdata/include/dccodec.h ../../dcmdata/include/dctypes.h \
  ../../ofstd/include/ofstdinc.h ../../dcmdata/include/dcerror.h \
  ../../ofstd/include/ofcond.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../../ofstd/include/ofstream.h \
  ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
  ../../ofstd/include/ofglobal.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/oflist.h ../include/djutils.h \
  ../../dcmimgle/include/diutils.h ../include/djcparam.h \
  ../include/djrploss.h ../../dcmdata/include/dcpixel.h \
  ../../ofstd/include/ofconsol.h ../../dcmdata/include/dcvrpobw.h \
  ../../dcmdata/include/dcvrobow.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcobject.h ../../dcmdata/include/dctag.h \
  ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dclist.h \
  ../../dcmdata/include/dcstack.h ../include/djeijg8.h \
  ../include/djencabs.h ../include/djeijg12.h
djencsps.o: djencsps.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/djencsps.h \
  ../include/djcodece.h ../../ofstd/include/oftypes.h \
  ../../dcmdata/include/dccodec.h ../../dcmdata/include/dctypes.h \
  ../../ofstd/include/ofstdinc.h ../../dcmdata/include/dcerror.h \
  ../../ofstd/include/ofcond.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../../ofstd/include/ofstream.h \
  ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
  ../../ofstd/include/ofglobal.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/oflist.h ../include/djutils.h \
  ../../dcmimgle/include/diutils.h ../include/djcparam.h \
  ../include/djrploss.h ../../dcmdata/include/dcpixel.h \
  ../../ofstd/include/ofconsol.h ../../dcmdata/include/dcvrpobw.h \
  ../../dcmdata/include/dcvrobow.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcobject.h ../../dcmdata/include/dctag.h \
  ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dclist.h \
  ../../dcmdata/include/dcstack.h ../include/djeijg8.h \
  ../include/djencabs.h ../include/djeijg12.h
djencsv1.o: djencsv1.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/djencsv1.h \
  ../include/djcodece.h ../../ofstd/include/oftypes.h \
  ../../dcmdata/include/dccodec.h ../../dcmdata/include/dctypes.h \
  ../../ofstd/include/ofstdinc.h ../../dcmdata/include/dcerror.h \
  ../../ofstd/include/ofcond.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../../ofstd/include/ofstream.h \
  ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
  ../../ofstd/include/ofglobal.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/oflist.h ../include/djutils.h \
  ../../dcmimgle/include/diutils.h ../include/djcparam.h \
  ../include/djrplol.h ../../dcmdata/include/dcpixel.h \
  ../../ofstd/include/ofconsol.h ../../dcmdata/include/dcvrpobw.h \
  ../../dcmdata/include/dcvrobow.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcobject.h ../../dcmdata/include/dctag.h \
  ../../dcmdata/include/dctagkey.h ../../dcmdata/include/dclist.h \
  ../../dcmdata/include/dcstack.h ../include/djeijg8.h \
  ../include/djencabs.h ../include/djeijg12.h ../include/djeijg16.h
djrplol.o: djrplol.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/djrplol.h \
  ../../dcmdata/include/dcpixel.h ../../ofstd/include/ofconsol.h \
  ../../ofstd/include/ofstream.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/oftypes.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../../ofstd/include/ofstdinc.h \
  ../../dcmdata/include/dcvrpobw.h ../../dcmdata/include/dcvrobow.h \
  ../../dcmdata/include/dcelem.h ../../dcmdata/include/dcerror.h \
  ../../ofstd/include/ofcond.h ../../dcmdata/include/dctypes.h \
  ../../dcmdata/include/dcobject.h ../../ofstd/include/ofglobal.h \
  ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
  ../../dcmdata/include/dctag.h ../../dcmdata/include/dctagkey.h \
  ../../dcmdata/include/dclist.h ../../dcmdata/include/dcstack.h \
  ../../ofstd/include/oflist.h
djrploss.o: djrploss.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/djrploss.h \
  ../../dcmdata/include/dcpixel.h ../../ofstd/include/ofconsol.h \
  ../../ofstd/include/ofstream.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/oftypes.h ../../ofstd/include/ofstring.h \
  ../../ofstd/include/ofcast.h ../../ofstd/include/ofstdinc.h \
  ../../dcmdata/include/dcvrpobw.h ../../dcmdata/include/dcvrobow.h \
  ../../dcmdata/include/dcelem.h ../../dcmdata/include/dcerror.h \
  ../../ofstd/include/ofcond.h ../../dcmdata/include/dctypes.h \
  ../../dcmdata/include/dcobject.h ../../ofstd/include/ofglobal.h \
  ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
  ../../dcmdata/include/dctag.h ../../dcmdata/include/dctagkey.h \
  ../../dcmdata/include/dclist.h ../../dcmdata/include/dcstack.h \
  ../../ofstd/include/oflist.h
djutils.o: djutils.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/djutils.h \
  ../../ofstd/include/ofcond.h ../../ofstd/include/oftypes.h \
  ../../ofstd/include/ofstring.h ../../ofstd/include/ofcast.h \
  ../../ofstd/include/ofstdinc.h ../../ofstd/include/ofstream.h \
  ../../dcmimgle/include/diutils.h ../../dcmdata/include/dctypes.h \
  ../../ofstd/include/ofglobal.h ../../ofstd/include/ofthread.h \
  ../../dcmdata/include/dcdeftag.h ../../dcmdata/include/dctagkey.h \
  ../../dcmdata/include/dcitem.h ../../ofstd/include/ofconsol.h \
  ../../dcmdata/include/dcobject.h ../../dcmdata/include/dcerror.h \
  ../../dcmdata/include/dcxfer.h ../../dcmdata/include/dcvr.h \
  ../../dcmdata/include/dctag.h ../../dcmdata/include/dclist.h \
  ../../dcmdata/include/dcstack.h ../../dcmdata/include/dcvrui.h \
  ../../dcmdata/include/dcbytstr.h ../../dcmdata/include/dcelem.h \
  ../../dcmdata/include/dcpcache.h ../../ofstd/include/oflist.h
