tvrdatim.o: tvrdatim.cc ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/dcvrda.h ../include/dctypes.h \
  ../../ofstd/include/oftypes.h ../../ofstd/include/ofstdinc.h \
  ../include/dcbytstr.h ../../ofstd/include/ofconsol.h \
  ../../ofstd/include/ofstream.h ../../ofstd/include/ofthread.h \
  ../../ofstd/include/ofstring.h ../../ofstd/include/ofcast.h \
  ../include/dcerror.h ../../ofstd/include/ofcond.h ../include/dcelem.h \
  ../include/dcobject.h ../../ofstd/include/ofglobal.h \
  ../include/dcxfer.h ../include/dcvr.h ../include/dctag.h \
  ../include/dctagkey.h ../include/dclist.h ../include/dcstack.h \
  ../../ofstd/include/ofdate.h ../include/dcvrtm.h \
  ../../ofstd/include/oftime.h ../include/dcvrdt.h \
  ../../ofstd/include/ofdatime.h ../include/dcdeftag.h
